### ISSUE TITLE
ABR: [Star Wars Armada] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\skinn\AppData\Roaming\VASSAL\tiles\173a959e65447347f739ff8e4f100692d19b588a\1\13\1387e8b4038ab007bd865e0f02ae944c9349b026

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10202]
| Bugzilla |  |
|----------|----------|
| ID | BZ14601 |
| Reported | 2021-06-29 00:41:00 +0200 |
| Modified | 2021-06-29 00:41:42 +0200 |
| Product | VASSAL |
| Component | Unknown |
| Version | 3.5.7 |
| Platform | All |
| OS | All |
| Status | NEW |
| Resolution | None |
| Priority | unspecified |
| Severity | normal |
| Milestone | --- |
| Reporter | [Joel Uckelman](mailto:uckelman@nomic.net) |
| Assignee | [Bugs](mailto:bugs@vassalengine.org) |

| Attachments | |
|-------|-------|
| [errorLog](http://www.vassalengine.org/files/bz/13064) | [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-29 00:41:00 +0200 text/plain 7761 the errorLog |

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-29 00:41:40 +0200
<pre>skinnyj71@comcast.net

Openng a saved game

Star Wars Armada v4.4.0 3.5.7

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\skinn\AppData\Roaming\VASSAL\tiles\173a959e65447347f739ff8e4f100692d19b588a\1\13\1387e8b4038ab007bd865e0f02ae944c9349b026
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)</pre>

#### [Joel Uckelman](mailto:uckelman@nomic.net) 2021-06-29 00:41:42 +0200
<pre>Created attachment 13064
the errorLog</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
