### ISSUE TITLE
ExecutionException: java.lang.NullPointerException: Cannot invoke "String.substring(int)" because "s" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10206]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | uckelman@nomic.net |
| Error Log | [3531 bytes](http://www.vassalengine.org/files/gh/6decf4431985dae632dfa1d54c4c8ca5bfdef9e1) |

<pre>This is a test bug report.

3.5.8

java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "String.substring(int)" because "s" is null
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:424)
</pre>

**Comment by uckelman** [comment]
Closing test issue.
