### ISSUE TITLE
[HHF2 module] NullPointerException: Cannot invoke "java.awt.Image.getSource()" because "i" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10218]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | harm@snafu.de |
| Error Log | [16471 bytes](http://www.vassalengine.org/files/gh/ae545dd8670b524f3f01fc3e3279f6c4ec10c90f) |

<pre>creating a new scenario after removeing unused files while in edit mode

HHF2 module v2.0.0 3.5.8

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getSource()" because "i" is null
 at java.desktop/javax.swing.GrayFilter.createDisabledImageImpl(GrayFilter.java:63)
 at java.desktop/javax.swing.GrayFilter.lambda$createDisabledImage$0(GrayFilter.java:56)
 at java.desktop/sun.awt.image.MultiResolutionCachedImage.lambda$map$2(MultiResolutionCachedImage.java:126)
 at java.desktop/sun.awt.image.MultiResolutionCachedImage.getResolutionVariant(MultiResolutionCachedImage.java:84)
</pre>

**Comment by uckelman** [comment]
Looks like there's also an encoding problem here?
```
VASSAL.launch.Editor --edit-extension -- /11D SpielzubehÃ¶r/VASSAL/HurtgenHellsForest/HHF2_2_mh7.vmod /11D SpielzubehÃ¶r/VASSAL/HurtgenHellsForest/HHF2_2_mh7_ext/GOSS_log-utilities_0.2.vmdx
```

**Comment by Cattlesquat** [comment]
This would be a "Sudden Wizard Death Syndrome" except if you want to investigate the encoding
