### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10215]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [6165 bytes](http://www.vassalengine.org/files/gh/8b1305181a9ed3bd4005c68696553275554d5a28) |

<pre>

3.5.8

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:422)
</pre>

**Comment by uckelman** [comment]
My guess is that this is a misencoded entry in the ZIP header. The next step is to check the module.

**Comment by uckelman** [comment]
Duplicate of #10045.
