### ISSUE TITLE
[Scorched Earth] IllegalArgumentException: Invalid prefix or suffix

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10227]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [7539 bytes](http://www.vassalengine.org/files/gh/e317cf0ccca66a1e361fe01c05e79ee697119238) |

<pre>

Scorched Earth v4.42 3.5.8

java.lang.IllegalArgumentException: Invalid prefix or suffix
 at java.base/java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:60)
 at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:124)
 at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:158)
 at java.base/java.nio.file.Files.createTempFile(Files.java:872)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10226.
