### ISSUE TITLE
[Star Wars X-Wing Miniatures Game] NullPointerException: Cannot invoke "VASSAL.command.Command.execute()" because "tripleChoiceCommand" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10222]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [72488 bytes](http://www.vassalengine.org/files/gh/af26191496ee095f885a41457092349661208fc8) |

<pre>

Star Wars X-Wing Miniatures Game v9.2.2 3.5.8

java.lang.NullPointerException: Cannot invoke "VASSAL.command.Command.execute()" because "tripleChoiceCommand" is null
 at mic.MouseShipGUI.firstStageShipGUI(MouseShipGUI.java:425)
 at mic.MouseShipGUI$2.mousePressed(MouseShipGUI.java:239)
 at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
 at VASSAL.build.module.Map.mousePressed(Map.java:1733)
</pre>

**Comment by Cattlesquat** [comment]
Custom Code
