### ISSUE TITLE
[Star Wars X-Wing Miniatures Game] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10220]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | swaymepisas@gmail.com |
| Error Log | [181228 bytes](http://www.vassalengine.org/files/gh/738978a5b7efad4c56ab324255aa63db61887278) |

<pre>welcome page

Star Wars X-Wing Miniatures Game v9.2.2 3.5.8

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813.
