### ISSUE TITLE
GAME PIECE IMAGES - FILENAME VALIDATION - He put illegal character into a "text label on an image design" and it couldn't make the file - [Scorched Earth] IllegalArgumentException: Invalid prefix or suffix

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10226]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | jimsvassal@gmail.com |
| Error Log | [7539 bytes](http://www.vassalengine.org/files/gh/5132b43540941fdb102a43aef0715834ccf5addc) |

<pre>I put a value of  "MC.200/2" into a text label on an image design when it crashed.  When I put in "MC.200-2" it works fine without crashing.  When I use "MC.200/2" for the design name, it works fine.

Scorched Earth v4.42 3.5.8

java.lang.IllegalArgumentException: Invalid prefix or suffix
 at java.base/java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:60)
 at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:124)
 at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:158)
 at java.base/java.nio.file.Files.createTempFile(Files.java:872)
</pre>

**Comment by uckelman** [comment]
GPI needs to sanitize the display name before using it as a filename.
