### ISSUE TITLE
[SCS Panzer Battles - Chir River] IndexOutOfBoundsException: Index: 3, Length: 2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10238]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | myk@deans-inter.net |
| Error Log | [287389 bytes](http://www.vassalengine.org/files/gh/26994adeb94e5ae8c41602b84f855d0ba93ffb1e) |

<pre>Toolbar Menu edit, Cancel button

SCS Panzer Battles - Chir River v2.00 3.5.8

java.lang.IndexOutOfBoundsException: Index: 3, Length: 2
 at org.apache.commons.lang3.ArrayUtils.insert(ArrayUtils.java:3092)
 at VASSAL.configure.StringArrayConfigurer.addEntry(StringArrayConfigurer.java:325)
 at VASSAL.configure.ConfigurableListController.lambda$new$2(ConfigurableListController.java:51)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by Cattlesquat** [comment]
Looks like maybe he was trying to add one w/ the very bottom of the list selected or something? Maybe some kind of off-by-one error?   He says it's in "Toolbar Menu Edit, Cancel Button" if that rings any bells. For your possible interest @BrentEaston

**Comment by BrentEaston** [comment]
I have not been able to reproduce this under 3.6.0.  Let's see if we get any reports after the beta comes out.
