### ISSUE TITLE
[Battle Spirits TCG Online] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Hotaru\AppData\Roaming\VASSAL\tiles\d80dfa1105d5d8200e156afa9c7ca2783000ab12\9\9b\9b9237f9c590066c1b00dd4fb540d729af5cb706

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10236]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [23851 bytes](http://www.vassalengine.org/files/gh/7496bddc2533985eff82fe6353648ef030797141) |

<pre>

Battle Spirits TCG Online v1.0 3.5.8

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Hotaru\AppData\Roaming\VASSAL\tiles\d80dfa1105d5d8200e156afa9c7ca2783000ab12\9\9b\9b9237f9c590066c1b00dd4fb540d729af5cb706
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:319)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
