### ISSUE TITLE
[Absolute Victory] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\John Buerger's PC\AppData\Roaming\VASSAL\tiles\2bfeb856a529001c5b9dfa5e7669a6c2e18699cc\8\8d\8dfdd34c35ce1f6180766fe9dbd5169889c86254

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10242]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | john.buerger@newstpeters.org |
| Error Log | [12557 bytes](http://www.vassalengine.org/files/gh/31db339023760421b96bc14380136a1e16b4d77f) |

<pre>I was just trying to load Vassal module "Absolute Victory" 1.1 game, using Vassal engine 3.5.8.  

Absolute Victory v1.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\John Buerger's PC\AppData\Roaming\VASSAL\tiles\2bfeb856a529001c5b9dfa5e7669a6c2e18699cc\8\8d\8dfdd34c35ce1f6180766fe9dbd5169889c86254
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Dupe #9957
