### ISSUE TITLE
[Hood Strikes North v3.01] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10244]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [35514 bytes](http://www.vassalengine.org/files/gh/ae08bcd666cd44af3d9661d60a795ed68955edf0) |

<pre>

Hood Strikes North v3.01 vHSN 3.01 3.5.8

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3424)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3410)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:425)
</pre>

**Comment by Cattlesquat** [comment]
"Caused by: an unexpected network error occurred"
