### ISSUE TITLE
[Lynnvander_07_TD] ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10252]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | josh.derksen@gmail.com |
| Error Log | [8878 bytes](http://www.vassalengine.org/files/gh/0c0413fe5b02d9c9bf446063e3c5613d1e36ed39) |

<pre>added a new board and selected a new default board setup using it while a game was running. 3 total boards are now arranged in a 2x2 layout with the bottom left cell empty (if that matters).

Lynnvander_07_TD v0.2 3.5.8

java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
 at VASSAL.build.module.Map.getLocation(Map.java:2417)
 at VASSAL.build.module.Map.getLocation(Map.java:2397)
 at VASSAL.build.module.Map.drawBoardsInRegion(Map.java:2059)
 at VASSAL.build.module.Map.paintRegion(Map.java:2040)
</pre>

**Comment by Cattlesquat** [comment]
This code is getting some kind of out-of-bounds problem

`  protected Point getLocation(int column, int row, double zoom) {
    final Point p = new Point();
    for (int x = 0; x < column; ++x) {
      p.translate((int) Math.floor(zoom * boardWidths[x][row]), 0);
    }
    for (int y = 0; y < row; ++y) {
      p.translate(0, (int) Math.floor(zoom * boardHeights[column][y]));
    }
    return p;
  }
`

**Comment by Cattlesquat** [comment]
Well it used to look all nicely indented with CRs and stuff
