### ISSUE TITLE
[World in Flames Collectors Edition] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10260]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | paulkt+vassal@gamail.com |
| Error Log | [579853 bytes](http://www.vassalengine.org/files/gh/1255833f121bc41aa6ec0daedb3feed614cda552) |

<pre>had WiF 1.04 open (from a PC sleep) then opened Mark Benson's new Flying Colors mdoule		

World in Flames Collectors Edition v1.04.P 3.5.8

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3424)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3410)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:425)
</pre>

**Comment by Cattlesquat** [comment]
Caused by: java.io.IOException: A device which does not exist was specified

(it's a wake-from-sleep, timed-out-Dropbox, kind of situation)
