### ISSUE TITLE
[Race to Tokyo: Battle for Japan, 1946] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Administrator\AppData\Roaming\VASSAL\tiles\ddb824f9121c95af37dc2d985d6f477692953192\0\0d\0df158ad1b7060cb01743cd7d837eeb73efeccf0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10290]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [13908 bytes](http://www.vassalengine.org/files/gh/44c29954113f877f4699fa89e21d04456e3f2fa3) |

<pre>

Race to Tokyo: Battle for Japan, 1946 v2.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Administrator\AppData\Roaming\VASSAL\tiles\ddb824f9121c95af37dc2d985d6f477692953192\0\0d\0df158ad1b7060cb01743cd7d837eeb73efeccf0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
