### ISSUE TITLE
[Midway(Playtest)] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10300]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | Harald@protonmail.com |
| Error Log | [9217 bytes](http://www.vassalengine.org/files/gh/475148073063a7e59ca5576edd5afe27d0f50cb7) |

<pre>I deleted two boards from a developmental version of Midway1964 in the editor with pieces on them and saved the game. I still have a pre-defined setup that refers to the deleted boards. I am filling this out just in case you are interested, not to claim a bug.

Midway(Playtest) v2.0b1 3.5.8

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
 at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
 at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
 at java.base/java.util.TimSort.sort(TimSort.java:245)
</pre>

**Comment by uckelman** [comment]
Duplicate of #8949.
