### ISSUE TITLE
[Cuius Regius] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Marc_Alda\AppData\Roaming\VASSAL\tiles\c0a135aeba1c171791876fd1ffed9a2536b3eff2\f\f4\f4be720ea5425e9d1a17935d796fb48bbf68c5f5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10307]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | maliaga12@gmail.com |
| Error Log | [11833 bytes](http://www.vassalengine.org/files/gh/91e9c608431dc186b2db552dda3c82a7232bf1ab) |

<pre>DATA MODULE ERROR: GTC_front. jpg not found

Cuius Regius v1.8 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Marc_Alda\AppData\Roaming\VASSAL\tiles\c0a135aeba1c171791876fd1ffed9a2536b3eff2\f\f4\f4be720ea5425e9d1a17935d796fb48bbf68c5f5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
