### ISSUE TITLE
[La Belle Epoque] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Tom\AppData\Roaming\VASSAL\tiles\4dd249ba4efc5ae3bee6108ee78f9ad35a70a92b\b\bd\bda8c00946252e6f8fe9e634df434c2dc6578750

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10308]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | tdchistorian@gmail.com |
| Error Log | [15180 bytes](http://www.vassalengine.org/files/gh/9f6b787b04b64eef781a3373c91c3f716ef8fb00) |

<pre>Just booting up new build.  The ONLY files installed are a main map file and a chart map file.

Thus it's interesting that the Tile cashe error: Tile not found has a list of over a dozen files that didn't load.  BUT THERE"S ONLY TWO !!!!

Just Amazing

Tom Cundiff

La Belle Epoque vv1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Tom\AppData\Roaming\VASSAL\tiles\4dd249ba4efc5ae3bee6108ee78f9ad35a70a92b\b\bd\bda8c00946252e6f8fe9e634df434c2dc6578750
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
