### ISSUE TITLE
[La Belle Epoque] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Tom\AppData\Roaming\VASSAL\tiles\4dd249ba4efc5ae3bee6108ee78f9ad35a70a92b\b\bd\bda8c00946252e6f8fe9e634df434c2dc6578750

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10309]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | tdchistorian@gmail.com |
| Error Log | [25274 bytes](http://www.vassalengine.org/files/gh/075981df809f78151256b98b6f767fee0fb5c447) |

<pre>Didn't even try to tile the files, of which there are STILL ONLY TWO!

La Belle Epoque vv1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Tom\AppData\Roaming\VASSAL\tiles\4dd249ba4efc5ae3bee6108ee78f9ad35a70a92b\b\bd\bda8c00946252e6f8fe9e634df434c2dc6578750
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
