### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10317]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [13237 bytes](http://www.vassalengine.org/files/gh/9fd550739965aba3e09fecf9b61f045c39b95ce0) |

<pre>

3.5.8

VASSAL.tools.image.UnrecognizedImageTypeException: images\Iconshock-Real-Vista-Mail-Robot.ico
 at VASSAL.tools.image.ImageIOImageLoader$1.run(ImageIOImageLoader.java:442)
 at VASSAL.tools.image.ImageIOImageLoader$1.run(ImageIOImageLoader.java:428)
 at VASSAL.tools.image.ImageIOImageLoader.wrapImageIO(ImageIOImageLoader.java:395)
 at VASSAL.tools.image.ImageIOImageLoader.load(ImageIOImageLoader.java:346)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10263.
