### ISSUE TITLE
[WiF CE Maps and Units] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10323]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | donsgeneralstuff@exemail.com.au |
| Error Log | [625809 bytes](http://www.vassalengine.org/files/gh/8bde33f4e3397d240467499f0a4749fad80e2eb1) |

<pre>Same as before. There are no mouse button/keyboard press issues. 

WiF CE Maps and Units v2.8 3.5.8

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10322.
