### ISSUE TITLE
[The Greatest Day: Sword, Juno and Gold Beaches] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Don\AppData\Roaming\VASSAL\tiles\7bb4421671880bba9f9d1207e45cf3c4f0217125\8\8c\8ca6e7cefa17326e299d7044c55823fd8e270d41

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10327]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [11004 bytes](http://www.vassalengine.org/files/gh/14704809aa463e394bfe964f2a61b108eea17a52) |

<pre>Opening a game

The Greatest Day: Sword, Juno and Gold Beaches v1.8.9 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Don\AppData\Roaming\VASSAL\tiles\7bb4421671880bba9f9d1207e45cf3c4f0217125\8\8c\8ca6e7cefa17326e299d7044c55823fd8e270d41
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
