### ISSUE TITLE
[Unconditional Surrender!] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\MatteoBetta\AppData\Roaming\VASSAL\tiles\1698cd599c1a025eaed6cd111cb0849e3ce30136\9\94\94861ea48a07d87051f9c082ee2ada8833993854

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10321]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [21730 bytes](http://www.vassalengine.org/files/gh/2ed696ee4602915fc7c2846ca616890957790286) |

<pre>

Unconditional Surrender! v2.3.4.4 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\MatteoBetta\AppData\Roaming\VASSAL\tiles\1698cd599c1a025eaed6cd111cb0849e3ce30136\9\94\94861ea48a07d87051f9c082ee2ada8833993854
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
