### ISSUE TITLE
[??????1.0?] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Administrator\AppData\Roaming\VASSAL\tiles\2c36a7f5050c085ee57c8631116bf47a47882b09\0\03\03a6530ffaac00cb9083e622d916d1374df995ae

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10339]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [13403 bytes](http://www.vassalengine.org/files/gh/b36bc32f8d46364e837840df9eb1515e8bc95026) |

<pre>

??????1.0? v1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Administrator\AppData\Roaming\VASSAL\tiles\2c36a7f5050c085ee57c8631116bf47a47882b09\0\03\03a6530ffaac00cb9083e622d916d1374df995ae
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
