### ISSUE TITLE
[Three Days of Gettysburg] ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10333]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | vze268df@verizon.net |
| Error Log | [13541 bytes](http://www.vassalengine.org/files/gh/a99961cfdd1f5bb3ead53bd027cf618229b7381c) |

<pre>restarting

Three Days of Gettysburg v1.27 3.5.8

java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 3
 at VASSAL.counters.Stack.lambda$getShape$1(Stack.java:437)
 at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
 at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
</pre>

**Comment by Cattlesquat** [comment]
See also #9975
