### ISSUE TITLE
[Battle Spirits] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Utente\AppData\Roaming\VASSAL\tiles\60fdf587189c3f00004ed3bf01c13a4a11737c3b\7\76\76ac25240687bfdd9fb65df1f1549874350ffb2b

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10338]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [12781 bytes](http://www.vassalengine.org/files/gh/0a9c81b4167c6174644cc6131fc997ebfb8bfd4b) |

<pre>

Battle Spirits v1.4 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Utente\AppData\Roaming\VASSAL\tiles\60fdf587189c3f00004ed3bf01c13a4a11737c3b\7\76\76ac25240687bfdd9fb65df1f1549874350ffb2b
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
