### ISSUE TITLE
[Strike of the Eagle] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Pablo\AppData\Roaming\VASSAL\tiles\6a5cb61f72a3b58ef3727930149bea6819890c50\8\85\85883e211f9800965d1fdebeff5848c2e2b91b68

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10335]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | vze268df@verizon,net |
| Error Log | [68568 bytes](http://www.vassalengine.org/files/gh/a40261e213723f311d6c0aa9b0f70b1f7808ed3e) |

<pre>

Strike of the Eagle v1.3 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Pablo\AppData\Roaming\VASSAL\tiles\6a5cb61f72a3b58ef3727930149bea6819890c50\8\85\85883e211f9800965d1fdebeff5848c2e2b91b68
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
