### ISSUE TITLE
[Blue Cross White Ensign] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Owner\AppData\Roaming\VASSAL\tiles\6084ef0b8515365f4d57b844fad307d8b18ed4cf\1\14\14c46c0debad72ce5dace7c10e8272f6d687a24c

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10343]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | albrasington@gmail.com |
| Error Log | [16777 bytes](http://www.vassalengine.org/files/gh/418470276902b0f9f90397017753ffe9b206960d) |

<pre>opening blue cross and white ensign module

Blue Cross White Ensign v1.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Owner\AppData\Roaming\VASSAL\tiles\6084ef0b8515365f4d57b844fad307d8b18ed4cf\1\14\14c46c0debad72ce5dace7c10e8272f6d687a24c
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
