### ISSUE TITLE
[The Burning Blue solo] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10357]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | myk@deans-inter.net |
| Error Log | [275642 bytes](http://www.vassalengine.org/files/gh/5b2c1c5dc3df532d51d2a0a591c8597763d670cb) |

<pre>Map Window - At-StartStack - Edit All Pieces
Move Prototype to top 
Move Prototype up
[Freeze]

The Burning Blue solo v1.0 3.5.8

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:303)
</pre>

**Comment by Cattlesquat** [comment]
(edit all pieces)
