### ISSUE TITLE
[??????????????????] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\14293\AppData\Roaming\VASSAL\tiles\7cc86ce0f278072f2933320b32561042db1c0ec6\9\98\986d33a74e4214d00473a9314d6d01d7f2da9412

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10365]
| ABR | |
|-----|-----|
| Version | 3.6.0-beta1 |
| Reporter |  |
| Error Log | [20584 bytes](http://www.vassalengine.org/files/gh/7ff9aed420480fc4705c16fe6614940319718a77) |

<pre>

?????????????????? v1.9 3.6.0-beta1

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\14293\AppData\Roaming\VASSAL\tiles\7cc86ce0f278072f2933320b32561042db1c0ec6\9\98\986d33a74e4214d00473a9314d6d01d7f2da9412
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
