### ISSUE TITLE
[Battlestar Galactica FFG] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\ja\AppData\Roaming\VASSAL\tiles\41d9f5904d73a5ec4053c6705f353f4fa737127b\1\15\153b65194029760902e2657d7f778459704769a1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10363]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [11335 bytes](http://www.vassalengine.org/files/gh/56ef3ec5407b93f0ab855274bc6da401b8eadbb3) |

<pre>

Battlestar Galactica FFG v4.6.4 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\ja\AppData\Roaming\VASSAL\tiles\41d9f5904d73a5ec4053c6705f353f4fa737127b\1\15\153b65194029760902e2657d7f778459704769a1
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
