### ISSUE TITLE
[A las Barricadas!  -  2nd Edition] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10375]
| ABR | |
|-----|-----|
| Version | 3.6.0-beta1 |
| Reporter | cr125rulz@gmail.com |
| Error Log | [14737 bytes](http://www.vassalengine.org/files/gh/80c9002f2cb2497100a1f7f5382974d818c58713) |

<pre>Testing Dynamic Property for formation assigement

A las Barricadas!  -  2nd Edition v3.06 3.6.0-beta1

java.lang.NullPointerException: null
 at VASSAL.build.module.properties.EnumeratedPropertyPrompt.getNewValue(EnumeratedPropertyPrompt.java:58)
 at VASSAL.counters.DynamicProperty.myKeyEvent(DynamicProperty.java:270)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:489)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:490)
</pre>

**Comment by uckelman** [comment]
@BrentEaston This is throwing an NPE when setting up an `AuditTrail`. It looks like `constraints` is null.
