### ISSUE TITLE
[La Bataille Talavera] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Acer\AppData\Roaming\VASSAL\tiles\086dfa184829b621ee34a796fcbf9d13ab0d4dbf\f\f4\f4a8f90ba3a60534753ca789fb56a0a10b89f128

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10373]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | alanfranz@alice.it |
| Error Log | [30735 bytes](http://www.vassalengine.org/files/gh/46382ecbaaad49709c1062e86f475fee1c838e4d) |

<pre>aprivo un nuovo gioco

La Bataille Talavera v2.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Acer\AppData\Roaming\VASSAL\tiles\086dfa184829b621ee34a796fcbf9d13ab0d4dbf\f\f4\f4a8f90ba3a60534753ca789fb56a0a10b89f128
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
