### ISSUE TITLE
[MagicRealmEXP] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\patris\AppData\Roaming\VASSAL\tiles\e7f0e7bd68033ac9960dba39bb72ff1e69a03c2b\9\98\987e0cd64ee57f61903da7fc986ecddb217f56ec

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10377]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [21064 bytes](http://www.vassalengine.org/files/gh/5e2bce157e811e85a270c638d5118b26f46eed7e) |

<pre>

MagicRealmEXP v1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\patris\AppData\Roaming\VASSAL\tiles\e7f0e7bd68033ac9960dba39bb72ff1e69a03c2b\9\98\987e0cd64ee57f61903da7fc986ecddb217f56ec
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
