### ISSUE TITLE
[Holland '44] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10374]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [13551 bytes](http://www.vassalengine.org/files/gh/29fa96923789daedfcbfcaf91f8e342a4ae3e7d3) |

<pre>

Holland '44 v0.92 3.5.8

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813.
