### ISSUE TITLE
[Gloomhaven] ClassCastException: class VASSAL.build.module.map.DeckGlobalKeyCommand$DeckGlobalCommand cannot be cast to class VASSAL.script.expression.Auditable (VASSAL.build.module.map.DeckGlobalKeyCommand$DeckGlobalCommand and VASSAL.script.expression.Auditable are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10370]
| ABR | |
|-----|-----|
| Version | 3.6.0-beta1 |
| Reporter |  |
| Error Log | [342769 bytes](http://www.vassalengine.org/files/gh/8d0bd65d95a850efe558a0fac52003e244ec55a4) |

<pre>

Gloomhaven v2.0 3.6.0-beta1

java.lang.ClassCastException: class VASSAL.build.module.map.DeckGlobalKeyCommand$DeckGlobalCommand cannot be cast to class VASSAL.script.expression.Auditable (VASSAL.build.module.map.DeckGlobalKeyCommand$DeckGlobalCommand and VASSAL.script.expression.Auditable are in unnamed module of loader 'app')
 at VASSAL.build.module.map.DeckGlobalKeyCommand$DeckGlobalCommand.apply(DeckGlobalKeyCommand.java:255)
 at VASSAL.build.module.map.DeckGlobalKeyCommand.apply(DeckGlobalKeyCommand.java:156)
 at VASSAL.build.module.map.DeckGlobalKeyCommand$DeckKeyCommand.actionPerformed(DeckGlobalKeyCommand.java:139)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10359.
