### ISSUE TITLE
[Battle Spirits TCG Online] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/kendall/Library/Application Support/VASSAL/tiles/d80dfa1105d5d8200e156afa9c7ca2783000ab12/1/14/141c0208046a9337741b4c13789675cbc4d546c2

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10419]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [14450 bytes](https://vassalengine.org/files/gh/a5d64a74456901dec7d0d417f43ef1d681ecb5f5) |

<pre>

Battle Spirits TCG Online v1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/kendall/Library/Application Support/VASSAL/tiles/d80dfa1105d5d8200e156afa9c7ca2783000ab12/1/14/141c0208046a9337741b4c13789675cbc4d546c2
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of#9957.
