### ISSUE TITLE
[Hood Strikes North v3.08] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/MB_ALBERTO/Library/Application Support/VASSAL/tiles/1a6cbc7ef24b9aeb932b4a6727d2dee2b3f0acd1/9/96/96760fa9c55bac61e28b56579b2b44ff625bb05d

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10417]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [10645 bytes](http://www.vassalengine.org/files/gh/a8fe1c77e23f1eb1d326502460e48324c4a4847e) |

<pre>

Hood Strikes North v3.08 vHSN 3.08 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/MB_ALBERTO/Library/Application Support/VASSAL/tiles/1a6cbc7ef24b9aeb932b4a6727d2dee2b3f0acd1/9/96/96760fa9c55bac61e28b56579b2b44ff625bb05d
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
