### ISSUE TITLE
[WiF CE Maps and Units] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Miguel Viana\AppData\Roaming\VASSAL\tiles\2da5ed55f073f5aa4a982fb84d0f4798c924353c\a\ad\ad0cd78acf57672ef250fec6cc9a34125177974a

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10413]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | miguelviana24@gmail.com |
| Error Log | [8259 bytes](http://www.vassalengine.org/files/gh/d16fc737b0bc0f6e9db456696e58ff54dddbf855) |

<pre>open file.

WiF CE Maps and Units v2.94a 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Miguel Viana\AppData\Roaming\VASSAL\tiles\2da5ed55f073f5aa4a982fb84d0f4798c924353c\a\ad\ad0cd78acf57672ef250fec6cc9a34125177974a
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
