### ISSUE TITLE
[High Frontier 4 All] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Ege\AppData\Roaming\VASSAL\tiles\77fe8ab5686a12e8599167d53d290a20102cb281\0\09\093a39639b023f7f1ab41dc1dc6b7a282ef5ebc7

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10418]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | eugenio.realini@gmail.com |
| Error Log | [13978 bytes](https://vassalengine.org/files/gh/d2a28f21cd36f1d7d9de4baf1624dffcb2b05de8) |

<pre>Opening the players' mat window in High Frontier

High Frontier 4 All v1.6 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Ege\AppData\Roaming\VASSAL\tiles\77fe8ab5686a12e8599167d53d290a20102cb281\0\09\093a39639b023f7f1ab41dc1dc6b7a282ef5ebc7
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
