### ISSUE TITLE
[RBS Deluxe Edition] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\John\AppData\Roaming\VASSAL\tiles\d0b92d82a146950ee398b0e787d80ece748ea367\8\85\859c443387db87d9177d50eaf3e30b5791d81aea

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10420]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | jazzcan37@gmail.com |
| Error Log | [26264 bytes](https://vassalengine.org/files/gh/af93739dd039a4c7e29f27636afe8aea164e3d5f) |

<pre>

RBS Deluxe Edition vRSBDE-v1.1.1b02.vmod 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\John\AppData\Roaming\VASSAL\tiles\d0b92d82a146950ee398b0e787d80ece748ea367\8\85\859c443387db87d9177d50eaf3e30b5791d81aea
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
