### ISSUE TITLE
[JWC06?????MINSK&RIGA] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10423]
| ABR | |
|-----|-----|
| Version | 3.6.0-beta2 |
| Reporter |  |
| Error Log | [9173 bytes](https://vassalengine.org/files/gh/6e918a79342b29a1bf27cf48d18dd9a03d4608e1) |

<pre>

JWC06?????MINSK&RIGA v1.0 3.6.0-beta2

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813.
