### ISSUE TITLE
[Commands & Colors: Napoleonics] ArrayIndexOutOfBoundsException: Index 53131 out of bounds for length 53131

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10422]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [235522 bytes](https://vassalengine.org/files/gh/c3dd26fe18a4c8652a00f4ba56890b8b3fcb9bb1) |

<pre>

Commands & Colors: Napoleonics v4.0.2 3.5.8

java.lang.ArrayIndexOutOfBoundsException: Index 53131 out of bounds for length 53131
 at java.base/java.util.HashMap.valuesToArray(HashMap.java:975)
 at java.base/java.util.HashMap$Values.toArray(HashMap.java:1052)
 at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
 at VASSAL.build.module.GameState.getRestorePiecesCommand(GameState.java:1060)
</pre>

**Comment by Cattlesquat** [comment]
It is a shame to have an array of 53,131 perfectly good items and overshoot it by one!

**Comment by Cattlesquat** [comment]
Loading game from wizard & getting "weird result" => probably an unwarned wrong-module-version type error.
