### ISSUE TITLE
[System W39] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\laszc\AppData\Roaming\VASSAL\tiles\6f53612f38fc94b1ae80b5409dac8a28ccf4f741\e\e1\e11b9f2cb63afe35e3d48eff5dfd30210eacb165

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10426]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | modelarzkolejowy@wp.pl |
| Error Log | [715638 bytes](https://vassalengine.org/files/gh/fde0dc20a5349a569fc919cd21c6d6bd41aa27f3) |

<pre>Nothing, this dialog appeared while the opening of session.

System W39 v4.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\laszc\AppData\Roaming\VASSAL\tiles\6f53612f38fc94b1ae80b5409dac8a28ccf4f741\e\e1\e11b9f2cb63afe35e3d48eff5dfd30210eacb165
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
