### ISSUE TITLE
[???] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\??\AppData\Roaming\VASSAL\tiles\07ebee0b99352818bce9cae4769338cc1750288d\4\40\40fe26acaf6175ef1774b9b8b2dd3477eeb1b699

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10433]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [17698 bytes](https://vassalengine.org/files/gh/3c0530ac335a9e6f1a4077e2b2b8ad75cb19e9e5) |

<pre>

??? vVer 1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\??\AppData\Roaming\VASSAL\tiles\07ebee0b99352818bce9cae4769338cc1750288d\4\40\40fe26acaf6175ef1774b9b8b2dd3477eeb1b699
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
