### ISSUE TITLE
[Panzer Grenadier - Über] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/Pimalteno/Library/Application Support/VASSAL/tiles/4a4e5c0d973dec868af5022af3f889f072ce2c6b/a/a7/a79dd155f8af54d36286bcccaa7cc393a641485c

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10431]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | felipe@jacomeconsulting.com |
| Error Log | [29709 bytes](https://vassalengine.org/files/gh/7800ba6fbe7fc3e47a8d4e500487126fb5bf5251) |

<pre>Trying to clear the tile cache

Panzer Grenadier - Über v3.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/Pimalteno/Library/Application Support/VASSAL/tiles/4a4e5c0d973dec868af5022af3f889f072ce2c6b/a/a7/a79dd155f8af54d36286bcccaa7cc393a641485c
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
