### ISSUE TITLE
[Napoleon3 LMap (4th ed)] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/jsdouglass/Library/Application Support/VASSAL/tiles/42d68cc0dc4b54be5b45d4d32204febbe28344fd/1/1d/1d56c2ed7028b977f88fa1f327151406579ecb14

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10438]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [10827 bytes](https://vassalengine.org/files/gh/f80c6f04aabbf7b25380715b67f2b25d2005c883) |

<pre>starting a modual

Napoleon3 LMap (4th ed) v1.1LMap 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/jsdouglass/Library/Application Support/VASSAL/tiles/42d68cc0dc4b54be5b45d4d32204febbe28344fd/1/1d/1d56c2ed7028b977f88fa1f327151406579ecb14
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
