### ISSUE TITLE
[TRC3] NoSuchMethodError: 'java.lang.String VASSAL.build.module.Map.getFullLocationName(java.awt.Point, boolean)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10442]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [6036 bytes](https://vassalengine.org/files/gh/e6bfc4ab4ac4ce7e056cc199578dcc413cacc595) |

<pre>

TRC3 v2.3 3.5.8

java.lang.NoSuchMethodError: 'java.lang.String VASSAL.build.module.Map.getFullLocationName(java.awt.Point, boolean)'
 at Inventory.Inventory.generateInventory(Inventory.java:163)
 at Inventory.Inventory$1.actionPerformed(Inventory.java:99)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
</pre>

**Comment by uckelman** [comment]
Custom code is calling a function which doesn't exist.
