### ISSUE TITLE
[Battle for Moscow (CGSC)] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10448]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | james.sterrett@gmail.com |
| Error Log | [8024 bytes](https://vassalengine.org/files/gh/2df006b3b0bba0bed487dad6863ece982619c962) |

<pre>Logging in

Battle for Moscow (CGSC) v1.1 3.5.8

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813.
