### ISSUE TITLE
[NATO Designer Signature Ed.] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Charlie\AppData\Roaming\VASSAL\tiles\7ca393ef4590fe95747f3ed4ca6cea2f7328bf10\7\71\71dd857d0a8a1432052c46aca6760993b6f5849a

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10453]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | dave_j_march@yahoo.co.uk |
| Error Log | [56914 bytes](https://vassalengine.org/files/gh/d9bc40209d2a7f32731ac42379ecdece86dca90b) |

<pre>NATO 1.2 Just opened. Requester box for Start New Logfile had just appeared

NATO Designer Signature Ed. v1.2 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Charlie\AppData\Roaming\VASSAL\tiles\7ca393ef4590fe95747f3ed4ca6cea2f7328bf10\7\71\71dd857d0a8a1432052c46aca6760993b6f5849a
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
