### ISSUE TITLE
[BCS-Last Blitzkrieg] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getId()" because "p" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10469]
| ABR | |
|-----|-----|
| Version | 3.6.0-beta2 |
| Reporter | jimpyle48@comcast.net |
| Error Log | [33400 bytes](https://vassalengine.org/files/gh/c7be038ab5b49cf79a12978ea1f53f853520880f) |

<pre>Tools/Refresh/Run

BCS-Last Blitzkrieg vver 3.6 Beta2 TEST 3.6.0-beta2

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getId()" because "p" is null
 at VASSAL.counters.Mat.myGetState(Mat.java:88)
 at VASSAL.counters.Decorator.getState(Decorator.java:399)
 at VASSAL.command.AddPiece.<init>(AddPiece.java:39)
 at VASSAL.build.module.Map.placeAt(Map.java:2900)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10468.
