### ISSUE TITLE
[Lincoln's War] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/Stephen/Library/Application Support/VASSAL/tiles/4fae6ba24739eeff50daae39f9001b36adeca512/9/93/930f761302241fedeb225462bbe322b3e8ec5e21

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10473]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [25439 bytes](https://vassalengine.org/files/gh/5401d14f353aae05ce23da1a4e8b662608a2df84) |

<pre>Opened Lincoln's War

Lincoln's War v2.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /Users/Stephen/Library/Application Support/VASSAL/tiles/4fae6ba24739eeff50daae39f9001b36adeca512/9/93/930f761302241fedeb225462bbe322b3e8ec5e21
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
