### ISSUE TITLE
[Highway to the Reich (SPI)] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10480]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | allendkrsn@yahoo.com |
| Error Log | [7414 bytes](https://vassalengine.org/files/gh/f7d44e66bf3deb2fb75e4dda5b981d80d4907d61) |

<pre>Attempting to arrange icon bar elements in desired order.

Highway to the Reich (SPI) v1.51 3.5.8

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
 at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
 at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
 at java.base/java.util.TimSort.sort(TimSort.java:245)
</pre>

**Comment by uckelman** [comment]
Duplicate of #8949.
