### ISSUE TITLE
[Red Star Rising(???)] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\john\AppData\Roaming\VASSAL\tiles\d2a2cf9821defa9c61323f86c3aa941abdbb4001\d\d9\d90c3f19a813c717c74845134ed844a409a45b6a

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10497]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [14073 bytes](https://vassalengine.org/files/gh/a8b04f57b59ef6815492eb75a39018a6451f60bd) |

<pre>

Red Star Rising(???) v4.0.8 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\john\AppData\Roaming\VASSAL\tiles\d2a2cf9821defa9c61323f86c3aa941abdbb4001\d\d9\d90c3f19a813c717c74845134ed844a409a45b6a
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
