### ISSUE TITLE
[LF1 module] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10490]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [641155 bytes](https://vassalengine.org/files/gh/1f586b6d8625e55eb4a640b50fbd8944e10f67c3) |

<pre>

LF1 module v1.1 3.5.8

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3424)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3410)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:425)
</pre>

**Comment by uckelman** [comment]
`Caused by: java.io.IOException: The device is not ready` ---> This makes it look like a problem with the drive.
