### ISSUE TITLE
[1931 Campaign Board] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\taylo\AppData\Roaming\VASSAL\tiles\8f9527d5a91ecb7ce470f58b4b6b3236a0e78d2e\7\75\754485724c6a03f98cb300952d8e156457f421b6

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10499]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [13033 bytes](https://vassalengine.org/files/gh/1c354de3ead7be47f25fcbabfa1fa88536cd2348) |

<pre>I opened the file lol your software is gash

1931 Campaign Board v0.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\taylo\AppData\Roaming\VASSAL\tiles\8f9527d5a91ecb7ce470f58b4b6b3236a0e78d2e\7\75\754485724c6a03f98cb300952d8e156457f421b6
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:319)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
