### ISSUE TITLE
[Montmirail and Vauchamps 1814 JDG] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10503]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | markben61@gmail.com |
| Error Log | [547604 bytes](https://vassalengine.org/files/gh/c0145cc09d269f0feb71ae4eb1826eb51e31d4ae) |

<pre>Trying to replicate 10488.
I deleted a components from the module (Montmirails & Vauchamps JdG),
saving to another file name as I went.
I had a game open in the module. 
No exceptions until I closed the the game, then immediate exception.

Montmirail and Vauchamps 1814 JDG v1.1.0a03 3.5.8

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.TimSort.mergeLo(TimSort.java:781)
 at java.base/java.util.TimSort.mergeAt(TimSort.java:518)
 at java.base/java.util.TimSort.mergeCollapse(TimSort.java:448)
 at java.base/java.util.TimSort.sort(TimSort.java:245)
</pre>

**Comment by uckelman** [comment]
Duplicate of #8949.
