### ISSUE TITLE
[High Frontier 4 All] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Ege\AppData\Roaming\VASSAL\tiles\77fe8ab5686a12e8599167d53d290a20102cb281\0\09\093a39639b023f7f1ab41dc1dc6b7a282ef5ebc7

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10522]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | eugenio.realini@gmail.com |
| Error Log | [12888 bytes](https://vassalengine.org/files/gh/00e213c6bfbc0bbfce27c1ec05bc11a2e4943b21) |

<pre>Bug 9957 resurfaced... In my last email I wrote that it was not appearing anymore, but apparently it was too early to say that :)
This time I simply loaded a log file, played it, started a new one, opened the players' boards and the bug appeared. I am using an external UHD screen through HDMI cable, not sure if it is relevant.

High Frontier 4 All v1.6 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Ege\AppData\Roaming\VASSAL\tiles\77fe8ab5686a12e8599167d53d290a20102cb281\0\09\093a39639b023f7f1ab41dc1dc6b7a282ef5ebc7
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by ege010** [comment]
Hi. Just after having reported this bug, I disconnected the UHD screen (an OLED TV) while keeping Windows running, opened the laptop lid, loaded the same log, played it, started a new one as before, opened the playmats' screen... and the bug did not appear.

Note that I had tried twice the same procedure with the UHD screen connected, and in both cases, the bug appeared.

When I use the UHD screen, Windows automatically sets some level of zoom in order to make the text readable. Maybe it has something to do with that?

Hope this helps.

**Comment by ege010** [comment]
I ran the "missing_tile_diagnostic" development build, triggered the bug and sent you the error log by email.
