### ISSUE TITLE
[Empire of the Sun (2nd Edition)] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10532]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | kdtbtaylor@hotmail.com |
| Error Log | [301645 bytes](https://vassalengine.org/files/gh/d3e6d78d3bc9c278ae012bafc2b8e47e582dc0d5) |

<pre>moving pieces 

Empire of the Sun (2nd Edition) v5.0 revisión 9 3.5.8

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3424)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3410)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:425)
</pre>

**Comment by Cattlesquat** [comment]
Caused by: java.io.IOException: The volume for a file has been externally altered so that the opened file is no longer valid
