### ISSUE TITLE
[Caesar(at Alesia)] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /home/stephen/.VASSAL/tiles/639a07af845db93c4fa1e3b2e25a6e2effa1b795/8/82/8258b2ef55bee47ab0434b2f52e912b898898224

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10539]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | sagenoff@gmail.com |
| Error Log | [44856 bytes](https://vassalengine.org/files/gh/aa751143fb2954dcb1356f7797979df13010149c) |

<pre>Loading game continuation file.   Some of the counters displayed but there was no background map.

Caesar(at Alesia) v1.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: /home/stephen/.VASSAL/tiles/639a07af845db93c4fa1e3b2e25a6e2effa1b795/8/82/8258b2ef55bee47ab0434b2f52e912b898898224
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
