### ISSUE TITLE
[No Retreat 3: The French and Polish Fronts] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\DELL\AppData\Roaming\VASSAL\tiles\8c00c15c6482ac24a8f4a1734073cd0821163cf3\3\35\35958c539abbb5ca14f471e651a61416a9917bbe

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10556]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | tao12318@outlook.com |
| Error Log | [21366 bytes](https://vassalengine.org/files/gh/07aa963b9788c8a34d65b4ed4f16e4ae8ca76423) |

<pre>Opening <No Retreat 3!:The French and Polish Fronts 1.1.1
version:3.5.8

No Retreat 3: The French and Polish Fronts v1.1.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\DELL\AppData\Roaming\VASSAL\tiles\8c00c15c6482ac24a8f4a1734073cd0821163cf3\3\35\35958c539abbb5ca14f471e651a61416a9917bbe
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
