### ISSUE TITLE
[Commands & Colors Ancients] NullPointerException: Cannot invoke "VASSAL.counters.Deck.getOrderedPieces()" because the return value of "VASSAL.build.module.map.DrawPile.getDeck()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10561]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [947832 bytes](https://vassalengine.org/files/gh/861c2a5045edb6c95757720522f1a1edaaac2fc4) |

<pre>

Commands & Colors Ancients v4.2a06 [Epic] 3.5.8

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.Deck.getOrderedPieces()" because the return value of "VASSAL.build.module.map.DrawPile.getDeck()" is null
 at VASSAL.counters.GlobalCommand.apply(GlobalCommand.java:336)
 at VASSAL.counters.CounterGlobalKeyCommand.apply(CounterGlobalKeyCommand.java:272)
 at VASSAL.counters.CounterGlobalKeyCommand.myKeyEvent(CounterGlobalKeyCommand.java:161)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:486)
</pre>

**Comment by Cattlesquat** [comment]
While processing a GKC it has somehow reached this block of code and found a non-null DrawPile (d) but then that drawpile's _Deck_ is null. That only _seems_ possible if the DrawPile was never initialized via the whole GameState.setup(true) sequence:

```
      // If we're using "specific deck", then we find that deck and iterate through it, checking fast property matches only
      else if (target.fastMatchLocation && target.targetType == GlobalCommandTarget.Target.DECK) {
        final DrawPile d = DrawPile.findDrawPile(fastDeck);
        final int useFromDeck = getSelectFromDeck();
        if ((d != null) && (useFromDeck != 0)) {
          final List<GamePiece> pieces = d.getDeck().getOrderedPieces();
```

**Comment by Cattlesquat** [comment]
Oh FFS, Global Key Command toolbar buttons will try to send GKC's when you've just opened the editor and never actually started a game yet, if you click on them.
