### ISSUE TITLE
[Battlestar Galactica FFG] StringIndexOutOfBoundsException: begin 17, end 15, length 28

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10653]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [28613 bytes](https://vassalengine.org/files/gh/becbc883113149e59e3c49ff2f36448a0e105f2c) |

<pre>trying to connect by peer to peer

Battlestar Galactica FFG v4.5 3.5.8

java.lang.StringIndexOutOfBoundsException: begin 17, end 15, length 28
 at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3751)
 at java.base/java.lang.String.substring(String.java:1907)
 at org.litesoft.p2pchat.PeerInfo.deFormat(PeerInfo.java:108)
 at VASSAL.chat.peer2peer.DirectPeerPool.invite(DirectPeerPool.java:178)
</pre>

**Comment by Cattlesquat** [comment]
This is that thing we fixed the other day #10607
