### ISSUE TITLE
[VASL] IllegalArgumentException: Invalid prefix or suffix

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10687]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [92738 bytes](https://vassalengine.org/files/gh/4241486dc25923679c954bce76eb9c838f02b641) |

<pre>adding chess clock...function worked fine...no saved.

VASL v6.6.3 3.5.8

java.lang.IllegalArgumentException: Invalid prefix or suffix
 at java.base/java.nio.file.TempFileHelper.generatePath(TempFileHelper.java:60)
 at java.base/java.nio.file.TempFileHelper.create(TempFileHelper.java:124)
 at java.base/java.nio.file.TempFileHelper.createTempFile(TempFileHelper.java:158)
 at java.base/java.nio.file.Files.createTempFile(Files.java:872)
</pre>

**Comment by Cattlesquat** [comment]
He clearly has something open in another process, and to the extent there's any invalid prefix or suffix then it's that sanitize thing I fixed recently for 3.6
