### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10690]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [5527 bytes](https://vassalengine.org/files/gh/56a35a6722e385ce5d6e126b401c8fea1cb0da8f) |

<pre>

3.5.8

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Current state = RESET, new state = FLUSHED
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:422)
</pre>

**Comment by Cattlesquat** [comment]
@uckelman Looks like there's some wacky encoding stuff going on there?

**Comment by Cattlesquat** [comment]
Whenever this happens it's in some version of "new ZipFile(file)" ctor, e.g. https://github.com/vassalengine/vassal/issues/10215

But not necessarily via this path. Do we think there's something wrong with the _filename_ or something wrong with the _zipfile_ itself?

**Comment by uckelman** [comment]
I suspect that the ZIP has a bad entry in it.
