### ISSUE TITLE
[Unnamed module] NullPointerException: Cannot read field "xpoints" because "this.polygon" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10715]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [10324 bytes](https://vassalengine.org/files/gh/53a72ef0d8085aa321c51d9be1fef56959e52d4f) |

<pre>

Unnamed module v0.0 3.5.8

java.lang.NullPointerException: Cannot read field "xpoints" because "this.polygon" is null
 at VASSAL.build.module.map.boardPicker.board.mapgrid.PolygonEditor.clonePolygon(PolygonEditor.java:99)
 at VASSAL.build.module.map.boardPicker.board.mapgrid.Zone$Editor.init(Zone.java:714)
 at VASSAL.build.module.map.boardPicker.board.mapgrid.Zone$Editor.lambda$new$0(Zone.java:623)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by uckelman** [comment]
This can't happen in the master/HEAD because nothing calls `clonePolygon()` anymore.
