### ISSUE TITLE
ExecutionException: java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10738]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [7493 bytes](https://vassalengine.org/files/gh/5e1cd560044a080cc093762e7b537b6cedff4624) |

<pre>

3.5.8

java.util.concurrent.ExecutionException: java.lang.IllegalStateException: Current state = FLUSHED, new state = CODING_END
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:422)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10690.
