### ISSUE TITLE
[WWI WoG] NullPointerException: Cannot invoke "VASSAL.build.module.turn.TurnLevel.getSetControls(javax.swing.JDialog, VASSAL.build.module.turn.TurnTracker)" because the return value of "VASSAL.build.module.turn.TurnTracker.getTurnLevel(int)" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10735]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [8650 bytes](https://vassalengine.org/files/gh/6dc366655729650e8fa4e4bdad9070a6489167fb) |

<pre>

WWI WoG v0.0 3.5.8

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.turn.TurnLevel.getSetControls(javax.swing.JDialog, VASSAL.build.module.turn.TurnTracker)" because the return value of "VASSAL.build.module.turn.TurnTracker.getTurnLevel(int)" is null
 at VASSAL.build.module.turn.TurnTracker$SetDialog.addChildControls(TurnTracker.java:1158)
 at VASSAL.build.module.turn.TurnTracker$SetDialog.setControls(TurnTracker.java:1146)
 at VASSAL.build.module.turn.TurnTracker.set(TurnTracker.java:717)
 at VASSAL.build.module.turn.TurnTracker.actionPerformed(TurnTracker.java:701)
</pre>

**Comment by Cattlesquat** [comment]
Essentially duplicates #9933
