### ISSUE TITLE
[Gloomhaven Jaws of the Lion] ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10748]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [39645 bytes](https://vassalengine.org/files/gh/c661786c3c11824127583faed1cb6f27f14d6828) |

<pre>Trying to set the enemy level in Gloomhaven JOTL

Gloomhaven Jaws of the Lion v1.0 3.5.8

java.lang.ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4
 at VASSAL.counters.Embellishment.getProperty(Embellishment.java:788)
 at VASSAL.counters.Embellishment.getLocalizedProperty(Embellishment.java:819)
 at VASSAL.counters.PropertyExporter.lambda$getProperties$0(PropertyExporter.java:42)
 at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1224)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10124. Fixed in 3.6.0-beta6.
