### ISSUE TITLE
[Battle Spirits TCG Online] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Teacher\AppData\Roaming\VASSAL\tiles\d80dfa1105d5d8200e156afa9c7ca2783000ab12\9\99\9989fcb1b227784e6aed01207c3bddcb9074a78c

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10745]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [182986 bytes](https://vassalengine.org/files/gh/3563d08b3f591c007d73c2d2c27a020232525ecf) |

<pre>

Battle Spirits TCG Online v1.0 3.5.8

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\Teacher\AppData\Roaming\VASSAL\tiles\d80dfa1105d5d8200e156afa9c7ca2783000ab12\9\99\9989fcb1b227784e6aed01207c3bddcb9074a78c
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
