### ISSUE TITLE
[Battles for the Ardennes (SPI)] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\yoshi\AppData\Roaming\VASSAL\tiles\93b61aebf1d079aa830ddb0f1df2e35e3d2619db\5\5e\5e172f13e5efa484de50243557668cd8e056c417

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10769]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [16203 bytes](https://vassalengine.org/files/gh/97f4f832258181e32a0772ff90060b4d47a79f5f) |

<pre>

Battles for the Ardennes (SPI) v1.1 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\yoshi\AppData\Roaming\VASSAL\tiles\93b61aebf1d079aa830ddb0f1df2e35e3d2619db\5\5e\5e172f13e5efa484de50243557668cd8e056c417
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
