### ISSUE TITLE
[The Greatest Day: Sword, Juno and Gold Beaches] NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutableProperty.getPropertyValue()" because "this.globalProperty" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10775]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | mataylor387@gmail.com |
| Error Log | [36497 bytes](https://vassalengine.org/files/gh/2ef7fee0eeb531cd3960c04ca4f9c22ad3b75357) |

<pre>In The Greatest Day module, I opened the "charts" and then tried clicking on "Options".  The other three tabs were fine.

The Greatest Day: Sword, Juno and Gold Beaches v1.9.4 3.5.8

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.MutableProperty.getPropertyValue()" because "this.globalProperty" is null
 at tdc.TdcScenarioOptions$BooleanOption.createConfigurer(TdcScenarioOptions.java:358)
 at tdc.TdcScenarioOptions$BasicOption.buildControls(TdcScenarioOptions.java:340)
 at tdc.TdcScenarioOptions$BasicOption.getControls(TdcScenarioOptions.java:334)
 at tdc.TdcScenarioOptions.getComponent(TdcScenarioOptions.java:187)
</pre>

**Comment by Cattlesquat** [comment]
Custom code
