### ISSUE TITLE
[Normandy '44 (GMT)] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10787]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [9912 bytes](https://vassalengine.org/files/gh/4a63e06796517758afbc5a97eb7a029b3e1fe278) |

<pre>

Normandy '44 (GMT) v0.94 3.5.8

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:289)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
</pre>

**Comment by Cattlesquat** [comment]
#5813
