### ISSUE TITLE
[WiF CE Maps and Units] ArrayIndexOutOfBoundsException: Index 150774 out of bounds for length 150774

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10797]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [4516 bytes](https://vassalengine.org/files/gh/02a5a54f8a0d3ff68df9a015d46a7c676475fde7) |

<pre>

WiF CE Maps and Units v2.72 3.5.8

java.lang.ArrayIndexOutOfBoundsException: Index 150774 out of bounds for length 150774
 at java.base/java.util.HashMap.valuesToArray(HashMap.java:975)
 at java.base/java.util.HashMap$Values.toArray(HashMap.java:1052)
 at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
 at VASSAL.build.module.GameState.getRestorePiecesCommand(GameState.java:1060)
</pre>

**Comment by Cattlesquat** [comment]
#10422
