### ISSUE TITLE
[Russian Civil War] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\rossm\AppData\Roaming\VASSAL\tiles\22b2c739daa5f87f60b5d6e8c46d965645d66f3d\7\7c\7c52a94eafea10a00940a8a7e6e05baff49b76be

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10804]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter | rossmenzies@hotmail.com |
| Error Log | [14611 bytes](https://vassalengine.org/files/gh/f19c77dcbbfc91e6bd8782be1f50c24ad8446b20) |

<pre>Loading a VSAV

Russian Civil War v1.0 3.5.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: C:\Users\rossm\AppData\Roaming\VASSAL\tiles\22b2c739daa5f87f60b5d6e8c46d965645d66f3d\7\7c\7c52a94eafea10a00940a8a7e6e05baff49b76be
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #9957.
