### ISSUE TITLE
[Lebensraum] IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10844]
| ABR | |
|-----|-----|
| Version | 3.5.8 |
| Reporter |  |
| Error Log | [9321 bytes](https://vassalengine.org/files/gh/d24970d4aa480ac64dc42044194decd6040717dd) |

<pre>

Lebensraum vK13 3.5.8

java.lang.IllegalArgumentException: NTFS ADS separator (':') in file name is forbidden.
 at org.apache.commons.io.FilenameUtils.indexOfExtension(FilenameUtils.java:745)
 at org.apache.commons.io.FilenameUtils.removeExtension(FilenameUtils.java:1119)
 at org.apache.commons.io.FilenameUtils.getBaseName(FilenameUtils.java:1031)
 at VASSAL.tools.io.ZipArchive.makeTempFileFor(ZipArchive.java:445)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10028.
