### ISSUE TITLE
[Sword of Rome] NullPointerException: Cannot invoke "String.equals(Object)" because "locationName" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10873]
| ABR | |
|-----|-----|
| Version | 3.6.0 |
| Reporter |  |
| Error Log | [9421 bytes](https://vassalengine.org/files/gh/47d80a79b83f18d53835bd370c0e0b002966a7ca) |

<pre>

Sword of Rome v5.0.6 3.6.0

java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "locationName" is null
 at VASSAL.build.module.map.CounterDetailViewer.drawText(CounterDetailViewer.java:512)
 at VASSAL.build.module.map.CounterDetailViewer.draw(CounterDetailViewer.java:303)
 at VASSAL.build.module.map.CounterDetailViewer.draw(CounterDetailViewer.java:273)
 at VASSAL.build.module.Map.drawDrawable(Map.java:2313)
</pre>

**Comment by Cattlesquat** [comment]
Either the new exception we added will produce actionable information for this situation, or it won't.
