### ISSUE TITLE
[Illusions of Glory] NullPointerException: Cannot invoke "java.awt.Polygon.contains(java.awt.Point)" because "this.myPolygon" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10874]
| ABR | |
|-----|-----|
| Version | 3.6.0 |
| Reporter |  |
| Error Log | [9901 bytes](https://vassalengine.org/files/gh/26b02d6fbc5be76651ba82a3e66a3c822862301e) |

<pre>I just opened the module for the first time in 3.6.0

Illusions of Glory v1.55 3.6.0

java.lang.NullPointerException: Cannot invoke "java.awt.Polygon.contains(java.awt.Point)" because "this.myPolygon" is null
 at VASSAL.build.module.map.boardPicker.board.mapgrid.Zone.contains(Zone.java:390)
 at VASSAL.build.module.map.boardPicker.board.ZonedGrid.findZone(ZonedGrid.java:314)
 at VASSAL.build.module.Map.findZone(Map.java:1097)
 at VASSAL.counters.BasicPiece.getPublicProperty(BasicPiece.java:323)
</pre>

**Comment by Cattlesquat** [comment]
already fixed for 3.6.1
