### ISSUE TITLE
[Commands & Colors Epic Napoleonics] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10886]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter | paulkt@gmail.com |
| Error Log | [26269 bytes](https://vassalengine.org/files/gh/c6b5ee650ca4febb9234e2a9f838573783605672) |

<pre>I was doing nothing, watching other people playing....

Commands & Colors Epic Napoleonics v3.0.0a69 3.6.1

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:442)
</pre>

**Comment by uckelman** [comment]
It looks like there are some bad images in the module?

**Comment by riverwanderer** [comment]
We are all using the same module ok fine in an 8 player online game. However, when this player reconnected at one point he started getting loads of bad data messages to do with missing image and sound files (for files that are definately in the module).  He disconnected and re-connected against and has been ok since.

**Comment by riverwanderer** [comment]
Is this particular incident a Vassal v3.6 variation of [this issue](https://github.com/vassalengine/vassal/issues/10854) that I have experienced under v3.5 and possibly earlier? The common theme being images that _**are**_ in the module but the user session doesn't recognise/find.

**Comment by BrentEaston** [comment]
There is no actual VASSAL code in any of these errorlogs. Possible Java bug?

**Comment by AsaiToshiya** [comment]
I would like to take up this issue.

**Comment by BrentEaston** [comment]
Fantastic, it would be great if you could sort this out.
