### ISSUE TITLE
[11 de Setembre. Setge 1714] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10882]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter |  |
| Error Log | [18739 bytes](https://vassalengine.org/files/gh/ed7f687f2ffd9ad8f3e75fceacb8b1aafb3d8c6d) |

<pre>

11 de Setembre. Setge 1714 v1.0 3.6.1

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813
