### ISSUE TITLE
[The Russian campaign2] NullPointerException: Cannot load from int array because "this.rawRolls" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10897]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter |  |
| Error Log | [14489 bytes](https://vassalengine.org/files/gh/99451133d00b22c5fae5e425dfdb9089c1762606) |

<pre>

The Russian campaign2 v3.3 3.6.1

java.lang.NullPointerException: Cannot load from int array because "this.rawRolls" is null
 at VASSAL.build.module.DiceButton.formatResult(DiceButton.java:362)
 at VASSAL.build.module.RandomTextButton.DR(RandomTextButton.java:149)
 at VASSAL.build.module.RandomTextButton.lambda$new$0(RandomTextButton.java:86)
 at VASSAL.tools.LaunchButton.lambda$new$0(LaunchButton.java:75)
</pre>

**Comment by uckelman** [comment]
Fixed by #10893.
