### ISSUE TITLE
[LnLP - World at War 85 - Storming the Gap] NullPointerException: Cannot load from int array because "this.rawRolls" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10892]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter | pymapper@gmail.com |
| Error Log | [5559 bytes](https://vassalengine.org/files/gh/a25944fdbb9bb01726fe71995c10f6675aa2fa6f) |

<pre>I activated a random text button element.

LnLP - World at War 85 - Storming the Gap v2.0 3.6.1

java.lang.NullPointerException: Cannot load from int array because "this.rawRolls" is null
 at VASSAL.build.module.DiceButton.formatResult(DiceButton.java:362)
 at VASSAL.build.module.RandomTextButton.DR(RandomTextButton.java:149)
 at VASSAL.build.module.RandomTextButton.lambda$new$0(RandomTextButton.java:86)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by ToxicRat** [comment]
Random Text Button worked in 3.6.0.
