### ISSUE TITLE
[Churchill - Big Three Struggle For Peace] NullPointerException: Cannot load from int array because "this.rawRolls" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10905]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter | timothy.paterson@gmail.com |
| Error Log | [22608 bytes](https://vassalengine.org/files/gh/2245dd44a83eb7c189d62de9b76de5c787651f62) |

<pre>Rolling 2d6 in the churchill module

Churchill - Big Three Struggle For Peace v1.13 3.6.1

java.lang.NullPointerException: Cannot load from int array because "this.rawRolls" is null
 at VASSAL.build.module.DiceButton.formatResult(DiceButton.java:362)
 at VASSAL.build.module.RandomTextButton.DR(RandomTextButton.java:149)
 at VASSAL.build.module.RandomTextButton.lambda$new$0(RandomTextButton.java:86)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by uckelman** [comment]
Fixed by #10893.
