### ISSUE TITLE
[WiF CE Maps and Units] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 Asia Final 2 Mar 2020 CMYK process no dieline.png:8,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10916]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter |  |
| Error Log | [18116 bytes](https://vassalengine.org/files/gh/9029cf6655c62c7afe563eac9dac8fa51b368ff2) |

<pre>cannot sea one of the maps for this module

WiF CE Maps and Units v3.00a 3.6.1

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 Asia Final 2 Mar 2020 CMYK process no dieline.png:8,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10900.
