### ISSUE TITLE
[RAF II Eagle] NullPointerException: Cannot load from int array because "this.rawRolls" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10917]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter | aspinall1910@yahoo.co.uk |
| Error Log | [35791 bytes](https://vassalengine.org/files/gh/66bc8ca76dce5844bbb4a377afdd4d13f7770bbc) |

<pre>raf 2 eAGLE 4. vASSAL 3.6.1 Clicked on the icon for weather. 

RAF II Eagle v4 3.6.1

java.lang.NullPointerException: Cannot load from int array because "this.rawRolls" is null
 at VASSAL.build.module.DiceButton.formatResult(DiceButton.java:362)
 at VASSAL.build.module.RandomTextButton.DR(RandomTextButton.java:149)
 at VASSAL.build.module.RandomTextButton.lambda$new$0(RandomTextButton.java:86)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by uckelman** [comment]
Fixed by #10893.
