### ISSUE TITLE
[Divine Right] NullPointerException: Cannot load from int array because "this.rawRolls" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10913]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter | jimmylogan0916@gmail.com |
| Error Log | [34384 bytes](https://vassalengine.org/files/gh/fa71b44189ee31574408a19b6e9b5fa4acb29bc1) |

<pre>random country - divine right module

Divine Right v4.4 3.6.1

java.lang.NullPointerException: Cannot load from int array because "this.rawRolls" is null
 at VASSAL.build.module.DiceButton.formatResult(DiceButton.java:362)
 at VASSAL.build.module.RandomTextButton.DR(RandomTextButton.java:149)
 at VASSAL.build.module.RandomTextButton.lambda$new$0(RandomTextButton.java:86)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by uckelman** [comment]
Fixed by #10893.
