### ISSUE TITLE
[World in Flames Collectors Edition] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 WEurope.jpg:0,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10910]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter |  |
| Error Log | [799343 bytes](https://vassalengine.org/files/gh/f9bdfe0cb259e5d7005e5496aeeb39068a8ac1c4) |

<pre>Just selecting the victory in the west 1940-41 setup.

World in Flames Collectors Edition v1.06.P 3.6.1

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 WEurope.jpg:0,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10900.
