### ISSUE TITLE
[A Time for Trumpets] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\aTfT-Card_TurnRecordTrack.png:9,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10923]
| ABR | |
|-----|-----|
| Version | 3.6.1 |
| Reporter |  |
| Error Log | [274856 bytes](https://vassalengine.org/files/gh/a80ad0df532f392518d6101814be5cf52a8fc01d) |

<pre>

A Time for Trumpets v2.0 3.6.1

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\aTfT-Card_TurnRecordTrack.png:9,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#10937
