### ISSUE TITLE
[War for the Union] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/TEC.png:2,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10938]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter |  |
| Error Log | [1393801 bytes](https://vassalengine.org/files/gh/9e92a1fab300b3730cdca491652147279f243529) |

<pre>

War for the Union v1.01 3.6.2

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/TEC.png:2,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by Cattlesquat** [comment]
#10937
