### ISSUE TITLE
[Commands & Colors: Napoleonics] NullPointerException: Cannot invoke "VASSAL.build.module.Map.repaint()" because "this.map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10950]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | markben61@gmail.com |
| Error Log | [48933 bytes](https://vassalengine.org/files/gh/ed59aca6cc3b710b0776a5c353f37ca00e70052e) |

<pre>click on an action button that triggers a GKC.

Commands & Colors: Napoleonics v4.0.7a04 3.6.2

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.repaint()" because "this.map" is null
 at VASSAL.counters.SendToLocation.myKeyEvent(SendToLocation.java:634)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:492)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:493)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:494)
</pre>

**Comment by uckelman** [comment]
Fixed by #10942.
