### ISSUE TITLE
[The Battle for Normandy] NullPointerException: Cannot invoke "VASSAL.build.module.Map.repaint()" because "this.map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10959]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | mike@themclaughlins.us |
| Error Log | [9104 bytes](https://vassalengine.org/files/gh/88c9f5b5e4893fa9074fb4d8cdfde886cbec1800) |

<pre>Advancing turn marker does not auto populate reinforcements from OOB's like it used to.

The Battle for Normandy v3.16 3.6.2

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.repaint()" because "this.map" is null
 at VASSAL.counters.SendToLocation.myKeyEvent(SendToLocation.java:634)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:492)
 at VASSAL.counters.GlobalCommand$Visitor.apply(GlobalCommand.java:759)
 at VASSAL.counters.GlobalCommand$Visitor.apply(GlobalCommand.java:738)
</pre>

**Comment by uckelman** [comment]
Fixed by #10942.
