### ISSUE TITLE
[Friedrich] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\friedrich.board.HighRes.LARGE.png:4,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10958]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | ichirou989@gmail.com |
| Error Log | [141894 bytes](https://vassalengine.org/files/gh/88bd062f82c9bbe937a80736ba81919f72eb3645) |

<pre>Attempting to start a game from the Friedrich module. I had just chosen the side and the pop-up asking if you want to start a new Logfile had just shown up when the crash happened. It was the very first time that I was trying out this module.

Friedrich v1.0 3.6.2

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\friedrich.board.HighRes.LARGE.png:4,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to confirm that #10961 solves the problem.
