### ISSUE TITLE
[C&E 1663] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10960]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter |  |
| Error Log | [14078 bytes](https://vassalengine.org/files/gh/0020a258eee930250b96356114ad070067bb86a7) |

<pre>

C&E 1663 vC 0.1 3.6.2

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by Cattlesquat** [comment]
#5813
