### ISSUE TITLE
[No Better Place To Die] NoSuchMethodError: 'java.util.Enumeration turn.TurnTracker.getComponents(java.lang.Class)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10978]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter |  |
| Error Log | [8637 bytes](https://vassalengine.org/files/gh/bbe8a6f72ab51d6f71139e12df9906d1d69fa3a7) |

<pre>

No Better Place To Die vTranslated to VASSAL by Gary Krockover, version 2.6 3.6.2

java.lang.NoSuchMethodError: 'java.util.Enumeration turn.TurnTracker.getComponents(java.lang.Class)'
 at turn.TurnTracker.getState(TurnTracker.java:154)
 at turn.TurnTracker.getRestoreCommand(TurnTracker.java:544)
 at VASSAL.build.module.GameState.getRestoreCommand(GameState.java:906)
 at VASSAL.build.module.GameState.saveString(GameState.java:670)
</pre>

**Comment by uckelman** [comment]
I'll bet I know what this is: Their TurnTracker class is an AbstractBuildable, and we removed `AbstractBuildable.getComponents()` in 3.6.0.
