### ISSUE TITLE
[No Better Place To Die] NoSuchMethodError: 'java.util.Enumeration turn.TurnTracker.getComponents(java.lang.Class)'

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10974]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | schmidt1885@yahoo.de |
| Error Log | [5247 bytes](https://vassalengine.org/files/gh/bba86ac8216f520d8a56e0a0307026a897450e3f) |

<pre>I wanted to close the game with X in the top right! It hangs on!

No Better Place To Die vTranslated to VASSAL by Gary Krockover, version 2.6 3.6.2

java.lang.NoSuchMethodError: 'java.util.Enumeration turn.TurnTracker.getComponents(java.lang.Class)'
 at turn.TurnTracker.getState(TurnTracker.java:154)
 at turn.TurnTracker.getRestoreCommand(TurnTracker.java:544)
 at VASSAL.build.module.GameState.getRestoreCommand(GameState.java:906)
 at VASSAL.build.module.GameState.saveString(GameState.java:670)
</pre>

**Comment by Cattlesquat** [comment]
Custom code
