### ISSUE TITLE
[Nemesis] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_90s.jpg:7,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10977]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter |  |
| Error Log | [10542 bytes](https://vassalengine.org/files/gh/cf8b3afa3d891eba97f9109d9e6eed709a54bf1b) |

<pre>

Nemesis v2.3a 3.6.2

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_90s.jpg:7,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10937.
