### ISSUE TITLE
[Nemesis] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_90s.jpg:7,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10971]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | orchq@hotmail.com |
| Error Log | [12613 bytes](https://vassalengine.org/files/gh/dc10addb03f95b5b5a56330592dd9cc01b4d5a92) |

<pre>zooming out

Nemesis v2.3a 3.6.2

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_90s.jpg:7,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user.
