### ISSUE TITLE
Vassal Exception in Editor attempting to remove an item from a folder

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#10982]
Encountered this error using interim v3.6.3 build: VASSAL-3.6.3-1afcc07-DealToSideBug

Vassal error dump:

2021-12-24 12:17:20,189 [65497-AWT-EventQueue-0] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/MacOS/jre/bin/java -classpath Contents/Resources/Java/Vengine.jar -Duser.dir=/Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app VASSAL.launch.ModuleManager --update-module /Users/Mark/Dropbox/CCNapoleonics4_1_0X.vmod
2021-12-24 12:17:25,750 [65497-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Exiting
2021-12-24 12:20:53,194 [62000-SwingWorker-pool-1-thread-6] INFO  VASSAL.launch.AbstractLaunchAction - Loading module file /Users/Mark/Dropbox/CCNapoleonics4_1_0X.vmod
2021-12-24 12:20:53,279 [62000-SwingWorker-pool-1-thread-6] INFO  VASSAL.launch.TilingHandler - No images to tile.
2021-12-24 12:20:53,280 [62000-SwingWorker-pool-1-thread-6] INFO  VASSAL.launch.AbstractLaunchAction - Loading module Commands & Colors: Napoleonics
2021-12-24 12:20:53,281 [62000-SwingWorker-pool-1-thread-6] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/MacOS/jre/bin/java -Xms512M -Xmx512M -Duser.home=/Users/Mark -Duser.dir=/Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app -cp Contents/Resources/Java/Vengine.jar -Xdock:name=Commands & Colors: Napoleonics -Xdock:icon=/Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/Resources/VASSAL.icns -Dsun.java2d.opengl=true -Dsun.java2d.opengl.fbobject=false VASSAL.launch.Player --load -- /Users/Mark/Dropbox/CCNapoleonics4_1_0X.vmod
2021-12-24 12:20:53,674 [66140-main] INFO  VASSAL.launch.StartUp - Starting
2021-12-24 12:20:53,681 [66140-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 11.5 x86_64
2021-12-24 12:20:53,681 [66140-main] INFO  VASSAL.launch.StartUp - Java version 17.0.1
2021-12-24 12:20:53,681 [66140-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/MacOS/jre
2021-12-24 12:20:53,681 [66140-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.6.3-SNAPSHOT-1afcc07-DealToSideBug
2021-12-24 12:20:53,681 [66140-main] INFO  VASSAL.launch.Launcher - Player
2021-12-24 12:20:57,453 [66140-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Commands & Colors: Napoleonics version 4.1.0
2021-12-24 12:33:32,817 [66140-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Exiting
2021-12-24 12:33:36,231 [62000-SwingWorker-pool-1-thread-7] INFO  VASSAL.launch.AbstractLaunchAction - Loading module file /Users/Mark/Dropbox/CCNapoleonics4_1_0X.vmod
2021-12-24 12:33:36,303 [62000-SwingWorker-pool-1-thread-7] INFO  VASSAL.launch.TilingHandler - No images to tile.
2021-12-24 12:33:36,304 [62000-SwingWorker-pool-1-thread-7] INFO  VASSAL.launch.AbstractLaunchAction - Loading module Commands & Colors: Napoleonics
2021-12-24 12:33:36,305 [62000-SwingWorker-pool-1-thread-7] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/MacOS/jre/bin/java -Xms512M -Xmx512M -Duser.home=/Users/Mark -Duser.dir=/Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app -cp Contents/Resources/Java/Vengine.jar -Xdock:name=Commands & Colors: Napoleonics -Xdock:icon=/Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/Resources/VASSAL.icns -Dsun.java2d.opengl=true -Dsun.java2d.opengl.fbobject=false VASSAL.launch.Editor --edit -- /Users/Mark/Dropbox/CCNapoleonics4_1_0X.vmod
2021-12-24 12:33:36,722 [66236-main] INFO  VASSAL.launch.StartUp - Starting
2021-12-24 12:33:36,729 [66236-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 11.5 x86_64
2021-12-24 12:33:36,729 [66236-main] INFO  VASSAL.launch.StartUp - Java version 17.0.1
2021-12-24 12:33:36,729 [66236-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/MacOS/jre
2021-12-24 12:33:36,729 [66236-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.6.3-SNAPSHOT-1afcc07-DealToSideBug
2021-12-24 12:33:36,729 [66236-main] INFO  VASSAL.launch.Launcher - Editor
2021-12-24 12:33:40,487 [66236-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Commands & Colors: Napoleonics version 4.1.0
2021-12-24 13:06:10,872 [66236-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog - Piece:  () Trait: Text Label - Disabled Marker - {isOff ? "X" : ""} Source: {isOff ? "X" : ""} Error: Expression evaluation error. See the errorlog for more details. 
Expression Audit:
   Source type=Piece Trait
   Source name=Piece:  ()
   Source description=Trait: Text Label - Disabled Marker - {isOff ? "X" : ""}
   Source field=Label text
   Source Expression={isOff ? "X" : ""}
   isOff=
   Error=: Condition must evaluate to a Boolean or boolean.
2021-12-24 13:23:03,181 [66236-AWT-EventQueue-0] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app/Contents/MacOS/jre/bin/java -classpath Contents/Resources/Java/Vengine.jar -Duser.dir=/Applications/VASSAL-3.6.3-1afcc07-DealToSideBug.app VASSAL.launch.ModuleManager --update-module /Users/Mark/Dropbox/CCNapoleonics4_1_0X.vmod
2021-12-24 13:32:24,494 [66236-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: Cannot invoke "javax.swing.JToolBar.remove(java.awt.Component)" because "this.toolbar" is null
	at VASSAL.build.module.ToolbarMenu.removeFrom(ToolbarMenu.java:194)
	at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1033)
	at VASSAL.configure.ConfigureTree$10.actionPerformed(ConfigureTree.java:986)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1028)
	at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1072)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by riverwanderer** [comment]
May relate specifically to attempting to delate a Multi-Action Button from the folder. Folder had been previously copied from another Player Hand window and moved up within the player hand window.
Appears to have been a transient error, as I have been able to recover by saving the module file and restarting the edit session. Thereafter I was able to delete the Multi-Action button from the folder.

**Comment by Cattlesquat** [comment]
Is it reproducible by following particular steps? Or was it just a one-off and you can't get it to happen again?

**Comment by Cattlesquat** [comment]
@riverwanderer Checking back to see if you are able to reproduce this problem?

**Comment by riverwanderer** [comment]
Sorry, I haven't seen it again yet.

**Comment by Cattlesquat** [comment]
Okay I'm going to close for now unless it comes back up, particularly since this was in a non-master-line test build.
