### ISSUE TITLE
[Adventure Quest] NullPointerException: Cannot invoke "String.length()" because "this.tooltip" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10989]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter |  |
| Error Log | [5105 bytes](https://vassalengine.org/files/gh/28be2a13c5cb9b07390147c473690b2a21421182) |

<pre>created a folder
added a symbolic dice inside
when I double click on the symbolic dice to edit it ... PUFF crash

Adventure Quest v1.0 3.6.3

java.lang.NullPointerException: Cannot invoke "String.length()" because "this.tooltip" is null
 at VASSAL.build.module.SpecialDiceButton.getAttributeValueString(SpecialDiceButton.java:484)
 at VASSAL.configure.AutoConfigurer.reset(AutoConfigurer.java:220)
 at VASSAL.build.AbstractConfigurable.getConfigurer(AbstractConfigurable.java:213)
 at VASSAL.configure.ConfigureTree.mouseReleased(ConfigureTree.java:1243)
</pre>

**Comment by uckelman** [comment]
Steps to reproduce, from the Editor:

1) Delete the tooltip text from a Symbolic Dice Button.
2) Close the dialog.
3) Reopen the dialog.

Result: NPE.

**Comment by uckelman** [comment]
Doesn't NPE in 3.5.8 (but it's also impossible to blank out the tooltip text there).
