### ISSUE TITLE
[OCS - Enemy at the Gates] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\EatG Map D.png:2,7@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#10991]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter |  |
| Error Log | [44375 bytes](https://vassalengine.org/files/gh/c582eb25a0ab68b3171de12d872e92243e9fef4e) |

<pre>

OCS - Enemy at the Gates v2.17 3.6.2

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\EatG Map D.png:2,7@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10937.
