### ISSUE TITLE
[Hexplorit] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11001]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | mrgreason61@gmail.com |
| Error Log | [186200 bytes](https://vassalengine.org/files/gh/b67bfe0522c4f1ed9cb91cb052447e0c2b232bca) |

<pre>I was trying to set a property test to disable a Global Key Command at the main level. I entered a '{' in the field and got this message.

Note: entering text into that field the characters are written on top of eachother.

Hexplorit v1.0 3.6.2

java.lang.StackOverflowError: null
 at VASSAL.build.AbstractToolbarItem.checkDisabled(AbstractToolbarItem.java:210)
 at VASSAL.build.AbstractToolbarItem.addPropertyGateListener(AbstractToolbarItem.java:175)
 at VASSAL.build.AbstractToolbarItem.checkDisabled(AbstractToolbarItem.java:210)
 at VASSAL.build.AbstractToolbarItem.addPropertyGateListener(AbstractToolbarItem.java:175)
</pre>

**Comment by Cattlesquat** [comment]
This is fixed by #10954 which is already merged to master and will release in 3.6.3
