### ISSUE TITLE
[World in Flames Collectors Edition] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 WEurope.jpg:0,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11009]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | elwood.birgden@hotmaill.com |
| Error Log | [17238 bytes](https://vassalengine.org/files/gh/13fc2141ddf024a300f5eade9dee127a00b7fe32) |

<pre>I was on the latest edition of vassal (3.6.3), and I opened a module (World in Flames). This error came up every time I opened a module.

World in Flames Collectors Edition v1.06.P 3.6.3

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\WiF8 WEurope.jpg:0,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.
