### ISSUE TITLE
[War of Conquest 1757] ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11006]
| ABR | |
|-----|-----|
| Version | 3.6.2 |
| Reporter | jeffrey.cherpeski@gmail.com |
| Error Log | [5315 bytes](https://vassalengine.org/files/gh/ba3277cf20a5944dbae3915cbc386123ba89cbe7) |

<pre>Attempting to build a new module.

War of Conquest 1757 v04 3.6.2

java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
 at VASSAL.configure.StringEnumConfigurer.getValueString(StringEnumConfigurer.java:111)
 at VASSAL.preferences.EnumPreference.getPreferenceConfigurer(EnumPreference.java:111)
 at VASSAL.preferences.BasicPreference.addTo(BasicPreference.java:149)
 at VASSAL.configure.ConfigureTree.insert(ConfigureTree.java:1080)
</pre>

**Comment by uckelman** [comment]
Steps to reproduce:

1. Create a new module.
2. Add a Drop-Down List Preference to Global Options.
3. Boom.

**Comment by uckelman** [comment]
Works in 3.5.8.

**Comment by uckelman** [comment]
Breaking change is between 3.6.0-beta2 and 3.6.0-beta3.

**Comment by uckelman** [comment]
Breaking change is 169da38fec.
