### ISSUE TITLE
[Malifaux 3e] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\side_board.jpg:1,2@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11018]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | tylerjreeves+vassal@gmail.com |
| Error Log | [8718 bytes](https://vassalengine.org/files/gh/5655bd73a5ba4b3fa9581f3ba91295bf1b7daa38) |

<pre>

Malifaux 3e v3e Malifaux Burns V3b 3.6.3

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\side_board.jpg:1,2@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.
