### ISSUE TITLE
[Imperial Struggle] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11019]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | vincentinfdu@hotmail.com |
| Error Log | [65877 bytes](https://vassalengine.org/files/gh/d8315b7d61e8bfb52cd1ebed21ce0d2692383d69) |

<pre>

Imperial Struggle v1.0 3.6.3

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813.
