### ISSUE TITLE
[Fleet Marine Force] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_Far North Large Frigid 1.2.jpg:0,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11022]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter |  |
| Error Log | [120550 bytes](https://vassalengine.org/files/gh/5343dcbe75e2de7d670b462b12d5177c7b3c69b3) |

<pre>

Fleet Marine Force vPlaytest v. 0.3.3 3.6.3

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_Far North Large Frigid 1.2.jpg:0,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10937.
