### ISSUE TITLE
[Battles for the Ardennes (SPI)] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map A.jpg:0,1@0.125

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11021]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | allendkrsn@yahoo.com |
| Error Log | [9625 bytes](https://vassalengine.org/files/gh/065d98e77bc3d814e3eaad2dcb3bb429fd29d226) |

<pre>Battles for the Ardennes module: I opened the module and tried to use the Overview window to orient myself.

The windown opened with the two map sections at the top of the map missing (blank). The two on the bottom were still visible.

Battles for the Ardennes (SPI) v1.2 3.6.3

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map A.jpg:0,1@0.125
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.
