### ISSUE TITLE
[Russo-Japanese War] NullPointerException: Cannot invoke "VASSAL.build.module.gamepieceimage.GamePieceLayout.getItem(String)" because "this.layout" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11042]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | ken@piyori.org |
| Error Log | [7822 bytes](https://vassalengine.org/files/gh/61b7f42c5549ed6c9969e6df682dee7214841b9b) |

<pre>Copying a [Game Piece Image] caused the exception.

I restarted vassal but it did not resolve the problem.

Russo-Japanese War v0.1 3.6.3

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.gamepieceimage.GamePieceLayout.getItem(String)" because "this.layout" is null
 at VASSAL.build.module.gamepieceimage.GamePieceImage.rebuildInstances(GamePieceImage.java:470)
 at VASSAL.build.module.gamepieceimage.GamePieceImage$DefnConfig.getConfigurer(GamePieceImage.java:175)
 at VASSAL.configure.AutoConfigurer.createConfigurer(AutoConfigurer.java:206)
 at VASSAL.configure.AutoConfigurer.<init>(AutoConfigurer.java:87)
</pre>

**Comment by Cattlesquat** [comment]
Emailed user for copy of module
