### ISSUE TITLE
[LnLP - World at War 85 - Storming the Gap] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/WAW85STGMap01S.jpg:0,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11047]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter |  |
| Error Log | [14681 bytes](https://vassalengine.org/files/gh/465fd59cbae1364c23329c5eec1f6c1ec026f0c8) |

<pre>

LnLP - World at War 85 - Storming the Gap v2.1 3.6.3

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/WAW85STGMap01S.jpg:0,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #10937.
