### ISSUE TITLE
[World in Flames Collectors Edition] NullPointerException: Cannot invoke "VASSAL.chat.node.SocketHandler.writeLine(String)" because "this.sender" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11043]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter |  |
| Error Log | [14739 bytes](https://vassalengine.org/files/gh/58868d4a8b2ef399ef9c545628e20cf114735a61) |

<pre>

World in Flames Collectors Edition v1.06.P 3.6.3

java.lang.NullPointerException: Cannot invoke "VASSAL.chat.node.SocketHandler.writeLine(String)" because "this.sender" is null
 at VASSAL.chat.node.NodeClient.send(NodeClient.java:226)
 at VASSAL.chat.node.NodeClient.registerNewConnection(NodeClient.java:188)
 at VASSAL.chat.node.NodeClient.setConnected(NodeClient.java:162)
 at VASSAL.chat.HybridClient.setConnected(HybridClient.java:90)
</pre>

**Comment by uckelman** [comment]
It looks like another thread is closing `sender` and resetting it to null while the client is connecting.
