### ISSUE TITLE
[Alhambra] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11048]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter |  |
| Error Log | [22777 bytes](https://vassalengine.org/files/gh/74e8173b8e694a946e260bed486535978f6c4e46) |

<pre>

Alhambra v1.1 3.6.3

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813.
