### ISSUE TITLE
[Formula Dé] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\dash-red.png:0,1@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11051]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter | mzig5@msn.com |
| Error Log | [30744 bytes](https://vassalengine.org/files/gh/b89b1219f834317e902e2ea284c16d25eb6689d2) |

<pre>I downloaded Formula De the Brazilian track. The other one Hochenheim didnt even show a track, everthing was blank. Anyway, on the other track the track graphics are there but not the graphics for the individual cars along the top of the screen. I have gotten a new computer so i needed to download Vassal again. My saved FD game is unusable because both modules 2.1 and 3.0 plus the extensions have bugs.
-Michael

Formula Dé v2.1 3.6.3

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\dash-red.png:0,1@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user.

Duplicate of #10937.
