### ISSUE TITLE
[Age of Empires III] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Age of Empires III Board.jpeg:0,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11085]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [212539 bytes](https://vassalengine.org/files/gh/2d6a7c7b1be3d2c67c5087c702392ce1038006af) |

<pre>

Age of Empires III v1.0 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Age of Empires III Board.jpeg:0,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
The tiler exited normally after tiling a small fraction of the images in the module. Er.
