### ISSUE TITLE
[Assassin's Mace & ZAPAD (Beta)] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\European_Theater_40x80.png:0,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11087]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [57874 bytes](https://vassalengine.org/files/gh/c9a9325a97d9b84972fa73224e1c45bf883bba68) |

<pre>

Assassin's Mace & ZAPAD (Beta) v2.4 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\European_Theater_40x80.png:0,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
This is new. The handler got a bad byte back from the stream.

**Comment by uckelman** [comment]
Doesn't contain a tiler run. We can't tell from this if the bad run was with 3.6.4.
