### ISSUE TITLE
[Caesar in Gaul] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11080]
| ABR | |
|-----|-----|
| Version | 3.6.3 |
| Reporter |  |
| Error Log | [10981 bytes](https://vassalengine.org/files/gh/42e98a2b645c396715f212838d27fae39235c03a) |

<pre>

Caesar in Gaul v1.0 3.6.3

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:442)
</pre>

**Comment by Cattlesquat** [comment]
Nothing appears actionable -- deep in an "Only Java Stuff" stack

**Comment by uckelman** [comment]
I'll bet this is related to all the bad/corrupt images in the module.
