### ISSUE TITLE
[Blue Cross White Ensign] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Final-Map-G.jpg:0,3@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11136]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter | yveslagimoniere@telus.net |
| Error Log | [26546 bytes](https://vassalengine.org/files/gh/798e030f9db821bc903ffeba0db481a3b8f12d9b) |

<pre>I only got as far as opening a game file.
Hope it won't happen again. 
Don't know how to recreate the event.

Blue Cross White Ensign v1.1 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Final-Map-G.jpg:0,3@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.

**Comment by uckelman** [comment]
User confirmed that clearing the tile cache fixed the problem.
