### ISSUE TITLE
[War of the Ring] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11134]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter | tmavenger@pm.me |
| Error Log | [53528 bytes](https://vassalengine.org/files/gh/8cbaf17a75881a1bd892f8447e01f56757428022) |

<pre>I was in "Select play mode" and had just entered my Nickname and password. This is my first game of War of the Ring, and I was following the setup choices. 

War of the Ring v1.4.3 3.6.4

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.

**Comment by uckelman** [comment]
User can't reproduce it.

Duplicate of #5813.
