### ISSUE TITLE
[Fire in the Sky (Phalanx Games)] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_Reduced.png:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11137]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter | sleepyj49@gmail.com |
| Error Log | [55243 bytes](https://vassalengine.org/files/gh/bab0565eaddf21362c2eaee131c58b2591e6746e) |

<pre>Opening the After Pearl Harbor scenario.  FitS version 2.02, Vassal 3.6.4
Error message was something about missing a tile file.

Fire in the Sky (Phalanx Games) v2.0.2 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map_Reduced.png:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.

**Comment by uckelman** [comment]
Emailed user for details.
