### ISSUE TITLE
[OCS - Enemy at the Gates] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\EatG Map D.png:0,7@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11132]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter | spitfirev@juno.com |
| Error Log | [60888 bytes](https://vassalengine.org/files/gh/68cad95e463a01dae9fc49f0392c0732f07ce7e2) |

<pre>

OCS - Enemy at the Gates v2.17 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\EatG Map D.png:0,7@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.
