### ISSUE TITLE
[The Third World War] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Chart-6.jpg:4,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11163]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [14381 bytes](https://vassalengine.org/files/gh/00e4419c8f4fbb7315d71d70d76133216105b3e2) |

<pre>loading a new map

The Third World War vK4 3.6.4

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Chart-6.jpg:4,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by uckelman** [comment]
Fixed by #11150.
