### ISSUE TITLE
[Starship Troopers -Lazzar Map-Dice edit  LoneStar FHB modified] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11175]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [288087 bytes](https://vassalengine.org/files/gh/a98bc065994a57290d315a4d4003a9969801d99b) |

<pre>

Starship Troopers -Lazzar Map-Dice edit  LoneStar FHB modified v1.3.3.1 3.6.4

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:442)
</pre>

**Comment by Cattlesquat** [comment]
all java stuff on stack
