### ISSUE TITLE
[World in Flames Collectors Edition] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\RAW8+Prodcirc5.jpg:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11171]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter | turboelec@yahoo.com |
| Error Log | [14039 bytes](https://vassalengine.org/files/gh/065177cfdfe90a9edb2eb6cea78878048586240f) |

<pre>I just accessed the menu. I believe if I expand the page I can see half of the background.

World in Flames Collectors Edition v1.05.P 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\RAW8+Prodcirc5.jpg:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to try current build.
