### ISSUE TITLE
[TiTE Update Kit] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\TITE_NW.png:0,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11181]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter | aud@colorado.edu |
| Error Log | [94084 bytes](https://vassalengine.org/files/gh/a1b7b079831080b9fd42baf94ba33e57f811b94f) |

<pre>Loading TiTE (Thunder in the East)  Update 5.5, which is not officially on VASSAL.  It's on Alan Emrich's ETO Hub website.  This has not happened before.

Loaded a vsav, twice, from an ongoing match, with identical results.

TiTE Update Kit v0.5.5 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\TITE_NW.png:0,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to try dev build and clear tile cache.
