### ISSUE TITLE
[Lost Ruins of Arnak] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Main Board Bird Temple 2.jpg:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11198]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [96150 bytes](https://vassalengine.org/files/gh/9ec7ff1bc33c88e916a5aad1f5321cefc312d02d) |

<pre>loading

Lost Ruins of Arnak v1.0 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Main Board Bird Temple 2.jpg:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
User ran out of disk space.
