### ISSUE TITLE
[Tanto_monta] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Español_mat.jpg:3,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11204]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [265846 bytes](https://vassalengine.org/files/gh/0fa977e9a331d0ec2abee804cd50e2f1732d004a) |

<pre>														

Tanto_monta v1.07 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Español_mat.jpg:3,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by uckelman** [comment]
Fixed by #11150.
