### ISSUE TITLE
[Nations in Arms] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\NiA Map 125dpiRGB8000.jpg:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11200]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [17155 bytes](https://vassalengine.org/files/gh/7f5c5680c22b1f36547b73101e62ee07d6ab780a) |

<pre>

Nations in Arms v1.7 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\NiA Map 125dpiRGB8000.jpg:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Fixed by #11150.
