### ISSUE TITLE
[Nations in Arms] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\NiA Map 125dpiRGB8000.jpg:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11201]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [26957 bytes](https://vassalengine.org/files/gh/1e9e281c97a500aed11654423f48dbbe7f64b4e4) |

<pre>Just updated to 3.6.4 and then started module Nations in Arms 1.7

Nations in Arms v1.7 3.6.4

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\NiA Map 125dpiRGB8000.jpg:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Fixed by #11150.
