### ISSUE TITLE
[For Whom the Bell tolls] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11202]
| ABR | |
|-----|-----|
| Version | 3.6.4 |
| Reporter |  |
| Error Log | [165358 bytes](https://vassalengine.org/files/gh/635bacd637fc97226447e2a2ed69a25133b7744b) |

<pre>

For Whom the Bell tolls v0.071 3.6.4

java.lang.StackOverflowError: null
 at VASSAL.build.module.ToolbarMenu.scheduleBuildMenu(ToolbarMenu.java:269)
 at VASSAL.build.module.ToolbarMenu.componentRemoved(ToolbarMenu.java:284)
 at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
 at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
</pre>

**Comment by Cattlesquat** [comment]
That's a bizarre cascade -- I wonder if he made a self-referencing toolbar menu? 

This module seems unrelated to the For Whom The Bell Tolls module on our site (which has a different filename and no toolbar menus), and the reporter didn't leave an email address.
