### ISSUE TITLE
[LHY Europe -  Play Test] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Sector_11.jpg:1,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11228]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | marcr545@gmail.com |
| Error Log | [14748 bytes](https://vassalengine.org/files/gh/2d4650a9ceb9e14cc23b54a59616dd2d830b54e4) |

<pre>Clear cache... tried loading a saved game for use as a pre-defined setup. Was working prior to clearing cache.

LHY Europe -  Play Test v19 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Sector_11.jpg:1,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Problem solved by clearing tile cache.
