### ISSUE TITLE
[Victory in the Pacific] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/VIP-map2.gif:0,7@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11238]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | stehen.seldom@gmail.com |
| Error Log | [11188 bytes](https://vassalengine.org/files/gh/23174c1264ae8b69cfb8fda3cb951305852aab79) |

<pre>had zoomed map twice in magnificaiton, then sent 2 units to Graveyard, then was scrolling left from
looking in lower right of screen

Victory in the Pacific v3.4.1 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/VIP-map2.gif:0,7@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to clear tile cache.
