### ISSUE TITLE
[Commands & Colors Ancients] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\cca_map_hq.jpg:1,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11241]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | billiam58@comcast.net |
| Error Log | [14323 bytes](https://vassalengine.org/files/gh/a9fedf1880e820bf1505c80490603c3a21ad8b49) |

<pre>Wanted to check out a module for C&C as I have played the game in person many times.  I got Vassal to play VASL but still getting aquainted to this system.  Scenerio tiles do not load but the pieces do.  Does it every time I try to load it.  It will not load the terrain except up in the upper right corner is a half a tile.  I have older computer 2.63 or so with Windows 7.  VASL loads fine.  Luftwaffe loads fine.  Don't know how I can help but will try. Pretty busy email wise. Upgraded to Vassal 3.6.5 and C&CVersion 4.1f1.  thx. bill

Commands & Colors Ancients v4.1f1 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\cca_map_hq.jpg:1,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to clear tile cache.

**Comment by uckelman** [comment]
Fixed in 3.6.6.
