### ISSUE TITLE
[WaR2 module] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11249]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter |  |
| Error Log | [98438 bytes](https://vassalengine.org/files/gh/2de1b19da3f8c1c260d98258534ea977307799b5) |

<pre>

WaR2 module v2.0.24 3.6.5

java.lang.StackOverflowError: null
 at VASSAL.tools.SequenceEncoder$Decoder.nextToken(SequenceEncoder.java:301)
 at VASSAL.counters.BasicPiece.mySetType(BasicPiece.java:167)
 at VASSAL.counters.BasicPiece.<init>(BasicPiece.java:154)
 at VASSAL.build.module.BasicCommandEncoder.createBasic(BasicCommandEncoder.java:249)
</pre>

**Comment by Cattlesquat** [comment]
This is either self-referencing prototypes or two prototypes that reference each other. Only question is why a recursion limiter didn't catch it.
