### ISSUE TITLE
[Android] NullPointerException: Cannot invoke "String.isEmpty()" because "segment" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11257]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter |  |
| Error Log | [6762 bytes](https://vassalengine.org/files/gh/14b078fb1454e055a2a4e98058230a6580cf53c3) |

<pre>

Android v2022-02-26 3.6.5

java.lang.NullPointerException: Cannot invoke "String.isEmpty()" because "segment" is null
 at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:224)
 at java.base/java.nio.file.Path.of(Path.java:147)
 at VASSAL.build.module.documentation.BrowserHelpFile.internalExtractContents(BrowserHelpFile.java:145)
 at VASSAL.build.module.documentation.BrowserHelpFile.extractContents(BrowserHelpFile.java:123)
</pre>

**Comment by Cattlesquat** [comment]
I tried various hypothetical ways to reproduce this, but had no luck.
