### ISSUE TITLE
[Game Of Crones] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\GOC-MainMap.jpg:6,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11250]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | igraffitdotcom@gmail.com |
| Error Log | [13045 bytes](https://vassalengine.org/files/gh/e763e3baa0661a7104e87e2857200cf5c4a200e5) |

<pre>I deleted a game board.
I added a new game board.
I closed the current running game.
I created a new game
it opened the map and it created the error.

Game Of Crones v1.0 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\GOC-MainMap.jpg:6,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to clear tile cache.

**Comment by uckelman** [comment]
User replied that the problem wasn't repeatable.
