### ISSUE TITLE
ExecutionException: java.io.IOException: return value == -1073741515

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11259]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | papathad@hotmail.com |
| Error Log | [9297 bytes](https://vassalengine.org/files/gh/caff2ee7b74bc9be3a1e5c9defca9119de43244d) |

<pre>Trying to run a java runtime environment.

3.6.5

java.util.concurrent.ExecutionException: java.io.IOException: return value == -1073741515
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:508)
</pre>

**Comment by uckelman** [comment]
Advised user to upgrade to VASL 6.6.3.1.
