### ISSUE TITLE
[Panzer 40-44 BattleAxe] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\MBACoast4i.gif:0,1@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11262]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | csutherlandewr@gmail.com |
| Error Log | [36072 bytes](https://vassalengine.org/files/gh/f4fd396632d54788d08e9f9f3f3673b5b46d88e0) |

<pre>Loading a saved vsav. First time using 3.6.5 version of vassal

Panzer 40-44 BattleAxe v1.0 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\MBACoast4i.gif:0,1@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by uckelman** [comment]
A tile from MBACoast4i.gif isn't found because apparently MBACoast4i.gif wasn't tiled: That image doesn't show up in the tiler output in the log.

**Comment by uckelman** [comment]
Fixed in 3.6.6.
