### ISSUE TITLE
[Pacific War 2] NPE in GameState.java:1443: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11299]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | donaldbyronjohnson@gmail.com |
| Error Log | [18566 bytes](https://vassalengine.org/files/gh/0f45177e1026cced946b7ce5c8b94cfb92a11d91) |

<pre>loading Pacific War mod, strategic scenario

Pacific War 2 v2.00.000 3.6.5

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getMap()" because "a" is null
 at VASSAL.build.module.GameState$12.compare(GameState.java:1443)
 at VASSAL.build.module.GameState$12.compare(GameState.java:1429)
 at java.base/java.util.TimSort.countRunAndMakeAscending(TimSort.java:360)
 at java.base/java.util.TimSort.sort(TimSort.java:234)
</pre>

**Comment by Cattlesquat** [comment]
Fixed in 3.6.12
