### ISSUE TITLE
[Battle Spirits Online Battlers] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Deck editor.png:0,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11293]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter |  |
| Error Log | [1152421 bytes](https://vassalengine.org/files/gh/79accb2621f9d7e88a496fd56b2427a8e15ee3a9) |

<pre>Nothing

Battle Spirits Online Battlers v1.0 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Deck editor.png:0,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Should be resolved in 3.6.6.
