### ISSUE TITLE
[Formula Dé] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Oschersleben.jpg:0,3@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11290]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | jdalessandro721@gmail.com |
| Error Log | [18849 bytes](https://vassalengine.org/files/gh/cd8a686e74721bae3d3daffc88ba9832e71d48c7) |

<pre>I was in the "Choose circuit" dialog of the Formula Dé module and attempted to select the Oschersleben circuit included in the "Tracks #4" extension.

Formula Dé v3.0 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Oschersleben.jpg:0,3@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user for details.

**Comment by uckelman** [comment]
Fixed in 3.6.6.
