### ISSUE TITLE
[Blue Cross White Ensign] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Final-Map-G.jpg:0,3@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11309]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | markben61@gmail.com |
| Error Log | [63673 bytes](https://vassalengine.org/files/gh/dff09d6e985f5df7bc41b7ba6601a71f341ef9c6) |

<pre>zooming out on a map.

Blue Cross White Ensign v1.1 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Final-Map-G.jpg:0,3@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by uckelman** [comment]
Fixed in 3.6.6.
