### ISSUE TITLE
[Axis Empires with SK] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\TK Map.png:1,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11305]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | belechannas@gmail.com |
| Error Log | [1426077 bytes](https://vassalengine.org/files/gh/3f13ddd78dd90803cd003bc0162d177c7a944177) |

<pre>I loaded a new .vlog file after clicking "No" to the Save prompt on the .vsav file I had open.

The .vsav file may have been open for a day or two with no activity.

Axis Empires with SK v15.0beta1 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\TK Map.png:1,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to clear tile cache.

**Comment by uckelman** [comment]
Fixed in 3.6.6.
