### ISSUE TITLE
[Silver Bayonet 25th Anniversary] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/OpSB Map.jpg:6,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11311]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter |  |
| Error Log | [32726 bytes](https://vassalengine.org/files/gh/535987616bc6b0034b055227125aba8dbcb6558d) |

<pre>

Silver Bayonet 25th Anniversary v1.32 3.6.5

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/OpSB Map.jpg:6,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by uckelman** [comment]
Fixed in 3.6.6.
