### ISSUE TITLE
[BCT Kandahar] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/map1234D.png:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11313]
| ABR | |
|-----|-----|
| Version | 3.6.5 |
| Reporter | rick_mckown@hotmail.com |
| Error Log | [60714 bytes](https://vassalengine.org/files/gh/c3d1493d4fe5e8e747a92fe73aeb2dccd261098b) |

<pre>Opening BCT Kandahar module

BCT Kandahar v1.0 3.6.5

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/map1234D.png:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Fixed in 3.6.6.
