### ISSUE TITLE
[PanzerBlitz Klein-Silber 1945 Revised] NoSuchElementException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11328]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [10749 bytes](https://vassalengine.org/files/gh/b7ab68b757d63ed67c9aaf64b6c085b916442ebc) |

<pre>editing a counter

PanzerBlitz Klein-Silber 1945 Revised v1.0 3.6.6

java.util.NoSuchElementException: null
 at VASSAL.tools.SequenceEncoder$Decoder.nextToken(SequenceEncoder.java:248)
 at VASSAL.counters.Embellishment.originalSetType(Embellishment.java:327)
 at VASSAL.counters.Embellishment.mySetType(Embellishment.java:199)
 at VASSAL.counters.MassPieceDefiner$Def.edit(MassPieceDefiner.java:172)
</pre>

**Comment by Cattlesquat** [comment]
Mass Piece Defiler
