### ISSUE TITLE
[Serpents of the Seas] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11322]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | markben61@gmail.com |
| Error Log | [71781 bytes](https://vassalengine.org/files/gh/afdf6e835da8bf9e765465b60c086abb34c3a285) |

<pre>Restarted Vassal 3.6.6 after an exception that occured when I tried a Ctrl+F (reported separately).
.
Then tried a search for "fox" with trait descriptions, expressions & fields, property names and key commands DESELECTED. This worked ok.

Next, I re-tried a search but re-selected all search options. This provoked the exception.

Serpents of the Seas v2.5a01 3.6.6

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.getProperty(Decorator.java:175)
 at VASSAL.counters.Embellishment.getProperty(Embellishment.java:808)
 at VASSAL.counters.Decorator.getProperty(Decorator.java:175)
 at VASSAL.counters.Embellishment.getProperty(Embellishment.java:808)
</pre>

**Comment by uckelman** [comment]
Fixed by #11323.
