### ISSUE TITLE
[Next War: Korea 2nd Edition] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\KoreaMap-S-2019 Kev A-150.jpg:1,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11331]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [17482 bytes](https://vassalengine.org/files/gh/20fcbb911c8bf68264e086cabd3f69481c8d154d) |

<pre>

Next War: Korea 2nd Edition v1.4 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\KoreaMap-S-2019 Kev A-150.jpg:1,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
There's no tiler run here. User needs to clear tile cache to trigger a fresh one.
