### ISSUE TITLE
[S&T 053 Punic Wars] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\S&T 53 - The Punic Wars Map.jpg:1,1@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11334]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | stephenbloom44@yahoo.ca |
| Error Log | [32404 bytes](https://vassalengine.org/files/gh/7877f668b8d43ede80cce356d64a619aaef17fb6) |

<pre>S&T 053 Punic Wars 0.9 loaded using Vassal 3.6.6
Tiles would not load for any scenario chosen.

S&T 053 Punic Wars v0.9 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\S&T 53 - The Punic Wars Map.jpg:1,1@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to clear tile cache.

**Comment by uckelman** [comment]
User confirmed that clearing the tile cache solved the problem.
