### ISSUE TITLE
[Victory in the Pacific] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Ship-Graveyard.gif:0,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11336]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [30877 bytes](https://vassalengine.org/files/gh/e170cdd1a2ce407f13a1dbc754782a276b699802) |

<pre>

Victory in the Pacific v3.4.1 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Ship-Graveyard.gif:0,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
No contact info, can't get the module. Closing.
