### ISSUE TITLE
[S&T 053 Punic Wars] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\S&T 53 - The Punic Wars Map.jpg:1,1@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11333]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | stephenbloom44@yahoo.ca |
| Error Log | [16170 bytes](https://vassalengine.org/files/gh/b2dd441804c146a4e5efb638c9bf03b44b387af9) |

<pre>opening 3rd punic war scenario in Punic Wars 0.9

S&T 053 Punic Wars v0.9 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\S&T 53 - The Punic Wars Map.jpg:1,1@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #11334.
