### ISSUE TITLE
[Lynnvander_08_BC] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/playarea3.png:14,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11359]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | josh.derksen@gmail.com |
| Error Log | [110031 bytes](https://vassalengine.org/files/gh/7c2fe6958e4ac25e10b776e751f1c9392ae412cf) |

<pre>Opened a module created with an older version of vassal (probably 3.3 or 3.4?) and went to replace the png image of the game board (main map window) with a new one. The pixel dimensions of previous are 3577?×?1837, pixel dimensions of the new that threw the error are 4013?×?1837. Both images prepared from the same .psd file in the same way, so only the dimensions have changed. Happy to provide the module and the image file that caused the issue provided they don't get publicly posted anywhere.

Lynnvander_08_BC v2.1 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/playarea3.png:14,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Emailed user to clear tile cache.

**Comment by uckelman** [comment]
User confirmed solution.
