### ISSUE TITLE
[TSWW] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map 13.BK.png:0,0@0.03125

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11364]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [1065275 bytes](https://vassalengine.org/files/gh/672b4e7d3a6815e8c2c775c58c3505387a64ef91) |

<pre>

TSWW v1.63b 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map 13.BK.png:0,0@0.03125
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
User ran out of memory.
