### ISSUE TITLE
[Flying Colors] GameRefresher NPE, expression eval returned a null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11375]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | markben61@gmail.com |
| Error Log | [1766370 bytes](https://vassalengine.org/files/gh/92bd270829b92d7e9ec9e1c63ad6fd26395de0fe) |

<pre>Modified some deck locations then did a refresh counters on the open scenario.		

Flying Colors v2.6.1a01-Br=A 3.6.6

java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "VASSAL.script.ExpressionInterpreter.get(String)" is null
 at VASSAL.script.ExpressionInterpreter.evaluate(ExpressionInterpreter.java:323)
 at VASSAL.script.expression.BeanShellExpression.evaluate(BeanShellExpression.java:65)
 at VASSAL.script.expression.Expression.evaluate(Expression.java:83)
 at VASSAL.configure.PropertyExpression.isTrue(PropertyExpression.java:120)
</pre>

**Comment by Cattlesquat** [comment]
This is all 3.6.6 stuff and haven't seen since, so let's cross our fingers.
