### ISSUE TITLE
[Flying Colors] NullPointerException: Cannot invoke "Object.toString()" because the return value of "VASSAL.script.ExpressionInterpreter.get(String)" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11376]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | markben61@gmail.com |
| Error Log | [1981133 bytes](https://vassalengine.org/files/gh/1a4ec4aab9916fbf87b6022f560a6829f7c60a83) |

<pre>drag and drop a card onto a deck. Possibly it didn't like the drag and drop filter expression.

Flying Colors v2.6.1a01-Br=A 3.6.6

java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "VASSAL.script.ExpressionInterpreter.get(String)" is null
 at VASSAL.script.ExpressionInterpreter.evaluate(ExpressionInterpreter.java:323)
 at VASSAL.script.expression.BeanShellExpression.evaluate(BeanShellExpression.java:65)
 at VASSAL.script.expression.Expression.evaluate(Expression.java:83)
 at VASSAL.configure.PropertyExpression.isTrue(PropertyExpression.java:120)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of: return value of "VASSAL.script.ExpressionInterpreter.get(String)" is null #11375
