### ISSUE TITLE
[Flying Colors] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11370]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | markben61@gmail.com |
| Error Log | [464465 bytes](https://vassalengine.org/files/gh/c6d4d415d538d9e769c088705eb520b30f6cce61) |

<pre>searching

Flying Colors v2.6.1a01-SIDES 3.6.6

java.lang.StackOverflowError: null
 at VASSAL.counters.Embellishment.getProperty(Embellishment.java:808)
 at VASSAL.counters.Decorator.getProperty(Decorator.java:175)
 at VASSAL.counters.Embellishment.getProperty(Embellishment.java:808)
 at VASSAL.counters.Decorator.getProperty(Decorator.java:175)
</pre>

**Comment by riverwanderer** [comment]
recurrence of #11367.
