### ISSUE TITLE
[[AH]Napoleon at  Bay] IllegalStateException: Component must have a valid peer

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11389]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [104014 bytes](https://vassalengine.org/files/gh/bc5132f8c773f79cfd968b1f3bd775b47138f44b) |

<pre>

[AH]Napoleon at  Bay v0.20 3.6.6

java.lang.IllegalStateException: Component must have a valid peer
 at java.desktop/java.awt.Component$FlipBufferStrategy.flipSubRegion(Component.java:4190)
 at java.desktop/java.awt.Component$FlipBufferStrategy.showSubRegion(Component.java:4314)
 at java.desktop/java.awt.Component$FlipSubRegionBufferStrategy.showIfNotLost(Component.java:4611)
 at java.desktop/javax.swing.BufferStrategyPaintManager.show(BufferStrategyPaintManager.java:208)
</pre>

**Comment by Cattlesquat** [comment]
Exotic Swing stuff
