### ISSUE TITLE
[La Bataille de la Moscowa 0.6] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map AC.jpg:3,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11395]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | sumaly1965@gmail.com |
| Error Log | [18304 bytes](https://vassalengine.org/files/gh/83da772b32776f498f581264ad8c01edf082b50e) |

<pre>

La Bataille de la Moscowa 0.6 v0.6 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Map AC.jpg:3,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
User needs to clear tile cache
