### ISSUE TITLE
[Sekigahara] NullPointerException: Cannot invoke "VASSAL.build.module.map.boardPicker.board.mapgrid.GridContainer.removeGrid(VASSAL.build.module.map.boardPicker.board.MapGrid)" because "this.container" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11394]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | markben61@gmail.com |
| Error Log | [132001 bytes](https://vassalengine.org/files/gh/7b8ecb8c002cfa330565f4b722359ce5f53f6938) |

<pre>removed a region.

Sekigahara v1.5 3.6.6

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.boardPicker.board.mapgrid.GridContainer.removeGrid(VASSAL.build.module.map.boardPicker.board.MapGrid)" because "this.container" is null
 at VASSAL.build.module.map.boardPicker.board.RegionGrid.removeFrom(RegionGrid.java:221)
 at VASSAL.configure.ConfigureTree.remove(ConfigureTree.java:1066)
 at VASSAL.configure.ConfigureTree.nodeUpdated(ConfigureTree.java:1339)
 at VASSAL.configure.EditPropertiesAction$1.windowClosed(EditPropertiesAction.java:77)
</pre>

**Comment by BrentEaston** [comment]
Emailed user for more info

**Comment by BrentEaston** [comment]
Spoken with user. No longer reproducible. Closing issue.
