### ISSUE TITLE
[PanzerBlitz Red Wave (MASTER Arrigo v2)] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11401]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [72155 bytes](https://vassalengine.org/files/gh/7b432674d614e7748fd93b1cb5a91b7214cd2633) |

<pre>

PanzerBlitz Red Wave (MASTER Arrigo v2) v1.0 3.6.6

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
</pre>

**Comment by Cattlesquat** [comment]
Duplicate of #11306
