### ISSUE TITLE
[PanzerBlitz Red Wave (MASTER Arrigo v2)] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11402]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [66656 bytes](https://vassalengine.org/files/gh/f9508ddee79ed91a49e07d5edea41a364a21c568) |

<pre>

PanzerBlitz Red Wave (MASTER Arrigo v2) v1.0 3.6.6

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
 at VASSAL.counters.Decorator.setPosition(Decorator.java:309)
</pre>

**Comment by Cattlesquat** [comment]
Duplicate of #11306
