### ISSUE TITLE
[Battle Spirits Online Battlers] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Gate Open! Future Field.png:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11418]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [14832 bytes](https://vassalengine.org/files/gh/996288a4c0b15c8b7356b7dc8a59cbae401d4426) |

<pre>

Battle Spirits Online Battlers v1.0 3.6.6

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Gate Open! Future Field.png:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#10937
