### ISSUE TITLE
[Titan Strike!] NullPointerException: Cannot invoke "VASSAL.build.module.map.boardPicker.Board.getSize()" because "this.board" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11430]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter | ares_ubris@yahoo.com |
| Error Log | [12879 bytes](https://vassalengine.org/files/gh/64bd005da031e4a58d0cd9b2d1118596433005ad) |

<pre>Hello Brent, I get this error while editing the grid after having added terrain.TerrainHexGrid custom Java Class. 
Hope this will help.

Titan Strike! v1.0 3.6.6

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.boardPicker.Board.getSize()" because "this.board" is null
 at VASSAL.build.module.map.boardPicker.board.GridEditor$GridPanel.setBoard(GridEditor.java:463)
 at VASSAL.build.module.map.boardPicker.board.GridEditor$GridPanel.<init>(GridEditor.java:458)
 at terrain.TerrainHexGridEditor$TerrainGridPanel.<init>(TerrainHexGridEditor.java:999)
 at terrain.TerrainHexGridEditor.initComponents(TerrainHexGridEditor.java:483)
</pre>

**Comment by Cattlesquat** [comment]
Custom Code

@BrentEaston tagging you since you're named by the bug reporter
