### ISSUE TITLE
[Twilight Struggle] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11441]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [11293 bytes](https://vassalengine.org/files/gh/917c2e13baad3cbf55ecea179865e9360cfeb3b4) |

<pre>

Twilight Struggle v3.04a 3.6.6

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #5813
