### ISSUE TITLE
[Vermin Wars] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\board.png:8,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11474]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [18348 bytes](https://vassalengine.org/files/gh/d19ecabb724a028c5a5530bffa50c226c6ea7571) |

<pre>

Vermin Wars v0.1 3.6.6

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\board.png:8,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of https://github.com/vassalengine/vassal/issues/11395/ Need to clear cache (per https://github.com/vassalengine/vassal/issues/11532) ?
