### ISSUE TITLE
[Axis Empires] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11480]
| ABR | |
|-----|-----|
| Version | 3.6.6 |
| Reporter |  |
| Error Log | [25064 bytes](https://vassalengine.org/files/gh/332ff001c30b58a99c75767aa5a2c31f6f643d17) |

<pre>

Axis Empires v10.65 3.6.6

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:442)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of #10886.
