### ISSUE TITLE
IndexOutOfBoundsException trying to open a private note

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11520]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | davidmelkin@comcast.net |
| Error Log | [6022 bytes](https://vassalengine.org/files/gh/4ffe46fcfa358816bab6b81bfdc2340346b1d7cd) |

<pre>trying to open a note that was private, and now I wanted to reveal

Undaunted - Normandy v1.0 3.6.7

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
 at java.base/java.util.Objects.checkIndex(Objects.java:359)
</pre>

**Comment by AsaiToshiya** [comment]
I would like to take up this issue.

**Comment by AsaiToshiya** [comment]
This problem occurs when clicking a header column if the notes is empty.

![キャプチャ](https://user-images.githubusercontent.com/18229040/215229408-2140c350-3ba0-46ea-b442-22442f6852b9.PNG)
