### ISSUE TITLE
[Crucible of Nations] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11589]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | games@harperzoo.com |
| Error Log | [14420 bytes](https://vassalengine.org/files/gh/97600295747477e0f79f52560d3e2be891c88dcc) |

<pre>I searched for the string "upgrades".

Crucible of Nations v0.1 3.6.7

java.lang.NullPointerException: null
 at java.base/java.util.Objects.requireNonNull(Objects.java:208)
 at java.base/java.util.ImmutableCollections$List12.<init>(ImmutableCollections.java:564)
 at java.base/java.util.List.of(List.java:829)
 at VASSAL.build.module.turn.TurnTracker.getMenuTextList(TurnTracker.java:1299)
</pre>

**Comment by Cattlesquat** [comment]
Already fixed by some earlier PR
