### ISSUE TITLE
[Commands & Colors: Napoleonics] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11591]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | markben61@gmail.com |
| Error Log | [216285 bytes](https://vassalengine.org/files/gh/8adfaa9c28daa738fcfc731249c3087ae9e4e88a) |

<pre>editting toolbar menu and action buttons

Commands & Colors: Napoleonics v4.1.1a03 3.6.7

java.lang.StackOverflowError: null
 at java.base/java.security.AccessController.getContext(AccessController.java:1003)
 at java.desktop/java.awt.AWTEvent.<init>(AWTEvent.java:120)
 at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:291)
 at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:177)
</pre>

**Comment by Cattlesquat** [comment]
Somehow an AWTEventMulticaster component contained itself

java.lang.StackOverflowError: null
	at java.base/java.security.AccessController.getContext(AccessController.java:1003)
	at java.desktop/java.awt.AWTEvent.<init>(AWTEvent.java:120)
	at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:291)
	at java.desktop/java.awt.event.InvocationEvent.<init>(InvocationEvent.java:177)
	at java.desktop/java.awt.EventQueue.invokeLater(EventQueue.java:1317)
	at java.desktop/javax.swing.SwingUtilities.invokeLater(SwingUtilities.java:1421)
	at VASSAL.build.module.ToolbarMenu.scheduleBuildMenu(ToolbarMenu.java:273)
	at VASSAL.build.module.ToolbarMenu.componentRemoved(ToolbarMenu.java:284)
	at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
	at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
	at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
	at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
	at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
	at java.desktop/java.awt.AWTEventMulticaster.componentRemoved(AWTEventMulticaster.java:217)
