### ISSUE TITLE
[Guns of August] IllegalArgumentException: image == null!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11595]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | gcshopper67@gmail.com |
| Error Log | [7540 bytes](https://vassalengine.org/files/gh/9b0971a7bb593cf50481fd1a9f10475fc156ed81) |

<pre>I was trying to duplicate a piece so that I can change it to 2-4-3 infantry unit

Guns of August v1.1 3.6.7

java.lang.IllegalArgumentException: image == null!
 at java.desktop/javax.imageio.ImageTypeSpecifier.createFromRenderedImage(ImageTypeSpecifier.java:917)
 at java.desktop/javax.imageio.ImageIO.getWriter(ImageIO.java:1610)
 at java.desktop/javax.imageio.ImageIO.write(ImageIO.java:1596)
 at VASSAL.build.module.gamepieceimage.GamePieceImage.getEncodedImage(GamePieceImage.java:389)
</pre>

**Comment by uckelman** [comment]
Probably `visImage` is null.
