### ISSUE TITLE
[Commands & Colors Ancients] IndexOutOfBoundsException: Index: 3, Length: 1

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11607]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | markben61@gmail.com |
| Error Log | [47664 bytes](https://vassalengine.org/files/gh/fc872ae44d81d6b67be0f56b19c046ae84e72f54) |

<pre>copy and paste between fields in an Action Button

Commands & Colors Ancients v4.2.0a68 3.6.7

java.lang.IndexOutOfBoundsException: Index: 3, Length: 1
 at org.apache.commons.lang3.ArrayUtils.insert(ArrayUtils.java:3092)
 at VASSAL.configure.NamedKeyStrokeArrayConfigurer.addEntry(NamedKeyStrokeArrayConfigurer.java:240)
 at VASSAL.configure.ConfigurableListController.lambda$new$2(ConfigurableListController.java:51)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #11455
