### ISSUE TITLE
[Pax Renaissance 2nd Edition] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11601]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [91678 bytes](https://vassalengine.org/files/gh/ba6703d3bea8feb7150383d0ec1d74682b321978) |

<pre>entering password

Pax Renaissance 2nd Edition v1.2 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of NullPointerException: No owning WizardImplementation for id _#UndeterminedStep #11561
