### ISSUE TITLE
[Normandy '44 (GMT)] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11623]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | sergiomolina242@gmail.com |
| Error Log | [14441 bytes](https://vassalengine.org/files/gh/53fea98c1566973fc4b2e7a2ae2f62a7f0e76d8e) |

<pre>

Normandy '44 (GMT) v0.94 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of NullPointerException: No owning WizardImplementation for id _#UndeterminedStep #11561
