### ISSUE TITLE
[Crown Of Amber] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\main board.jpg:20,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11626]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [55040 bytes](https://vassalengine.org/files/gh/b53fff9a0f3b9828c08407726dfdff57f1d976d9) |

<pre>

Crown Of Amber v0.2 3.6.7

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\main board.jpg:20,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of https://github.com/vassalengine/vassal/issues/11395/ Need to clear cache (per https://github.com/vassalengine/vassal/issues/11532) ?
