### ISSUE TITLE
[Nevsky] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11640]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [17115 bytes](https://vassalengine.org/files/gh/b2ef218e790728c80053809be5c2c358ee742507) |

<pre>

Nevsky v2.1 3.6.7

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:440)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of #10886.
