### ISSUE TITLE
[Star Wars X-Wing Miniatures Game] NullPointerException: Cannot invoke "VASSAL.build.module.Map.placeOrMerge(VASSAL.counters.GamePiece, java.awt.Point)" because the return value of "mic.BombSpawner.getMap()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11649]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [692676 bytes](https://vassalengine.org/files/gh/1585cda3e1f1033b7aa381576a0486142c42f490) |

<pre>

Star Wars X-Wing Miniatures Game v9.4.0 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.placeOrMerge(VASSAL.counters.GamePiece, java.awt.Point)" because the return value of "mic.BombSpawner.getMap()" is null
 at mic.BombSpawner.spawnBomb(BombSpawner.java:257)
 at mic.BombSpawner.keyEvent(BombSpawner.java:320)
 at VASSAL.counters.KeyCommand.actionPerformed(KeyCommand.java:147)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by BrentEaston** [comment]
Custom code issue
