### ISSUE TITLE
[Star Wars X-Wing Miniatures Game] NullPointerException: Cannot invoke "Object.toString()" because the return value of "VASSAL.counters.GamePiece.getProperty(Object)" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11650]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [704171 bytes](https://vassalengine.org/files/gh/d40ad7df95033bd8015d43d6511cb0804fc59dc0) |

<pre>

Star Wars X-Wing Miniatures Game v9.4.0 3.6.7

java.lang.NullPointerException: Cannot invoke "Object.toString()" because the return value of "VASSAL.counters.GamePiece.getProperty(Object)" is null
 at mic.AutoRangeFinder.keyEvent(AutoRangeFinder.java:162)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:494)
 at VASSAL.counters.Decorator.keyEvent(Decorator.java:494)
 at VASSAL.counters.TriggerAction.keyEvent(TriggerAction.java:165)
</pre>

**Comment by BrentEaston** [comment]
Custom code issue
