### ISSUE TITLE
[The Devils Cauldron v6] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11668]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [62312 bytes](https://vassalengine.org/files/gh/db673bdee42d4783e1a23069cbe321ac5fdee0d0) |

<pre>

The Devils Cauldron v6 v6.5 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of NullPointerException: No owning WizardImplementation for id _#UndeterminedStep #11561
