### ISSUE TITLE
[Iron Storm] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11681]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | yvesjp.roig@gmail.com |
| Error Log | [49818 bytes](https://vassalengine.org/files/gh/89dc9a47b6ff3dc9b16538411e1947f6a2551087) |

<pre>Bonjour, je selectionnais un mode de jeu (recherche en ligne)

Iron Storm v1.39b 3.6.7

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by riverwanderer** [comment]
Recurrence of NullPointerException: No owning WizardImplementation for id _#UndeterminedStep #11561
