### ISSUE TITLE
[Empires of the Apocalypse] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Force Pool_Germany.png:3,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11695]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [14413 bytes](https://vassalengine.org/files/gh/e224838311660b7e1265ddf04444e0f36dbc355f) |

<pre>

Empires of the Apocalypse v0.9g-big 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Force Pool_Germany.png:3,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by riverwanderer** [comment]
TileNotFound - recurrence of #11395.
