### ISSUE TITLE
[Combat Commander: Europe] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getMoveToFormat()" because "toMap" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11703]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | danielshuffman@gmail.com |
| Error Log | [22315 bytes](https://vassalengine.org/files/gh/243c81c55bdee2f0c9eb2c942986504e2265a755) |

<pre>I moved a suppression marker from the American to the German because the German wouldn't let me put a suppression marker on it. :-)

25b Field of Fire and Field of Blood

Combat Commander: Europe v2.4 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getMoveToFormat()" because "toMap" is null
 at VASSAL.build.module.map.MovementReporter.getReportCommand(MovementReporter.java:190)
 at VASSAL.build.module.map.PieceMover.movePieces(PieceMover.java:1164)
 at VASSAL.build.module.map.PieceMover.performDrop(PieceMover.java:1331)
 at VASSAL.build.module.map.PieceMover.mouseReleased(PieceMover.java:1298)
</pre>

**Comment by BrentEaston** [comment]
Unable to reproduce and hard to see how it can happen. Need a reproducible case. This is the only case I can see of this.
