### ISSUE TITLE
[Three Days of Gettysburg] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11709]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | imikem2@gmail.com |
| Error Log | [110673 bytes](https://vassalengine.org/files/gh/aa89c034a5ab0be8a1066ff5a8b4209182244964) |

<pre>Saving an updated pre-defined scenario setup.

Three Days of Gettysburg v1.41 3.6.7

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:440)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #11751
