### ISSUE TITLE
[Berlín 1945] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Mano alemana.jpg:3,1@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11725]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [8744 bytes](https://vassalengine.org/files/gh/697bfb076e61327e9ece8fd94dd4efd8924b2036) |

<pre>

Berlín 1945 v1.2 3.6.7

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Mano alemana.jpg:3,1@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by BrentEaston** [comment]
User needs to clear tile cache
