### ISSUE TITLE
[Paydirt] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11722]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [9240 bytes](https://vassalengine.org/files/gh/7e08087238af3a3d0c47b7e2b233637afb44e8d3) |

<pre>building and repositioning a deck stack

Paydirt v.01 3.6.7

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3420)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3406)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:440)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #11751
