### ISSUE TITLE
[The Devils Cauldron v6] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\map-veghel.jpg:6,2@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11737]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [1234816 bytes](https://vassalengine.org/files/gh/45e989cab1c4b2b5e4b0e282cba7388d368db06b) |

<pre>

The Devils Cauldron v6 v6.5.1 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\map-veghel.jpg:6,2@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
User needs to clear tile cache
