### ISSUE TITLE
[La Bataille de Ligny] IllegalStateException: Cannot insert a stack into another stack

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11730]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [40961 bytes](https://vassalengine.org/files/gh/c11914c5d67f38bfa2dd7c34ee8ab0413d96e671) |

<pre>

La Bataille de Ligny v1.23 3.6.7

java.lang.IllegalStateException: Cannot insert a stack into another stack
 at VASSAL.counters.Stack.insertChild(Stack.java:299)
 at VASSAL.counters.Stack.setState(Stack.java:639)
 at VASSAL.command.AddPiece.executeCommand(AddPiece.java:55)
 at VASSAL.command.Command.execute(Command.java:61)
</pre>

**Comment by Cattlesquat** [comment]
Loading a saved game, but apparently from the correct version of the module.
