### ISSUE TITLE
[War in the Pacific (SPI, 1977)] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Air Surface Tactical Display-page-001.jpg:0,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11745]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [111602 bytes](https://vassalengine.org/files/gh/62d9f627e84df5db6735ef9bc1b61a8bcdb49185) |

<pre>

War in the Pacific (SPI, 1977) v1.38 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Air Surface Tactical Display-page-001.jpg:0,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:311)
</pre>

**Comment by BrentEaston** [comment]
User needs to clear tile cache
