### ISSUE TITLE
[Invasion: Norway] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Strategic Map Vassal  5.jpg:8,4@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11746]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [30341 bytes](https://vassalengine.org/files/gh/badcf53bd0a1e62d021896d223d7846ca995518b) |

<pre>

Invasion: Norway v1.2 3.6.7

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Strategic Map Vassal  5.jpg:8,4@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
User needs to clear tile cache
