### ISSUE TITLE
NegativeArraySizeException when negative number of Dice reqeuested to roll

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11759]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter |  |
| Error Log | [13247 bytes](https://vassalengine.org/files/gh/18d5ecb003f1039a794a1e06227b192e2f7526f7) |

<pre>I was rolling 3 d6 with a modifier of -3

Blade & Bow v1.1 3.6.7

java.lang.NegativeArraySizeException: -2
 at VASSAL.build.module.DiceButton.DR(DiceButton.java:241)
 at VASSAL.build.module.DiceButton.lambda$initLaunchButton$0(DiceButton.java:204)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
</pre>

**Comment by BrentEaston** [comment]
This is actually caused by trying to roll a negative number of dice.
