### ISSUE TITLE
[Amagami] NumberFormatException: For input string: ""

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11764]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | tanamachikaoru007s@gmail.com |
| Error Log | [9715 bytes](https://vassalengine.org/files/gh/989a4523002841b9fc12d0e02bcf076ce439f514) |

<pre>In EDIT ALL CONTAINED PIECES, The order of Traits cannot be edit.

Amagami v1.0 3.6.7

java.lang.NumberFormatException: For input string: ""
 at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
 at java.base/java.lang.Integer.parseInt(Integer.java:678)
 at java.base/java.lang.Integer.parseInt(Integer.java:784)
 at VASSAL.counters.FreeRotator.mySetType(FreeRotator.java:264)
</pre>

**Comment by Cattlesquat** [comment]
Mass Piece Defiler
