### ISSUE TITLE
Mat Refresher (NPE)

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11785]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | martin.ekre@gmail.com |
| Error Log | [492499 bytes](https://vassalengine.org/files/gh/7c3322986e00430a196d4ca5b0a21c140346427a) |

<pre>Refreshing counters after updating game from older to newer version of same module

WiF CE Maps and Units v3.27 3.6.7

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.Mat.makeAddCargoCommand(VASSAL.counters.GamePiece)" because the return value of "VASSAL.counters.Decorator.getDecorator(VASSAL.counters.GamePiece, java.lang.Class)" is null
 at VASSAL.build.module.GameRefresher$MatRefresher.refresh(GameRefresher.java:817)
 at VASSAL.build.module.GameRefresher.execute(GameRefresher.java:334)
 at VASSAL.build.module.GameRefresher$RefreshDialog.run(GameRefresher.java:706)
 at VASSAL.build.module.GameRefresher$RefreshDialog.lambda$initComponents$0(GameRefresher.java:580)
</pre>

**Comment by Cattlesquat** [comment]
Somehow a Mat Refresher has something assigned as its "mat piece" that doesn't contain a Mat.class?

**Comment by Cattlesquat** [comment]
**This save was created with Module version '3.17' but you are running '3.27'**
