### ISSUE TITLE
[WiF CE Maps and Units] ArrayIndexOutOfBoundsException: Index 10959 out of bounds for length 10959

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11794]
| ABR | |
|-----|-----|
| Version | 3.6.7 |
| Reporter | thomtoups@gmail.com |
| Error Log | [82826 bytes](https://vassalengine.org/files/gh/ac92ddacef672292f031f8da3a8ead2cdaef552f) |

<pre>i was exiting the game.

WiF CE Maps and Units v3.27 3.6.7

java.lang.ArrayIndexOutOfBoundsException: Index 10959 out of bounds for length 10959
 at java.base/java.util.HashMap.valuesToArray(HashMap.java:973)
 at java.base/java.util.HashMap$Values.toArray(HashMap.java:1050)
 at java.base/java.util.ArrayList.<init>(ArrayList.java:181)
 at VASSAL.build.module.GameState.getRestorePiecesCommand(GameState.java:1441)
</pre>

**Comment by Cattlesquat** [comment]
Oh, it was "heap spaced"
