### ISSUE TITLE
[Pacific War 2] NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11813]
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter |  |
| Error Log | [22321 bytes](https://vassalengine.org/files/gh/e57cb7b7810d80a6b9b43c94a3c74abdc02a8b98) |

<pre>

Pacific War 2 v2.00.025 3.6.8

java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null
 at VASSAL.counters.Decorator.getOutermost(Decorator.java:525)
 at VASSAL.build.widget.PieceSlot.getLocalizedConfigureName(PieceSlot.java:609)
 at VASSAL.build.Widget$MyCellRenderer.getListCellRendererComponent(Widget.java:183)
 at java.desktop/javax.swing.plaf.basic.BasicListUI.updateLayoutState(BasicListUI.java:1444)
</pre>

**Comment by BrentEaston** [comment]
I suspect this is a race condition bought on by the changes to PieceSlot.getLocalizedConfigureName().
