### ISSUE TITLE
[Banderin run] ExecutionException: java.lang.NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11820]
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter |  |
| Error Log | [17724 bytes](https://vassalengine.org/files/gh/f495382cd17c35c7ca8ff809d693a1c05d24d6c7) |

<pre>

Banderin run v0.0 3.6.8

java.util.concurrent.ExecutionException: java.lang.NullPointerException
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Here's the "real" part of the stack trace
```	at VASSAL.build.module.map.boardPicker.board.GridOp.draw(GridOp.java:104)
	at VASSAL.build.module.map.boardPicker.board.GridOp$TileOp.eval(GridOp.java:187)
	at VASSAL.build.module.map.boardPicker.board.GridOp$TileOp.eval(GridOp.java:138)
	at VASSAL.tools.opcache.OpCache$Request.doInBackground(OpCache.java:203)```
