### ISSUE TITLE
[Banderin run] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/mapa.png:1,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11822]
| ABR | |
|-----|-----|
| Version | 3.6.8 |
| Reporter | santiagodevoto2003@gmail.com |
| Error Log | [14591 bytes](https://vassalengine.org/files/gh/a5cfcef0f68701b73703aa7ab253bb1e103f61ce) |

<pre>

Banderin run v0.0 3.6.8

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/mapa.png:1,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
Emailed user to clear Tile cache
