### ISSUE TITLE
[The Hunters] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11832]
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [17311 bytes](https://vassalengine.org/files/gh/4dc4374148a7538526c43cacdccf322017af4d4d) |

<pre>

The Hunters v2.1 3.6.9

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
 at java.base/java.util.Objects.checkIndex(Objects.java:385)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #11520
