### ISSUE TITLE
[Twilight Struggle 3.1] Twilight Struggle Custom Code issues

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11874]
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [14732 bytes](https://vassalengine.org/files/gh/7181c09ca1389baf85ce920d7dc51e676c66e149) |

<pre>

Twilight Struggle 3.1 v3.1.2 3.6.9

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: 'void ca.mkiefte.TSPlayerRoster.addSideChangeListener(VASSAL.build.module.PlayerRoster$SideChangeListener)'
</pre>

**Comment by BrentEaston** [comment]
This is an issue with custom code in the Twilight Struggle module. Leaving this open as a placeholder for Twlight Struggle custom code issues. See the alternate module repository for more information about Twilight Struggle issues

**Comment by BrentEaston** [comment]
A new version of the module 3.2 (compatible with Vassal 3.6+) has been released which resolves this issue/
