### ISSUE TITLE
[TLNB: Napoleon Against Russia] IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11876]
| ABR | |
|-----|-----|
| Version | 3.6.9 |
| Reporter |  |
| Error Log | [14677 bytes](https://vassalengine.org/files/gh/f551b1a0843cc8e6fb3f6cef0ea962b3a7315ce7) |

<pre>

TLNB: Napoleon Against Russia vv1.60_NLC 3.6.9

java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
 at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
 at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
 at java.base/java.util.Objects.checkIndex(Objects.java:385)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #11520
