### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11897]
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [20333 bytes](https://vassalengine.org/files/gh/47a824ba615c9c00328a2260b1b0a7880316cd95) |

<pre>

3.6.10

java.lang.NullPointerException: null
 at VASSAL.launch.ModuleManagerWindow$ModuleInfo$1.actionPerformed(ModuleManagerWindow.java:1389)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
 at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
</pre>

**Comment by BrentEaston** [comment]
Adding an Extension, but the selectedModule can no longer be found in the Module Manager??? Can't reproduce this. Perhaps just add null protection and fail quietly. Investigate when someone complains they can't add an extension?
