### ISSUE TITLE
NullPointerException: Cannot invoke "java.io.File.getCanonicalFile()" because "f" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11915]
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [13759 bytes](https://vassalengine.org/files/gh/862f44201e93966f76fc2df92ca983633c85abb8) |

<pre>

3.6.10

java.lang.NullPointerException: Cannot invoke "java.io.File.getCanonicalFile()" because "f" is null
 at VASSAL.launch.ModuleManagerWindow$MyTreeNode.findNode(ModuleManagerWindow.java:1122)
 at VASSAL.launch.ModuleManagerWindow$ModuleInfo$1.actionPerformed(ModuleManagerWindow.java:1388)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
 at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
</pre>

**Comment by Cattlesquat** [comment]
Probably deleted the module from OS and then did something in module manager
