### ISSUE TITLE
[Battle Spirits [Online Battlers]] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\BSOB Classic.png:5,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11934]
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [21996 bytes](https://vassalengine.org/files/gh/3b42fdd77c89cec79da7ee56e8054292eec62b43) |

<pre>

Battle Spirits [Online Battlers] v1.0 3.6.10

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\BSOB Classic.png:5,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#10937
