### ISSUE TITLE
[Commands & Colors Ancients] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11949]
| ABR | |
|-----|-----|
| Version | 3.6.10 |
| Reporter |  |
| Error Log | [62837 bytes](https://vassalengine.org/files/gh/26fa63404540316f13a8601bc796d29655afd099) |

<pre>

Commands & Colors Ancients v4.2.6 3.6.10

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3419)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3405)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:446)
</pre>

**Comment by AsaiToshiya** [comment]
Duplicate #10886.
