### ISSUE TITLE
[Dragon Pass] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Sartar_Map.png:0,5@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11953]
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | djberg96@gmail.com |
| Error Log | [14213 bytes](https://vassalengine.org/files/gh/f65fe86eb57f5840482a4500c3f6a61241f74f1d) |

<pre>Trying to reload a map image. I resized the map, but used the same file name.

Dragon Pass v0.3 3.6.11

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Sartar_Map.png:0,5@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#10937
