### ISSUE TITLE
[War of Marcus Aurelius] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Main Map.jpg:1,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11961]
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter |  |
| Error Log | [15719 bytes](https://vassalengine.org/files/gh/c1e37dbd048ca064e24220d9d8203b8c13491307) |

<pre>

War of Marcus Aurelius v1.0 3.6.11

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Main Map.jpg:1,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
#10937
