### ISSUE TITLE
ExecutionException: java.io.IOException: return value == -1073741502

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#11990]
| ABR | |
|-----|-----|
| Version | 3.6.11 |
| Reporter | puciek2@gazeta.pl |
| Error Log | [22214 bytes](https://vassalengine.org/files/gh/7e59283de5f94546bd376a32e3a9d3977edfba0e) |

<pre>When opening module NeuroshimaHex.vmod

3.6.11

java.util.concurrent.ExecutionException: java.io.IOException: return value == -1073741502
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.launch.AbstractLaunchAction$LaunchTask.done(AbstractLaunchAction.java:512)
</pre>

**Comment by Cattlesquat** [comment]
Duplicate #11413
