### ISSUE TITLE
[Panzer] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\BaseMap.jpg:4,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12036]
| ABR | |
|-----|-----|
| Version | 3.6.12 |
| Reporter | grennabrenna@gmail.com |
| Error Log | [233496 bytes](https://vassalengine.org/files/gh/7a2739cd7626d8f670afd1df314bf565867d7c53) |

<pre>I attempted to begin a new game.

Panzer v1.6.8 3.6.12

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\BaseMap.jpg:4,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Ran out of disk space
