### ISSUE TITLE
[OCS - Reluctant Enemies] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12033]
| ABR | |
|-----|-----|
| Version | 3.6.12 |
| Reporter | john.mcdougall@gmx.com |
| Error Log | [51940 bytes](https://vassalengine.org/files/gh/f2ff7a3e76e05eaa419d12d8ecf46c312178e22e) |

<pre>I was playing through my oppenents log watching a unit move.  I thought it had exceeded MA and undid movement to look at it again.  Starting through again this error came up.

OCS - Reluctant Enemies v1.13 (EF) 3.6.12

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2522)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:272)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:246)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by Cattlesquat** [comment]
map.findPiece() at the location returns piece p,

but then map.positionOf(p) discovers p's "map" field is a different map (or I guess it could be null)

**Comment by Cattlesquat** [comment]
emailed user since this is fresh we might get a log of it (of course game could already be corrupt before log, but worth checking)

**Comment by BrentEaston** [comment]
@Cattlesquat Starting to get a few of these. I can't see why this is happening. Pretty easily fixed by adding 

`      if (!map.equals(p.getMap())) { // Piece is not actually on this map, do nothing
        return;
      }`

in the MenuDisplayer. Wondering if it is time to just go ahead and do that? I've just spent 30 minutes trying to duplicate this.

**Comment by riverwanderer** [comment]
In my experience - in case it's not already clear from the other reports - this problem is associated with UnDo when replaying a log. After the UnDo a Piece on a map suddenly will report CurrentMap as null. I provided a short example of this in my report #13730.

**Comment by riverwanderer** [comment]
> if (!map.equals(p.getMap())) { // Piece is not actually on this map, do nothing return; }

@BrentEaston I'm pretty sure that this isn't a fix for the issue. At any rate, in my experience the piece IS on the map (it's visible and can be moved), but CurrentMap says its not. Hypothesis: Somewhere in the UnDo processing, Vassal has lost track.

**Comment by BrentEaston** [comment]
@riverwanderer Without a log file that spans the undo that causes the problem, it is an extremely difficult issue to debug.

**Comment by riverwanderer** [comment]
> [@riverwanderer](https://github.com/riverwanderer) Without a log file that spans the undo that causes the problem, it is an extremely difficult issue to debug.

Not helped by the log  that I made not being able to reproduce the issue as I thought it would. Also, the OldMap (also OldZone, OldLocationName) issue might be a separate thing. That iaauw is readily observable in a logfile - the Old settings are reset to null when a logfile is opened and not updated as the logfile replays. I will raise a separate issue for this, because despite my theory Current settings start out correct in the log file.

**Comment by riverwanderer** [comment]
Therefore, I will submit a PR for the change you proposed @BrentEaston. I'd be happy to run it consolidated with other 3.6.16 changes in test games over a week or two.

**Comment by BrentEaston** [comment]
@riverwanderer I'm wondering if that is such a good fix? 

Perhaps at that point, we know we have a piece that is supposed to be on a Map, but isn't. And we know which Map that is because we have just called map.findPiece(). Perhaps we should fix the piece and force it on to the map? If we don't then people are going to start complaining about pieces that right-click doesn't do anything on.

**Comment by riverwanderer** [comment]
@BrentEaston, I did wonder about that. I guess it's a question of how corrupted the piece data is and the extent to which it can be repaired. Do we use the appropriate PieceMover or PlaceMarker methods using the information from map.findPiece(), assuming that is still valid at this point ? Or is there a more straightforward fix?

**Comment by BrentEaston** [comment]
Could possibly just add this:

`// Undo sometimes corrupts a pieces Map.
    if (!map.equals(p.getMap())) {
      p.setMap(map);
    }`

**Comment by riverwanderer** [comment]
There a two subsequent references to the piece (p); hopefully that data is not affected by the bug. PR to follow.
