### ISSUE TITLE
[Omaha Beachhead VG] RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError: Bad location

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12045]
| ABR | |
|-----|-----|
| Version | 3.6.13 |
| Reporter | rlenar@sbcglobal.net |
| Error Log | [3980 bytes](https://vassalengine.org/files/gh/723112e7f7c3ef825c9d17f784fcd12c3957557a) |

<pre>Trying to import Adc2 module.  Error can be reproduced by restarting import.

Omaha Beachhead VG v0.0 3.6.13

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError: Bad location
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Editor.<init>(Editor.java:61)
 at VASSAL.launch.Editor.main(Editor.java:54)
Caused by: java.util.concurrent.ExecutionException: java.lang.AssertionError: Bad location
</pre>

**Comment by Cattlesquat** [comment]
#9375
