### ISSUE TITLE
[Star Wars Armada] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12075]
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter |  |
| Error Log | [114261 bytes](https://vassalengine.org/files/gh/82443fa5f6d825f47ff7a580d16d1adc3b646e5f) |

<pre>

Star Wars Armada v4.8.0 (3.6.9) 3.6.14

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by Cattlesquat** [comment]
#5813
