### ISSUE TITLE
[Pendragon] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Card Display.jpg:0,5@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12082]
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter | mrkptrs1@yahoo.com |
| Error Log | [20894 bytes](https://vassalengine.org/files/gh/c8e15f65fe60c703c70c2602e735e4dfa48a07e5) |

<pre>opening on-line game of PENDRAGON

Pendragon v1.2 3.6.14

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images/Card Display.jpg:0,5@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #12081.
