### ISSUE TITLE
[Empire of the Sun (2nd Edition)] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12086]
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter | eduardo.lopez.izquierdo@gmail.com |
| Error Log | [8155 bytes](https://vassalengine.org/files/gh/0195b173205c590c3371a94de7e0932c00febdaf) |

<pre>I tried to begin a log after playing a log to its last step.

Empire of the Sun (2nd Edition) v5.10.2.1 3.6.14

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
 at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
 at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
 at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
</pre>

**Comment by uckelman** [comment]
Fixed by PR #12152.
