### ISSUE TITLE
[Empire of the Sun (2nd Edition)] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12089]
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter | eduardo.lopez.izquierdo@gmail.com |
| Error Log | [12810 bytes](https://vassalengine.org/files/gh/3c3e1c2356269c7961ee0a575c73c37a4bc1deb8) |

<pre>Open the wizard for loading a log or a save.

I have already desinstaled all version of VASSAL and current version of java. Trying with different modules and logs previoulsy working, everyone triggers an error when a panel for selecting a save, saving or begining a log. I think it a problem with last version of java (8v361).

Empire of the Sun (2nd Edition) v5.10.2.1 3.6.14

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
 at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
 at java.base/java.util.ComparableTimSort.mergeForceCollapse(ComparableTimSort.java:426)
 at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:222)
</pre>

**Comment by uckelman** [comment]
Fixed by PR #12152.
