### ISSUE TITLE
[DRN Omaha] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\DRN-Omaha.jpg:11,0@0.5

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12145]
| ABR | |
|-----|-----|
| Version | 3.6.14 |
| Reporter | 404marsh@gmail.com |
| Error Log | [16530 bytes](https://vassalengine.org/files/gh/a5bd244b88c10f34da9355d88680ae36ad77c07f) |

<pre>loading the module 

DRN Omaha v.011 3.6.14

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\DRN-Omaha.jpg:11,0@0.5
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Fixed by #12231
