### ISSUE TITLE
[Commands & Colors: Napoleonics] IllegalBuildException: failed to load class napoleonics.ChooseScenarioItem

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12166]
| ABR | |
|-----|-----|
| Version | 3.7.0-beta2 |
| Reporter | markben61@gmail.com |
| Error Log | [34598 bytes](https://vassalengine.org/files/gh/c5f0bc0cdd87264d2b6b96af3ee2321dd0a2a684) |

<pre>tried importing xml; the xml had been exported from a previous version of the module (saved under v3.6.15) and comprising a single line of a custom code  component.

Commands & Colors: Napoleonics v4.2.1a01R 3.7.0-beta2

VASSAL.build.IllegalBuildException: failed to load class napoleonics.ChooseScenarioItem
 at VASSAL.build.Builder.create(Builder.java:145)
 at VASSAL.configure.ConfigureTree.importTreeBranch(ConfigureTree.java:570)
 at VASSAL.configure.ConfigureTree$3.actionPerformed(ConfigureTree.java:677)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by riverwanderer** [comment]
Custom code had not been added into the module.
