### ISSUE TITLE
[WS - Fall Blau] ExecutionException: java.awt.image.RasterFormatException: negative or zero height

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12185]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter | peter.dietrich@waldmes.de |
| Error Log | [29770 bytes](https://vassalengine.org/files/gh/cb5748632fc83251eec79dc33d54f461faf5bc77) |

<pre>Opening the module - loading the Game -  minimizing view - error.

WS - Fall Blau v007.6 3.6.15

java.util.concurrent.ExecutionException: java.awt.image.RasterFormatException: negative or zero height
 at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:323)
 at VASSAL.tools.opcache.OpCache.get(OpCache.java:261)
 at VASSAL.tools.opcache.AbstractOpImpl.get(AbstractOpImpl.java:80)
 at VASSAL.tools.imageop.AbstractOpImpl.getImage(AbstractOpImpl.java:101)
</pre>

**Comment by uckelman** [comment]
Emailed user to test build.
