### ISSUE TITLE
[Vassal 40k] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Asphalt.png:1,2@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12194]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter |  |
| Error Log | [222244 bytes](https://vassalengine.org/files/gh/d5811636c0a03104aad23623757f2f2fa96d659c) |

<pre>Loading up a map

Vassal 40k v9.2 3.6.15

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Asphalt.png:1,2@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.build.module.map.boardPicker.Board.drawTile(Board.java:321)
</pre>

**Comment by uckelman** [comment]
Duplicate of #12081.
