### ISSUE TITLE
[Vassal 40k] ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\KT_Board_Urban-V.png:1,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12193]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter |  |
| Error Log | [163859 bytes](https://vassalengine.org/files/gh/365b15a1556300c62e272aecfd04e302431cc5fc) |

<pre>All I did was click open the map.

Vassal 40k v9.2 3.6.15

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\KT_Board_Urban-V.png:1,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #12081.
