### ISSUE TITLE
Refresh Counters trashed module (Vassal dev build: VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS)

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12229]
Crash on a Refresh Counters after a simple edit of a Prototype (added a KeyCommand to the execution list of 3 or 4 Triggers, in a dev version of C&C Nap module currently testing @Cattlesquat's new Attachment functionality (no obvious link other than that the Refresh Counters had to be updated for Attachments).

Immediately exited and saved  the module, which had been trashed; only saving buildfile and moduledata:
[CCN BAD.zip](https://github.com/vassalengine/vassal/files/11248020/CCN.BAD.zip)

Build in use: VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS. Dump below.

```
2023-04-17 08:54:55,322 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - ----------
2023-04-17 08:55:08,802 [35874-AWT-EventQueue-0] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS.app/Contents/MacOS/jre/bin/java -classpath Contents/Resources/Java/Vengine.jar -Duser.dir=/Applications/VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS.app VASSAL.launch.ModuleManager --update-module /Users/Mark/Downloads/CCNapoleonics4_2_0N.vmod
2023-04-17 08:55:22,439 [29412-ProcessLauncher-2] WARN  VASSAL.tools.logging.LoggedOutputStream - 2023-04-17 08:55:22.439 java[35874:1610448] +[CATransaction synchronize] called within transaction
2023-04-17 08:55:42,218 [35874-AWT-EventQueue-0] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS.app/Contents/MacOS/jre/bin/java -classpath Contents/Resources/Java/Vengine.jar -Duser.dir=/Applications/VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS.app VASSAL.launch.ModuleManager --update-module /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0N.vmod
2023-04-17 09:16:05,777 [35874-AWT-EventQueue-0] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS.app/Contents/MacOS/jre/bin/java -classpath Contents/Resources/Java/Vengine.jar -Duser.dir=/Applications/VASSAL-3.7.0-SNAPSHOT-8b7b306-AttachTHIS.app VASSAL.launch.ModuleManager --update-module /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0N.vmod
2023-04-17 09:16:16,385 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: highlight3.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:16,451 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - Collecting Counters
2023-04-17 09:16:16,451 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - 247 Counters found in game
2023-04-17 09:16:16,451 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - - 247 Counters collected
2023-04-17 09:16:16,451 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - - 0 Counters not collected - Not owned
2023-04-17 09:16:16,451 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - - 0 Counters not collected - Not visible
2023-04-17 09:16:16,451 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - -
2023-04-17 09:16:17,445 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - Refreshing Counters with Module version 4.2.1a01N
2023-04-17 09:16:17,445 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - - 247 Counters refreshed
2023-04-17 09:16:17,445 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - - 0 Counters could not be refreshed - Not found
2023-04-17 09:16:17,445 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - - 0 Counters could not be refreshed - Not on a map
2023-04-17 09:16:17,445 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - ----------
2023-04-17 09:16:17,445 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - - 0 Refreshed counters had no parent stack
2023-04-17 09:16:17,445 [35874-AWT-EventQueue-0] INFO  VASSAL.build.module.GameRefresher - ----------
2023-04-17 09:16:17,524 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: CardMask3b.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,524 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_LeaderUnitReform(3).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,524 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_LoopHoleBuildings(1).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,525 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_InfantryMeleeLeader(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,525 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_HastySquare(1).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,525 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: card outline-grey.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,526 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_BattlefieldSmoke(1).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,526 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_ForceMarch(4).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,526 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: card outline-greyCmd.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,527 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_ProbeRight(5).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,527 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_FlankAttack(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,528 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_ScoutRight(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,528 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_CounterAttack(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,530 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_LeaderOrdersFallBack(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,530 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_ArtilleryCombat(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,530 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_LeaderBonusOrders(3).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,531 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_ChargeIfCharged(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,531 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_TakeCommandAny(3).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,532 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_AttackCenter(6).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,532 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_ProbeCenter(6).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,533 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_AttackRight(5).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,559 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Tile_River.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,559 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Tile_Hill.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,560 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Tile_Forest.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,560 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Tile_RiverBend.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,561 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_6.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,562 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,562 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Tile_Town.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,563 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_7.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,563 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_2.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,564 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_7.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,564 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,565 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_6.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,565 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_10.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,566 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_9.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,566 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_5.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,567 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_5.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,567 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_10.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,568 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_4.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,568 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_8.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,569 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_3.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,569 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_9.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,570 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_2.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,570 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_3.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,570 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_4.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,571 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_8.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,571 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: N_french.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,572 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: N_british.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,572 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: FR_Victory_1.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,573 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: AL_Victory_1.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,573 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: highlight15.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,573 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Napoleon by David B&W size60.jpg Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,574 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: side_blue_L mute.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,579 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Wellington by Goya size60.jpg Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,580 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: side_red_R.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,585 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: side_blue_R mute.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,585 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: fre_LN.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,585 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: str2.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,586 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: unit_LI.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,586 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: port_LC.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,587 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: str3.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,587 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: unit_LC.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,587 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: port_LDR.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,588 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: brit_LN.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,588 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: str4.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,589 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: brit_LDR.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,591 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: fre_LDR.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,594 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: fre_LC.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,595 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: port_LN.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,596 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: brit_HA.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,596 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: unit_HA.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,598 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: brit_HC.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,599 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: unit_HC.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,599 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: brit_LT.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,599 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: str5.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,600 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: unit_LT.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,600 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: fre_LT.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,602 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: fre_FA.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,602 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: unit_FA.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,603 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: port_LT.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,605 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: brit_FA.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,606 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marker_battled25x25v2.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,609 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marker_rally25x25.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,609 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marker_attacker_CCN25x25.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,609 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marker_target25x25.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,610 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: icn_unit_block_lost 50x50.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,616 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_back.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,618 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: marsh_CoordinatedAdvance(2).png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,618 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: tactic_back.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,620 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: guerrillasmall.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,621 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: IronWillsmall.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,667 [35874-AWT-EventQueue-0] WARN  VASSAL.tools.ErrorDialog -  Source: Icon_FlipCard.png Error: Image not found. See the errorlog for more details. 
2023-04-17 09:16:17,669 [35874-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
	at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
	at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3419)
	at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3405)
	at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:446)
	at java.desktop/com.apple.laf.AquaButtonUI.paintIcon(AquaButtonUI.java:439)
	at java.desktop/com.apple.laf.AquaButtonUI.paint(AquaButtonUI.java:320)
	at java.desktop/javax.swing.plaf.ComponentUI.update(ComponentUI.java:161)
	at java.desktop/javax.swing.JComponent.paintComponent(JComponent.java:852)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1128)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:961)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1137)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5318)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBufferedImpl(RepaintManager.java:1656)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(RepaintManager.java:1631)
	at java.desktop/javax.swing.RepaintManager$PaintManager.paint(RepaintManager.java:1569)
	at java.desktop/javax.swing.RepaintManager.paint(RepaintManager.java:1336)
	at java.desktop/javax.swing.JComponent._paintImmediately(JComponent.java:5266)
	at java.desktop/javax.swing.JComponent.paintImmediately(JComponent.java:5076)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:878)
	at java.desktop/javax.swing.RepaintManager$4.run(RepaintManager.java:861)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:861)
	at java.desktop/javax.swing.RepaintManager.paintDirtyRegions(RepaintManager.java:834)
	at java.desktop/javax.swing.RepaintManager.prePaintDirtyRegions(RepaintManager.java:784)
	at java.desktop/javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1897)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by Cattlesquat** [comment]
Looking at the errorlog it seems like it's "just" a freak occurrence of one of our occasional mystery bugs -- you can see that it hits some point where it suddenly fails to load a bunch of images ("image not found" errors) even though I'm sure those images are probably all in your module. And then it crashes (with no Vassal code on the stack) deep inside of java awt where it apparently has "null" as the image it is trying to draw. 

We've always suspected that maybe Java ran out of memory/resources or something in that case, but that is only speculation.

If you can ever get this to happen reproducibly (e.g. from a specific module & save starting state, and/or by repeating the same set of steps) then we'd definitely want to take a look.

**Comment by Cattlesquat** [comment]
Now if somehow there were pieces "being currently displayed on the screen", and somehow running the Game Refresher were to update them to want to display png files *that don't exist in the current module* then THAT would likely cause the problem. I'm not quite sure I can wrap my mind around how one would manage to do that though.
