### ISSUE TITLE
[Next War: Poland 2nd Edition] NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12225]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter |  |
| Error Log | [33354 bytes](https://vassalengine.org/files/gh/f16d211c461061dfac8765472c816e2d83fa7c2e) |

<pre>

Next War: Poland 2nd Edition v2.0 3.6.15

java.lang.NullPointerException: Cannot invoke "java.awt.Image.getWidth(java.awt.image.ImageObserver)" because the return value of "java.awt.image.AbstractMultiResolutionImage.getBaseImage()" is null
 at java.desktop/java.awt.image.AbstractMultiResolutionImage.getWidth(AbstractMultiResolutionImage.java:84)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3419)
 at java.desktop/sun.java2d.SunGraphics2D.drawImage(SunGraphics2D.java:3405)
 at java.desktop/javax.swing.ImageIcon.paintIcon(ImageIcon.java:446)
</pre>

**Comment by uckelman** [comment]
Duplicate of #12083.
