### ISSUE TITLE
[Vietnam 1965-1975 GMT] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Population-Control.jpg:0,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12226]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter |  |
| Error Log | [49443 bytes](https://vassalengine.org/files/gh/bf3679d447d82e86cdc8fa6c6fb24d0791ef1966) |

<pre>

Vietnam 1965-1975 GMT vv.2.23 3.6.15

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\Population-Control.jpg:0,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #12081.
