### ISSUE TITLE
[Panzer Grenadier - Über] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\PG4TEC4K.png:0,0@0.25

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12227]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter |  |
| Error Log | [15854 bytes](https://vassalengine.org/files/gh/6a798448cb944ba977cae6a57f83c96bd4e8fb7f) |

<pre>

Panzer Grenadier - Über v4.1 3.6.15

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\PG4TEC4K.png:0,0@0.25
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Duplicate of #12081.
