### ISSUE TITLE
[American Tank Ace] IllegalArgumentException: Comparison method violates its general contract!

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12224]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter | lucacip@tiscali.it |
| Error Log | [7639 bytes](https://vassalengine.org/files/gh/25f0cc889847a51e1400faa5496b8f9c74a18cb7) |

<pre>i was saving a game of american tank ace

American Tank Ace v1.2 3.6.15

java.lang.IllegalArgumentException: Comparison method violates its general contract!
 at java.base/java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:870)
 at java.base/java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:487)
 at java.base/java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:413)
 at java.base/java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
</pre>

**Comment by uckelman** [comment]
Emailed user to try 3.7.0-beta2.
