### ISSUE TITLE
[VASL] ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getTransparency()" because "src" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12230]
| ABR | |
|-----|-----|
| Version | 3.6.15 |
| Reporter |  |
| Error Log | [298678 bytes](https://vassalengine.org/files/gh/fb37184011598c80c326c2fbba245b2e7cfefea7) |

<pre>

VASL v6.6.6 3.6.15

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getTransparency()" because "src" is null
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by Cattlesquat** [comment]
Heap Space
