### ISSUE TITLE
[Circus Maximus] ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\CircusMax_NewTrack_4.jpg:13,0@1.0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12277]
| ABR | |
|-----|-----|
| Version | 3.6.17 |
| Reporter |  |
| Error Log | [120962 bytes](https://vassalengine.org/files/gh/a3f1b7b823980bdc5175356862bfd8c69e65b81c) |

<pre>

Circus Maximus v2.3 3.6.17

java.util.concurrent.ExecutionException: VASSAL.tools.image.tilecache.TileNotFoundException: images\CircusMax_NewTrack_4.jpg:13,0@1.0
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #10937
