### ISSUE TITLE
Exception after editing a mouse-over field

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12298]
Build: Vassal 3.7.0-SNAPSHOT-e24f5bf-fastRangeV2

Exception occurs when mousing-over 2 pieces in a stack, after changing a mouse-over in the editor, to set "Show only top piece in stack" whilst clearing "Include non-stacking pieces "; thus:
<img width="787" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/a1a0a673-4df0-4507-b8b2-8a7e8f650113">

After restarting the module, the module triggered the exception once more (see below) but did not reproduce after clearing and the re-setting "Show only top piece in stack" despite further restarts of the module.

```
2023-05-11 12:06:37,121 [36567-main] INFO  VASSAL.launch.StartUp - Starting
2023-05-11 12:06:37,134 [36567-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 13.3.1 x86_64
2023-05-11 12:06:37,135 [36567-main] INFO  VASSAL.launch.StartUp - Java version 20
2023-05-11 12:06:37,135 [36567-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL.app/Contents/MacOS/jre
2023-05-11 12:06:37,135 [36567-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.0-SNAPSHOT-e24f5bf-fastRangeV2
2023-05-11 12:06:37,135 [36567-main] INFO  VASSAL.launch.Launcher - Editor
2023-05-11 12:06:42,992 [36567-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Commands & Colors: Napoleonics version 4.2.0a07
2023-05-11 12:08:01,268 [36567-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: Cannot invoke "VASSAL.counters.GamePiece.getProperty(Object)" because "p" is null
	at VASSAL.build.module.map.LayeredPieceCollection$Collection.visitDefault(LayeredPieceCollection.java:274)
	at VASSAL.counters.PieceVisitorDispatcher.accept(PieceVisitorDispatcher.java:46)
	at VASSAL.counters.DeckVisitorDispatcher.accept(DeckVisitorDispatcher.java:37)
	at VASSAL.build.module.map.LayeredPieceCollection$Collection.getLayerForPiece(LayeredPieceCollection.java:230)
	at VASSAL.build.module.map.CounterDetailViewer$Visitor.apply(CounterDetailViewer.java:1180)
	at VASSAL.build.module.map.CounterDetailViewer$Visitor.visitStack(CounterDetailViewer.java:1145)
	at VASSAL.counters.PieceVisitorDispatcher.accept(PieceVisitorDispatcher.java:43)
	at VASSAL.counters.DeckVisitorDispatcher.accept(DeckVisitorDispatcher.java:37)
	at VASSAL.build.module.map.CounterDetailViewer.getDisplayablePieces(CounterDetailViewer.java:967)
	at VASSAL.build.module.map.CounterDetailViewer.showDetails(CounterDetailViewer.java:915)
	at VASSAL.build.module.map.CounterDetailViewer.lambda$new$0(CounterDetailViewer.java:267)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by BrentEaston** [comment]
Fixed by #12315
