### ISSUE TITLE
Module entries sometimes disappear from Vassal Library

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12344]
This issue relates to a possible cause of the problems discussed on [this forum thread](https://forum.vassalengine.org/t/modules-disappear-from-module-library-after-upgrade/76292/16).

After installing a new Vassal dev build, VASSAL-3.7.0-SNAPSHOT-d80228d-issue_12070_inaccurate, having previously been using dev build VASSAL-3.7.0-SNAPSHOT-1e6a427-fastRangeV2PlusFunctions, I noticed that some module entries had disappeared. 

1. This was not happening across restarts of Vassal using the earlier build. 
2. When I restored that previous version of V_Globals, the earlier build opened up without dropping modules.
3. Closing that buld and opening the new build a second time; the modules were dropped again.

The original V_Global and appearance of the library:
[V_Global Orig.txt](https://github.com/vassalengine/vassal/files/11642634/V_Global.Orig.txt)
<img width="936" alt="Pasted Graphic 3" src="https://github.com/vassalengine/vassal/assets/58135975/6849dcdc-4633-4b52-baa8-52a79122f03b">

The "zapped" V_Global and associated library:
[V_Global zapped.txt](https://github.com/vassalengine/vassal/files/11642636/V_Global.zapped.txt)
<img width="923" alt="Pasted Graphic 2" src="https://github.com/vassalengine/vassal/assets/58135975/a8f26065-5cf6-4e08-9ab7-bfc93eafd77c">

The Vassal log from the startup using new build indicates that Vassal was housekeeping the library by removing entries for modules that it was unable to find. In fact all three are in place, which would explain why the other version didn't remove them:

```
2023-06-03 13:21:11,512 [17178-main] INFO  VASSAL.launch.StartUp - Starting
2023-06-03 13:21:11,572 [17178-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 12.6.6 x86_64
2023-06-03 13:21:11,572 [17178-main] INFO  VASSAL.launch.StartUp - Java version 20.0.1
2023-06-03 13:21:11,572 [17178-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL 2.app/Contents/MacOS/jre
2023-06-03 13:21:11,572 [17178-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.0-SNAPSHOT-d80228d-issue_12070_inaccurate
2023-06-03 13:21:12,099 [17178-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManager - Manager
2023-06-03 13:21:13,028 [17178-AWT-EventQueue-0] ERROR VASSAL.build.module.metadata.MetaDataFactory - 
java.io.FileNotFoundException: /Users/Mark/Downloads/CCNapoleonics4_2_0.vmod (Operation not permitted)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1332)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1298)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at VASSAL.build.module.metadata.MetaDataFactory.buildMetaData(MetaDataFactory.java:60)
	at VASSAL.launch.ModuleManagerWindow$ModuleInfo.loadMetaData(ModuleManagerWindow.java:1426)
	at VASSAL.launch.ModuleManagerWindow$ModuleInfo.<init>(ModuleManagerWindow.java:1460)
	at VASSAL.launch.ModuleManagerWindow.lambda$buildTree$3(ModuleManagerWindow.java:569)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.DistinctOps$1$1.accept(DistinctOps.java:151)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at VASSAL.launch.ModuleManagerWindow.buildTree(ModuleManagerWindow.java:568)
	at VASSAL.launch.ModuleManagerWindow.<init>(ModuleManagerWindow.java:368)
	at VASSAL.launch.ModuleManagerWindow.<clinit>(ModuleManagerWindow.java:187)
	at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-06-03 13:21:13,071 [17178-AWT-EventQueue-0] ERROR VASSAL.build.module.metadata.MetaDataFactory - 
java.io.FileNotFoundException: /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/C&C Ancients/CCAncientsV4-3-5.vmod (Operation not permitted)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1332)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1298)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at VASSAL.build.module.metadata.MetaDataFactory.buildMetaData(MetaDataFactory.java:60)
	at VASSAL.launch.ModuleManagerWindow$ModuleInfo.loadMetaData(ModuleManagerWindow.java:1426)
	at VASSAL.launch.ModuleManagerWindow$ModuleInfo.<init>(ModuleManagerWindow.java:1460)
	at VASSAL.launch.ModuleManagerWindow.lambda$buildTree$3(ModuleManagerWindow.java:569)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.DistinctOps$1$1.accept(DistinctOps.java:151)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at VASSAL.launch.ModuleManagerWindow.buildTree(ModuleManagerWindow.java:568)
	at VASSAL.launch.ModuleManagerWindow.<init>(ModuleManagerWindow.java:368)
	at VASSAL.launch.ModuleManagerWindow.<clinit>(ModuleManagerWindow.java:187)
	at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-06-03 13:21:13,075 [17178-AWT-EventQueue-0] ERROR VASSAL.build.module.metadata.MetaDataFactory - 
java.io.FileNotFoundException: /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0.vmod (Operation not permitted)
	at java.base/java.io.RandomAccessFile.open0(Native Method)
	at java.base/java.io.RandomAccessFile.open(RandomAccessFile.java:346)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:260)
	at java.base/java.io.RandomAccessFile.<init>(RandomAccessFile.java:214)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:1332)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:1298)
	at java.base/java.util.zip.ZipFile$CleanableResource.<init>(ZipFile.java:716)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:243)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:172)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:186)
	at VASSAL.build.module.metadata.MetaDataFactory.buildMetaData(MetaDataFactory.java:60)
	at VASSAL.launch.ModuleManagerWindow$ModuleInfo.loadMetaData(ModuleManagerWindow.java:1426)
	at VASSAL.launch.ModuleManagerWindow$ModuleInfo.<init>(ModuleManagerWindow.java:1460)
	at VASSAL.launch.ModuleManagerWindow.lambda$buildTree$3(ModuleManagerWindow.java:569)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.DistinctOps$1$1.accept(DistinctOps.java:151)
	at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at VASSAL.launch.ModuleManagerWindow.buildTree(ModuleManagerWindow.java:568)
	at VASSAL.launch.ModuleManagerWindow.<init>(ModuleManagerWindow.java:368)
	at VASSAL.launch.ModuleManagerWindow.<clinit>(ModuleManagerWindow.java:187)
	at VASSAL.launch.ModuleManager.launch(ModuleManager.java:384)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
2023-06-03 13:21:13,102 [17178-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManagerWindow - Module /Users/Mark/Downloads/CCNapoleonics4_2_0.vmod not found - Removed.
2023-06-03 13:21:13,112 [17178-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManagerWindow - Module /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/C&C Ancients/CCAncientsV4-3-5.vmod not found - Removed.
2023-06-03 13:21:13,116 [17178-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManagerWindow - Module /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0.vmod not found - Removed.
```

**Comment by BrentEaston** [comment]
Hi Mark,

The error 

> java.io.FileNotFoundException: /Users/Mark/Downloads/CCNapoleonics4_2_0.vmod (Operation not permitted)

is pretty clear, for whatever reason, at that point in time, MacOS is not allowing Vassal to see those files.

I am pretty sure there have been problems in the past with people saving modules in DropBox folders. Can you see if you can reproduce that issue in a non-Dropbox folder?

Also, have a read of this article as see if makes any sense? This 'Operation not permitted' error is not uncommon on Macos. Not sure why you would get it on one build and not the other, unless Joel bumped the Java version in there somewhere.

https://appletoolbox.com/seeing-error-operation-not-permitted-in-macos-mojave/

**Comment by uckelman** [comment]
The last time Java was updated was c115444f, which was on 18 May.

**Comment by cholmcc** [comment]
I think https://github.com/vassalengine/vassal/pull/14578 fixes this issue.
