### ISSUE TITLE
[VSQL] InvalidPathException: Illegal char <:> at index 0: ::{20D04FE0-3AEA-1069-A2D8-08002B30309D}

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12356]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [11801 bytes](https://vassalengine.org/files/gh/ad62f559d00ab5f01fe9489e8972e0b556ae28d5) |

<pre>

VSQL v4.3.5 3.6.19

java.nio.file.InvalidPathException: Illegal char <:> at index 0: ::{20D04FE0-3AEA-1069-A2D8-08002B30309D}
 at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
 at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
 at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
 at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
</pre>

**Comment by uckelman** [comment]
`::{20D04FE0-3AEA-1069-A2D8-08002B30309D}` isn't a valid Windows path.
