### ISSUE TITLE
[WiF CE Maps and Units] Error: Invalid escape character at line 1 column 3.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12355]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | donsgeneralstuff@exemail.com.au |
| Error Log | [21415 bytes](https://vassalengine.org/files/gh/524bc92cbf8521cce0dfb928cf619990d4c989c6) |

<pre>Trying to get Vassal to generate a currency symbol. Tried a number of things to no avail. Then tried a CP trait and entered '\u. At that point, twice now, the uncaought exception error occurred

WiF CE Maps and Units v3.33 3.6.19

java.lang.Error: Invalid escape character at line 1 column 3.
 at bsh.JavaCharStream.readChar(JavaCharStream.java:331)
 at bsh.ParserTokenManager.jjMoveNfa_0(ParserTokenManager.java:1899)
 at bsh.ParserTokenManager.jjMoveStringLiteralDfa0_0(ParserTokenManager.java:271)
 at bsh.ParserTokenManager.getNextToken(ParserTokenManager.java:2102)
</pre>

**Comment by Cattlesquat** [comment]
@BrentEaston This is in the Beanshell parser apparently - I wasn't able to duplicate from what he described but I may not have done it correctly.

**Comment by BrentEaston** [comment]
Yeah, but sounds like he is entering weird unicode expressions. 

What's the expected outcome? That we implement full support for displaying arbitrary Unicode characters, or that we hide the exception?

It seems to be happening in the Expression Validator, so I could just convert this to a Red Tick?

**Comment by Cattlesquat** [comment]
Yes I would be more expecting "fail gracefully" instead of generating strange exception

**Comment by uckelman** [comment]
Why doesn't he just paste in the character he wants? Java already has full Unicode support for strings.
