### ISSUE TITLE
[Commands & Colors: Napoleonics] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12351]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | markben61@gmail.com |
| Error Log | [94278 bytes](https://vassalengine.org/files/gh/d744a96d44ed1d14195879fd222ac4b625242130) |

<pre>Vassal (editor session) went into long stall when I pressed an Action button that I'd just updated. Possibly a logic error in my change but I did not get an infinite loop error.

Commands & Colors: Napoleonics v4.1.10 3.6.19

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.getProperty(Decorator.java:173)
 at VASSAL.counters.Embellishment.getProperty(Embellishment.java:811)
 at VASSAL.counters.Decorator.getProperty(Decorator.java:173)
 at VASSAL.counters.Embellishment.getProperty(Embellishment.java:811)
</pre>

**Comment by riverwanderer** [comment]
The action button had a bug that caused an infinite loop.

**Comment by Cattlesquat** [comment]
Stack trace shows not an infinite loop but more like a really really really complicated set of interactions of lots and lots and lots of traits & properties that *actually* overflowed the stack. I don't actually know what determines Java's max stack size or if that's increasable.

**Comment by riverwanderer** [comment]
The screenshot illustrates my specific error:
<img width="962" alt="image" src="https://github.com/vassalengine/vassal/assets/58135975/c42d95d4-01f0-4620-84f6-cb88d24829a5">

I'd meant to put `prepBuild` as the Loop `index property name` (to control the reporting action) but I'd accidentally put it into the Perform before looping starts field.  It takes the same name as the Hotkey that triggers the Action Button, hence the dire consequence.
