### ISSUE TITLE
[WiF CE Maps and Units] RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 476550 out of bounds for length 476550

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12365]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [9154 bytes](https://vassalengine.org/files/gh/9d1a92b51b857f895fa3fadc0589b85fa2cb2793) |

<pre>

WiF CE Maps and Units v3.26 3.6.19

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 476550 out of bounds for length 476550
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 476550 out of bounds for length 476550
</pre>

**Comment by uckelman** [comment]
I don't see how we can be getting an ArrayIndexOutOfBounds exception from the ArrayList constructor.

**Comment by uckelman** [comment]
Duplicate of #12713.
