### ISSUE TITLE
NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "info" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12385]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [2459 bytes](https://vassalengine.org/files/gh/c4402a857e9e14a80582e6e2f5150ea00730c30d) |

<pre>

3.6.19

java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "info" is null
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.setMountPoints(CgroupSubsystemFactory.java:351)
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.amendCgroupInfos(CgroupSubsystemFactory.java:327)
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.determineType(CgroupSubsystemFactory.java:188)
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:85)
</pre>

**Comment by uckelman** [comment]
[This](https://github.com/bazelbuild/bazel/issues/16982) suggests that the bug is fixed, but maybe not in Java 17.0.7?
