### ISSUE TITLE
NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "info" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12386]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [2459 bytes](https://vassalengine.org/files/gh/58903a3332f7d3eb0f040076e3ec8b09ef13c50a) |

<pre>

3.6.19

java.lang.NullPointerException: Cannot invoke "jdk.internal.platform.CgroupInfo.getMountPoint()" because "info" is null
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.setMountPoints(CgroupSubsystemFactory.java:351)
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.amendCgroupInfos(CgroupSubsystemFactory.java:327)
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.determineType(CgroupSubsystemFactory.java:188)
 at java.base/jdk.internal.platform.CgroupSubsystemFactory.create(CgroupSubsystemFactory.java:85)
</pre>

**Comment by uckelman** [comment]
Duplicate of #12385.
