### ISSUE TITLE
[GDW Bloodtree Rebellion] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12411]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [69479 bytes](https://vassalengine.org/files/gh/693f22c1fa9011a35dd155829fd843188b1f1894) |

<pre>

GDW Bloodtree Rebellion v0.0 3.6.19

java.lang.NullPointerException: null
 at VASSAL.configure.ConfigureTree.notifyUpdate(ConfigureTree.java:510)
 at VASSAL.configure.ConfigureTree.nodeEdited(ConfigureTree.java:2438)
 at VASSAL.configure.EditPropertiesAction.actionPerformed(EditPropertiesAction.java:146)
 at VASSAL.configure.ConfigureTree$1.actionPerformed(ConfigureTree.java:342)
</pre>

**Comment by uckelman** [comment]
`editorWindow` is null.
