### ISSUE TITLE
[Legendary: A Marvel Deck Building Game] NullPointerException: Cannot invoke "VASSAL.build.module.properties.PropertySource.getProperty(Object)" because "this.source" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12464]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [67906 bytes](https://vassalengine.org/files/gh/dd5ad717a0364b18c940a5eb508b24dc39c436f3) |

<pre>Opening the Module

Legendary: A Marvel Deck Building Game v5.0.2 3.6.19

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.properties.PropertySource.getProperty(Object)" because "this.source" is null
 at VASSAL.script.ExpressionInterpreter.evaluate(ExpressionInterpreter.java:273)
 at VASSAL.script.expression.BeanShellExpression.evaluate(BeanShellExpression.java:65)
 at VASSAL.script.expression.Expression.tryEvaluate(Expression.java:213)
 at VASSAL.script.expression.Expression.tryEvaluate(Expression.java:138)
</pre>

**Comment by BrentEaston** [comment]
Fixed in 3.7 by https://github.com/vassalengine/vassal/pull/12382
