### ISSUE TITLE
[Steak Alpha 001] StringIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12471]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [145265 bytes](https://vassalengine.org/files/gh/73d8e823fc7060c07e88bed8c1d48d5c3806d200) |

<pre>

Steak Alpha 001 v0.001 3.6.19

java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
 at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
 at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
 at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
</pre>

**Comment by uckelman** [comment]
`displayStyle = s.charAt(0);` is run when `s` is the empty string.
