### ISSUE TITLE
[Commands & Colors Ancients] StackOverflowError

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12502]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | mk20336@yahoo.com |
| Error Log | [70742 bytes](https://vassalengine.org/files/gh/beb68f3bd1abc3f1e18f2dcc9db384480e9abc6c) |

<pre>Error during opening a saved game.

Commands & Colors Ancients v4.3.7 3.6.19

java.lang.StackOverflowError: null
 at VASSAL.counters.Decorator.getState(Decorator.java:400)
 at VASSAL.counters.Decorator.getState(Decorator.java:401)
 at VASSAL.counters.Decorator.getState(Decorator.java:401)
 at VASSAL.counters.Decorator.getState(Decorator.java:401)
</pre>

**Comment by riverwanderer** [comment]
Does this reproduce? If so, can you attach the save game ?

**Comment by riverwanderer** [comment]
I can't get this error to reproduce using the latest CCA module (V4.3.9), which contains no relevant changes compated with the reported error version. Have asked Michel if it was a "one off" for him too.

@uckelman - is there enough info in the above report to match this with any other open ABRs ?

**Comment by uckelman** [comment]
Does it look similar to #11306?

**Comment by riverwanderer** [comment]
> Does it look similar to #11306?

Not if #11306 affects just editting. The user was in the player attempting to open a save file.
