### ISSUE TITLE
[Malifaux 3e] RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 915 out of bounds for length 915

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12518]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [146508 bytes](https://vassalengine.org/files/gh/ba46d4cf1d29232860e46ebeb1e83278d34ed064) |

<pre>

Malifaux 3e vMoM_v4g 3.6.19

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 915 out of bounds for length 915
 at VASSAL.launch.Launcher.<init>(Launcher.java:166)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 915 out of bounds for length 915
</pre>

**Comment by uckelman** [comment]
Duplicate of #12365.
