### ISSUE TITLE
[Littoral Commander: Indo-Pacific] ArithmeticException: / by zero

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12582]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | rmalanchuk@live.com |
| Error Log | [116114 bytes](https://vassalengine.org/files/gh/40cce2b2a3b728216f4d43e64b1417157f913a7a) |

<pre>I'm trying to update another person's module with new boards. I loaded a new map Image and tried to run a new game loading the map. 

Littoral Commander: Indo-Pacific v1.2 3.6.19

java.lang.ArithmeticException: / by zero
 at VASSAL.build.module.map.boardPicker.board.mapgrid.Zone.getLocation(Zone.java:363)
 at VASSAL.build.module.map.boardPicker.board.ZonedGrid.getLocation(ZonedGrid.java:228)
 at VASSAL.build.module.map.SetupStack.updatePosition(SetupStack.java:203)
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:265)
</pre>

**Comment by uckelman** [comment]
The exception happens here, because the pologon has no points:
```
      p.x /= myPolygon.npoints;
```
