### ISSUE TITLE
[Bios Megafauna 2nd Edition] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12580]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | pedro.hbt.almeida@gmail.com |
| Error Log | [7883 bytes](https://vassalengine.org/files/gh/79fd5bb1f0ac725dbf3e43f7b1fde36c0ab0baae) |

<pre>While entering my name to begin a game

Bios Megafauna 2nd Edition v3 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #5813
