### ISSUE TITLE
[VASL] ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getType()" because "img" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12606]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter | matthewsroot@gmail.com |
| Error Log | [16827 bytes](https://vassalengine.org/files/gh/f3af4a39b5a5f405c65c9b671eef0b47e76ffc7b) |

<pre>I don't remember. I walked away and did the dishes then came back to this error. I know I am trying to get the SaF module to work. 

VASL v6.6.6 3.6.19

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException: Cannot invoke "java.awt.image.BufferedImage.getType()" because "img" is null
 at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
 at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
 at java.desktop/javax.swing.SwingWorker.get(SwingWorker.java:613)
 at VASSAL.tools.opcache.OpCache$Request.done(OpCache.java:209)
</pre>

**Comment by uckelman** [comment]
Advised user to set a higher max heap.
