### ISSUE TITLE
[Absolute Victory] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12631]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [7949 bytes](https://vassalengine.org/files/gh/124413ab3ec77d7c2a18c313ed6a88d348841f8a) |

<pre>

Absolute Victory v1.2 3.6.19

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:289)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #5813
