### ISSUE TITLE
[OCS - Smolensk EF (dev)] UnsupportedOperationException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12637]
| ABR | |
|-----|-----|
| Version | 3.7.0-beta5 |
| Reporter |  |
| Error Log | [14316 bytes](https://vassalengine.org/files/gh/9d1fa899ca8a2ca578684f74ab25337682a71c22) |

<pre>Seach string - last entry in module found, cycling back to start of module

OCS - Smolensk EF (dev) v1.18 (EF) dev 3.7.0-beta5

java.lang.UnsupportedOperationException: null
 at java.base/java.util.ImmutableCollections.uoe(ImmutableCollections.java:142)
 at java.base/java.util.ImmutableCollections$AbstractImmutableCollection.add(ImmutableCollections.java:147)
 at VASSAL.counters.CounterGlobalKeyCommand.getPropertyList(CounterGlobalKeyCommand.java:235)
 at VASSAL.configure.ConfigureTree$SearchAction.checkSearchTarget(ConfigureTree.java:2280)
</pre>

**Comment by BrentEaston** [comment]
Thanks, This is a known problem fixed in beta6
