### ISSUE TITLE
[VASL] ExecutionException: java.lang.NegativeArraySizeException: -1422608753

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12664]
| ABR | |
|-----|-----|
| Version | 3.6.19 |
| Reporter |  |
| Error Log | [53467 bytes](https://vassalengine.org/files/gh/948fd7a7e046c93035acdba8b1f3242853b8bb86) |

<pre>

VASL v6.6.6 3.6.19

java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
 at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:323)
 at VASSAL.tools.opcache.OpCache.get(OpCache.java:261)
 at VASSAL.tools.opcache.AbstractOpImpl.get(AbstractOpImpl.java:80)
 at VASSAL.tools.imageop.AbstractOpImpl.getImage(AbstractOpImpl.java:101)
</pre>

**Comment by uckelman** [comment]
User had max heap set too low.
