### ISSUE TITLE
"c" is null exception on starting a scenario in main room

### ISSUE THREAD

**Issue by riverwanderer** [vassalengine/vassal#12683]
Vassal version: VASSAL version 3.7.1-SNAPSHOT-f81e59a-master
Dev version of C&C Nap module triggered this exception:

2023-09-12 14:08:11,160 [3372-main] INFO  VASSAL.launch.StartUp - Starting
2023-09-12 14:08:11,175 [3372-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 12.6.8 x86_64
2023-09-12 14:08:11,175 [3372-main] INFO  VASSAL.launch.StartUp - Java version 20.0.2
2023-09-12 14:08:11,175 [3372-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL 2.app/Contents/MacOS/jre
2023-09-12 14:08:11,175 [3372-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.1-SNAPSHOT-f81e59a-master
2023-09-12 14:08:11,915 [3372-AWT-EventQueue-0] INFO  VASSAL.launch.ModuleManager - Manager
2023-09-12 14:10:58,365 [3372-SwingWorker-pool-1-thread-1] INFO  VASSAL.launch.AbstractLaunchAction - Loading module file /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0DEV.vmod
2023-09-12 14:10:59,588 [3372-SwingWorker-pool-1-thread-1] INFO  VASSAL.launch.TilingHandler - No images to tile.
2023-09-12 14:10:59,590 [3372-SwingWorker-pool-1-thread-1] INFO  VASSAL.launch.AbstractLaunchAction - Loading module Commands & Colors: Napoleonics
2023-09-12 14:10:59,596 [3372-SwingWorker-pool-1-thread-1] INFO  VASSAL.tools.io.ProcessLauncher - launching /Applications/VASSAL 2.app/Contents/MacOS/jre/bin/java -Xms1024M -Xmx1024M -Duser.home=/Users/Mark -Duser.dir=/Applications/VASSAL 2.app -cp Contents/Resources/Java/Vengine.jar -Xdock:name=Commands & Colors: Napoleonics -Xdock:icon=/Applications/VASSAL 2.app/Contents/Resources/VASSAL.icns VASSAL.launch.Player --load -- /Users/Mark/Library/CloudStorage/Dropbox/Vassal Test Releases/CCN4/CCNapoleonics4_2_0DEV.vmod
2023-09-12 14:11:00,593 [3577-main] INFO  VASSAL.launch.StartUp - Starting
2023-09-12 14:11:00,612 [3577-main] INFO  VASSAL.launch.StartUp - OS Mac OS X 12.6.8 x86_64
2023-09-12 14:11:00,612 [3577-main] INFO  VASSAL.launch.StartUp - Java version 20.0.2
2023-09-12 14:11:00,612 [3577-main] INFO  VASSAL.launch.StartUp - Java home /Applications/VASSAL 2.app/Contents/MacOS/jre
2023-09-12 14:11:00,612 [3577-main] INFO  VASSAL.launch.StartUp - VASSAL version 3.7.1-SNAPSHOT-f81e59a-master
2023-09-12 14:11:00,613 [3577-main] INFO  VASSAL.launch.Launcher - Player
2023-09-12 14:11:09,439 [3577-AWT-EventQueue-0] INFO  VASSAL.build.GameModule - Commands & Colors: Napoleonics version 4.2.0a40
2023-09-12 14:13:12,325 [3577-AWT-EventQueue-0] ERROR VASSAL.tools.ErrorDialog - 
java.lang.NullPointerException: Cannot invoke "VASSAL.command.Command.getSubCommands()" because "c" is null
	at VASSAL.command.CommandFilter.apply(CommandFilter.java:31)
	at VASSAL.chat.MainRoomChecker.filter(MainRoomChecker.java:37)
	at VASSAL.chat.node.NodeClient.forward(NodeClient.java:283)
	at VASSAL.chat.node.NodeClient.sendToOthers(NodeClient.java:303)
	at VASSAL.chat.node.NodeClient.sendToOthers(NodeClient.java:270)
	at VASSAL.chat.HybridClient.sendToOthers(HybridClient.java:85)
	at VASSAL.build.GameModule.sendAndLog(GameModule.java:1876)
	at VASSAL.build.module.GlobalKeyCommand.apply(GlobalKeyCommand.java:73)
	at VASSAL.build.module.StartupGlobalKeyCommand.apply(StartupGlobalKeyCommand.java:306)
	at VASSAL.build.module.StartupGlobalKeyCommand.applyIfNotApplied(StartupGlobalKeyCommand.java:285)
	at VASSAL.build.module.GameState.applyStartupGlobalKeyCommands(GameState.java:442)
	at VASSAL.build.module.GameState.applyStartupGlobalKeyCommands(GameState.java:446)
	at VASSAL.build.module.GameState.doStartupGlobalKeyCommands(GameState.java:456)
	at VASSAL.build.module.GameState.lambda$setup$1(GameState.java:576)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by riverwanderer** [comment]
Also occurs in v3.7.0.
Sequence:
Start module
Connect online.
Start a scenario.
Connect as observer.
OK to the not in main room message.
Exception occurs.
