### ISSUE TITLE
[The U.S. Civil War] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12698]
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter |  |
| Error Log | [7964 bytes](https://vassalengine.org/files/gh/3a20cf62a45ff26842590fb2a4382dcc80a16d10) |

<pre>filling in a new username and pass

The U.S. Civil War v1.15 3.7.0

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by uckelman** [comment]
Duplicate of #5813.
