### ISSUE TITLE
[SCS Panzer Battles - Chir River] RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 32734 out of bounds for length 32734

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12713]
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter | gfw1010@charter.net |
| Error Log | [219169 bytes](https://vassalengine.org/files/gh/8f296f7ab7e370b2c14527ff995d151ad94950af) |

<pre>Opening module for first time. Fedora38.

SCS Panzer Battles - Chir River v2.00 3.7.0

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 32734 out of bounds for length 32734
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.ArrayIndexOutOfBoundsException: Index 32734 out of bounds for length 32734
</pre>

**Comment by uckelman** [comment]
I don't see how we can be getting an ArrayIndexOutOfBounds exception from the ArrayList constructor.
