### ISSUE TITLE
[Commands & Colors Ancients] NullPointerException: Cannot invoke "VASSAL.command.Command.getSubCommands()" because "c" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12714]
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter |  |
| Error Log | [36759 bytes](https://vassalengine.org/files/gh/400f281701dfcfe452061364c7b8c8f58f70672b) |

<pre>

Commands & Colors Ancients v4.3.4 3.7.0

java.lang.NullPointerException: Cannot invoke "VASSAL.command.Command.getSubCommands()" because "c" is null
 at VASSAL.command.CommandFilter.apply(CommandFilter.java:31)
 at VASSAL.chat.MainRoomChecker.filter(MainRoomChecker.java:37)
 at VASSAL.chat.node.NodeClient.forward(NodeClient.java:283)
 at VASSAL.chat.node.NodeClient.sendToOthers(NodeClient.java:303)
</pre>

**Comment by riverwanderer** [comment]
Duplicate of #12683.
