### ISSUE TITLE
[OCS - The Third Winter] ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.opcache.OpFailedException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12722]
| ABR | |
|-----|-----|
| Version | 3.7.0 |
| Reporter |  |
| Error Log | [15497 bytes](https://vassalengine.org/files/gh/befa73b00432eea9b41c29e5d90b5a34520ee4a2) |

<pre>

OCS - The Third Winter v1.13 3.7.0

java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: VASSAL.tools.opcache.OpFailedException
 at VASSAL.tools.opcache.OpCache.getFuture(OpCache.java:323)
 at VASSAL.tools.opcache.AbstractOpImpl.getFuture(AbstractOpImpl.java:86)
 at VASSAL.tools.imageop.AbstractOpImpl.getFutureImage(AbstractOpImpl.java:108)
 at VASSAL.tools.imageop.AbstractTiledOpImpl.getFutureTile(AbstractTiledOpImpl.java:154)
</pre>

**Comment by uckelman** [comment]
User ran out of memory.
