### ISSUE TITLE
[Arkham Horror LCG] NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12869]
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | mi1291@gmail.com |
| Error Log | [32739 bytes](https://vassalengine.org/files/gh/1098a04488e52b744b270729caa5a316c7f5704a) |

<pre>lstarting module afert changing something in editor mode.After restart,  there are no bugs  

Arkham Horror LCG v2.0.4 3.7.5

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.Map.getEdgeBuffer()" because "map" is null
 at VASSAL.build.module.map.SetupStack.setup(SetupStack.java:274)
 at VASSAL.build.module.map.DrawPile.setup(DrawPile.java:1227)
 at VASSAL.build.module.GameState.setup(GameState.java:553)
 at VASSAL.build.module.GameState$8.actionPerformed(GameState.java:260)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #12044 

Supposedly fixed by #12044, but apparently not.
