### ISSUE TITLE
[A Distant Plain] NoClassDefFoundError: javax/script/ScriptException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12868]
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [6850 bytes](https://vassalengine.org/files/gh/87a8366911bb8ecdd35d6eb7d56c98311c978020) |

<pre>

A Distant Plain v3.0 3.7.5

java.lang.NoClassDefFoundError: javax/script/ScriptException
 at coin.DistantAIWindow.aiButtonActionPerformed(DistantAIWindow.java:293)
 at coin.DistantAIWindow.access$0(DistantAIWindow.java:195)
 at coin.DistantAIWindow$DistantAIDialog$1.actionPerformed(DistantAIWindow.java:137)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by uckelman** [comment]
My guess is that the JRE we package doesn't have `javax/script` in it.
