### ISSUE TITLE
[WiF CE Maps and Units Combo] NullPointerException: No owning WizardImplementation for id _#UndeterminedStep

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12895]
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter |  |
| Error Log | [9661 bytes](https://vassalengine.org/files/gh/b92db2954d506d12ff773cb6b89a55698e2ea6cc) |

<pre>

WiF CE Maps and Units Combo v1.03 3.7.5

java.lang.NullPointerException: No owning WizardImplementation for id _#UndeterminedStep
 at org.netbeans.spi.wizard.BranchingWizard.navigatingTo(BranchingWizard.java:284)
 at org.netbeans.spi.wizard.Wizard.navigatingTo(Wizard.java:137)
 at org.netbeans.api.wizard.displayer.WizardDisplayerImpl.navigateTo(WizardDisplayerImpl.java:522)
 at org.netbeans.api.wizard.displayer.NavButtonManager.processNextProceed(NavButtonManager.java:394)
</pre>

**Comment by BrentEaston** [comment]
#5813
