### ISSUE TITLE
[The Other Side] ArrayIndexOutOfBoundsException: Index 71 out of bounds for length 36

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#12979]
| ABR | |
|-----|-----|
| Version | 3.7.5 |
| Reporter | akjones666@gmail.com |
| Error Log | [335831 bytes](https://vassalengine.org/files/gh/342d4152062a0eca28190165936ce16377095c76) |

<pre>Using the Other Side module.

Error occured when I opened a game

The Other Side vv.2.1 Beyond the Other Side 3.7.5

java.lang.ArrayIndexOutOfBoundsException: Index 71 out of bounds for length 36
 at VASSAL.counters.FreeRotator.getAngle(FreeRotator.java:203)
 at VASSAL.counters.FreeRotator.boundingBox(FreeRotator.java:173)
 at VASSAL.counters.FreeRotator.boundingBox(FreeRotator.java:172)
 at VASSAL.counters.FreeRotator.draw(FreeRotator.java:328)
</pre>

**Comment by rlament** [comment]
Seems to me that this is a module problem rather than a Vassal one.

The module has a `Rotate` prototype which comprises of three `Can Rotate` traits. One is setup for arbitrary (free) rotation, the other two fixed with 36 and 72 facings. In the list of traits, the top rotator is the one with 36 facings.

The Vassal Reference manual states that the Rotator name is used to exposes internal properties. Unfortunately, or unknowingly the two fixed rotators have the **same** name. This confuses the Refresher. Since the 72 facing Rotator is lower in the trait list, it takes precedence. I'm not sure on the internal workings, but it seems that this facing is applied to both rotators. Depending on how pieces are arranged on the map, some obviously do have facings in the 36 to 71 range. Since the facing is applied to both Rotators, the range of the topmost Rotator is exceeded causing the exception.

The quick fix is to edit and rename the first Rotator, perhaps something like 'RotateCoarse'. Load the 2.0 vmod and Refresh. Finally, someone has to manually verify the orientation of all pieces as the Refresh may not adjudicate the duplicate naming (it worked ok in my simple test case).

This isn't the best way to handle rotation, as there are three rotations being calculated and each rotator manages it's own facing. To actually determine the true facing, one has to add the three rotator properties. Instead, there could be one free rotator with a dynamic property for the "Rotate direct to" field. Then use Trigger and Set Piece Property traits along with some math to calculate the "direct to" value and let the free rotator do the fixed facing rotations.
