### ISSUE TITLE
[Russian Front] RuntimeException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class VASSAL.build.GameModule cannot be cast to class VASSAL.build.module.properties.GlobalPropertiesContainer (VASSAL.build.GameModule and VASSAL.build.module.properties.GlobalPropertiesContainer are in unnamed module of loader 'app')

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13079]
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter |  |
| Error Log | [24203 bytes](https://vassalengine.org/files/gh/2a6a4a284298bc001888be189eb87c99702f28b7) |

<pre>Opening up RFTv20b30.vmod 

Russian Front v2.0b30 3.7.7

java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class VASSAL.build.GameModule cannot be cast to class VASSAL.build.module.properties.GlobalPropertiesContainer (VASSAL.build.GameModule and VASSAL.build.module.properties.GlobalPropertiesContainer are in unnamed module of loader 'app')
 at VASSAL.launch.Launcher.<init>(Launcher.java:164)
 at VASSAL.launch.Player.<init>(Player.java:62)
 at VASSAL.launch.Player.main(Player.java:57)
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: class VASSAL.build.GameModule cannot be cast to class VASSAL.build.module.properties.GlobalPropertiesContainer (VASSAL.build.GameModule and VASSAL.build.module.properties.GlobalPropertiesContainer are in unnamed module of loader 'app')
</pre>

**Comment by BrentEaston** [comment]
Out of date module
