### ISSUE TITLE
NPE Crash when copy/paste a folder of Deck GKC commands between Decks

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13080]
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter | bhfredjenni@gmail.com |
| Error Log | [5897 bytes](https://vassalengine.org/files/gh/de20190a2e953ff844bb6965c2efc44ccfc8f2cd) |

<pre>I was trying to copy a Folder with multiple DeckGKC and then paste the Folder into a different Deck when I got the error. Yes I can make the error happen again. Making Vassal myself.

Scholars v1.0 3.7.7

java.lang.NullPointerException: Cannot invoke "VASSAL.build.module.map.DrawPile.addGlobalKeyCommand(VASSAL.build.module.map.DeckGlobalKeyCommand)" because "parent" is null
 at VASSAL.build.module.map.DeckGlobalKeyCommand.addTo(DeckGlobalKeyCommand.java:123)
 at VASSAL.build.Builder.build(Builder.java:82)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
 at VASSAL.configure.ConfigureTree$7.actionPerformed(ConfigureTree.java:888)
</pre>

**Comment by BrentEaston** [comment]
Symptom of general problem #13106
