### ISSUE TITLE
[Fantasy Battle] IllegalBuildException: failed to load class VASSAL.build.module.PrototypesContainer

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13116]
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter | nmcternan747@gmail.com |
| Error Log | [7910 bytes](https://vassalengine.org/files/gh/9ad4883562c83ba6bbd9add4cfc863cc162155c8) |

<pre>Opened a Fantasy Battle module, it crashed immedietly. Probably cause of the depreciated functions

Fantasy Battle v0.4 3.7.7

VASSAL.build.IllegalBuildException: failed to load class VASSAL.build.module.PrototypesContainer
 at VASSAL.build.Builder.create(Builder.java:145)
 at VASSAL.build.Builder.build(Builder.java:80)
 at VASSAL.build.AbstractBuildable.build(AbstractBuildable.java:104)
 at VASSAL.build.GameModule.build(GameModule.java:785)
</pre>

**Comment by BrentEaston** [comment]
Very old custom code, needs to be updated.
