### ISSUE TITLE
[Liberty or Death (GMT)] OverlappingFileLockException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13110]
| ABR | |
|-----|-----|
| Version | 3.7.7 |
| Reporter |  |
| Error Log | [19752 bytes](https://vassalengine.org/files/gh/73ae2cb4e9dc72c6e15721062ae0e49623c6643f) |

<pre>

Liberty or Death (GMT) v2.0 3.7.7

java.nio.channels.OverlappingFileLockException: null
 at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229)
 at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123)
 at java.base/sun.nio.ch.FileChannelImpl.lock(FileChannelImpl.java:1475)
 at java.base/java.nio.channels.FileChannel.lock(FileChannel.java:1240)
</pre>

**Comment by BrentEaston** [comment]
Ran out of Disk space
