### ISSUE TITLE
[VASL] RuntimeException: Unexpected block close in selector

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13128]
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter | giohioti@gmail.com |
| Error Log | [17205 bytes](https://vassalengine.org/files/gh/aed198831da41c6f6ae7205cf7f287bd2a8dc13e) |

<pre>Trying to insert an HTML table in a "Label" using the VASL module (Virtual Advanced Squad Leader).. The HTML code is below:<html>
<head>

    <style>
        table {
            width: 100%;
            border-collapse: collapse;
			/* Dark to light orange gradient */ 
			border: 2px double #000; /* Double line border with black color */
        }

        th, td {
            border: 1px solid black;
            padding: 8px;
            text-align: center;
        }
		
		        }

      .military-font {
            font-family: "Army Rust", sans-serif;
            font-size: 24px;
            font-weight: bold;
        }
		
		.greyletters {
            width: 200px;
            height: 136px;
			background: white;
            color: #808080; /* Light grey color */
        }
		.greyletterstwo {
            width: 200px;
            height: 75px;
			background: white;
            color: #808080; /* Light grey color */
       
		    .left-justified {
            text-align: left;
        }
		
		    .turn-chart {
            font-size: 16px; /* Adjust the font size as needed */
            font-weight: bold;
            text-align: center;
        }
		    .large-numeral {
			font-size: 24px; /* Adjust the font size as needed */
			width: 50px;
        }
		    .soviet-star-image {
            content: url('https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Order_of_the_Patriotic_War_%28Ist_class%29.svg/800px-Order_of_the_Patriotic_War_%28Ist_class%29.svg.png');
        }
		    .blank-grey-cell {
            background-color: #d3d3d3; /* Grey background color */
        }
    </style>
</head>
<body>

<table>
    
    <tr>
        <th colspan="11" class="military-font">ASL SCENARIO U27 - A WINTER MELEE</th>
    </tr>
    
    <tr>
	    <tr>
        <td colspan="2" rowspan="4">
            <img src="https://upload.wikimedia.org/wikipedia/commons/3/3d/Bundesarchiv_Bild_101I-274-0498-15%2C_Russland%2C_Soldat_mit_MG_34.jpg?20220703191646" alt="Spanned Image" class="spanned-image" width="200" height="136">
        </td>
        
        
    </tr>
        <td colspand="2" rowspan="3" class="greyletters">Phase<br>Marker</td> 
        <t    <tr>
        <td colspan="9" class="turn-chart">TURN RECORD CHART</td>
        
    </tr>

    
    <tr>
        <td colspan="2" class="left-justified">
		    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Order_of_the_Patriotic_War_%28Ist_class%29.svg/800px-Order_of_the_Patriotic_War_%28Ist_class%29.svg.png" alt="Soviet Star" class="soviet-star" width="20" height="20">
            <span class="soviet-star-text">RUSSIAN Sets Up First [60]</span> 
		</td>
        <td class="large-numeral">1</td>
        <td class="large-numeral">2</td>
        <td class="large-numeral">3</td>
        <td class="large-numeral">4</td>
        <td class="large-numeral">5</td>
        <td class="blank-grey-cell"></td>

    </tr>
    
    <tr>
        <td colspan="2" class="left-justified">
		    <img src="https://upload.wikimedia.org/wikipedia/commons/5/56/Regulation_WW_II_Upperwing_Balkenkreuz.png" width="20" height="20">
            <span class="soviet-star-text">GERMAN Moves First [120]</span> 
		</td>
        <td class="large-numeral">6</td>
        <td class="large-numeral">7</td>
        <td class="large-numeral">8</td>
        <td class="large-numeral">9</td>
        <td class="large-numeral">10</td>
        <td style="font-size: 24px;"><b>END</b></td>

    </tr>
    
    <tr>
        <td style="font-size: 12px;" colspan="2"><b>OKOROVOVO, RUSSIA, 17 February 1942</td>
        <td style="font-size: 12px;" class="left-justified"><b>VICTORY CONDITIONS:</b> The Russian/partisans win at game end by Controlling all five stone buildings<br> on board 3.</td>
        <td class="greyletterstwo">Compass</td>
        <td class="greyletterstwo">Wind<br>Direction</td>
        <td class="greyletterstwo">Wind</td>
        <td class="greyletterstwo">ECs</td>
        <td class="greyletterstwo">No Quarter</td>
        <td class="greyletterstwo">Snow</td>
        <td class="greyletterstwo">Environmental<br>Conditions</td>
        <td class="greyletterstwo">Interdiction</td>

    </tr>
</table>

</body>
</html>

VASL v6.6.7 3.7.8

java.lang.RuntimeException: Unexpected block close in selector
 at java.desktop/javax.swing.text.html.CSSParser.parseSelectors(CSSParser.java:311)
 at java.desktop/javax.swing.text.html.CSSParser.parseRuleSet(CSSParser.java:271)
 at java.desktop/javax.swing.text.html.CSSParser.getNextStatement(CSSParser.java:179)
 at java.desktop/javax.swing.text.html.CSSParser.parse(CSSParser.java:154)
</pre>

**Comment by rlament** [comment]
This just looks like misplaced curly braces in the <style> section. There's an extra closing brace before `.military-font` and one missing for `.greyletterstwo`.
