### ISSUE TITLE
[TTG] NullPointerException: Cannot invoke "VASSAL.configure.Configurer.getControls()" because "this.configurer" is null

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13152]
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter | eclectictllc@gmail.com |
| Error Log | [49079 bytes](https://vassalengine.org/files/gh/fba19f47656739d1fa31b69c8140a4c1e06aa31d) |

<pre>Did it again when adding another List Scenario Property then going back in to edit it.

TTG v0.8.2 3.7.8

java.lang.NullPointerException: Cannot invoke "VASSAL.configure.Configurer.getControls()" because "this.configurer" is null
 at VASSAL.configure.PropertiesWindow.initialize(PropertiesWindow.java:119)
 at VASSAL.configure.PropertiesWindow.<init>(PropertiesWindow.java:60)
 at VASSAL.configure.EditPropertiesAction.actionPerformed(EditPropertiesAction.java:70)
 at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
</pre>

**Comment by BrentEaston** [comment]
Emailed user for more details.
