### ISSUE TITLE
[Pax Emancipation] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13164]
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter | aberlanas@disroot.org |
| Error Log | [209637 bytes](https://vassalengine.org/files/gh/7b04bf1c094b6775c65f3abd09838044462c63d9) |

<pre>Write Log

Pax Emancipation v1.5 3.7.8

java.lang.NullPointerException: null
 at java.base/java.util.Objects.requireNonNull(Objects.java:233)
 at VASSAL.tools.io.ZipWriter.<init>(ZipWriter.java:48)
 at VASSAL.build.module.BasicLogger.write(BasicLogger.java:447)
 at VASSAL.build.module.BasicLogger$1.actionPerformed(BasicLogger.java:657)
</pre>

**Comment by BrentEaston** [comment]
Seems to be trying to end a log file, but has no log file to end.
