### ISSUE TITLE
[Eylau] SAXParseException: Il markup nel documento che segue l'elemento radice deve avere un formato corretto.

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13165]
| ABR | |
|-----|-----|
| Version | 3.7.8 |
| Reporter |  |
| Error Log | [9838 bytes](https://vassalengine.org/files/gh/f623d27edc14ee617d3a5dc56fd647edb05493e2) |

<pre>importing an XML file

Eylau v0.2 3.7.8

org.xml.sax.SAXParseException: Il markup nel documento che segue l'elemento radice deve avere un formato corretto.
 at java.xml/com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:262)
 at java.xml/com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:342)
 at java.xml/javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:206)
 at VASSAL.configure.ConfigureTree.importTreeBranch(ConfigureTree.java:599)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #13166
