### ISSUE TITLE
[Formula Dé] JavaLayerException: Cannot create AudioDevice

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13230]
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | manu.abad16@gmail.com |
| Error Log | [27543 bytes](https://vassalengine.org/files/gh/619de8c247e872990f732917f2c7c14d3b8e83ac) |

<pre>Estoy intentando poner una ficha en el tablero. La ficha no aparece en el tablero

Formula Dé v3.0 3.7.9

javazoom.jl.decoder.JavaLayerException: Cannot create AudioDevice
 at javazoom.jl.player.FactoryRegistry.createAudioDevice(FactoryRegistry.java:97)
 at javazoom.jl.player.Player.<init>(Player.java:97)
 at javazoom.jl.player.Player.<init>(Player.java:82)
 at VASSAL.tools.Mp3AudioClip.getPlayer(Mp3AudioClip.java:75)
</pre>

**Comment by riverwanderer** [comment]
translation: I'm trying to put a piece on the board. The token does not appear on the board
