### ISSUE TITLE
[Galactic Rising] StringIndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13253]
| ABR | |
|-----|-----|
| Version | 3.7.9 |
| Reporter | mjjhatchen@tutanota.com |
| Error Log | [19978 bytes](https://vassalengine.org/files/gh/3d233650248b8dc4f5d6d4856979eb286423ba6b) |

<pre>Pressed Enter while in Return To Deck as a means to exit out of it. 

Galactic Rising v0.2 3.7.9

java.lang.StringIndexOutOfBoundsException: Index 0 out of bounds for length 0
 at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:55)
 at java.base/jdk.internal.util.Preconditions$1.apply(Preconditions.java:52)
 at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:213)
 at java.base/jdk.internal.util.Preconditions$4.apply(Preconditions.java:210)
</pre>

**Comment by BrentEaston** [comment]
Mass Piece Definer issue,
