### ISSUE TITLE
[Unnamed module] NullPointerException

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13312]
| ABR | |
|-----|-----|
| Version | 3.7.10 |
| Reporter |  |
| Error Log | [2162 bytes](https://vassalengine.org/files/gh/a58155cf82e73fe939d987de624d60c43f5fcf76) |

<pre>Fresh install. Tried to select a button icon. Wasn't able to find it. Pressed "Cancel"

Unnamed module v0.0 3.7.10

java.lang.NullPointerException: null
 at java.base/java.io.File.<init>(File.java:278)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.filenameFilterCallback(GtkFileDialogPeer.java:107)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.run(Native Method)
 at java.desktop/sun.awt.X11.GtkFileDialogPeer.showNativeDialog(GtkFileDialogPeer.java:195)
</pre>

**Comment by BrentEaston** [comment]
Appears to be a Linux specific Java Bug. Suggest trying a different version of Java
