### ISSUE TITLE
[WaR2 module] FileNotFoundException: 'Campaign2.vsav' not found in /home/pdietrich/DatenServer/Peter/Spiele/1939 - Second World War/Decision Games - GOSS/Decision Games - Wacht am Rhein IV/Bx-GOSS_Wacht_V2.vmod

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13359]
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [33442 bytes](https://vassalengine.org/files/gh/f58f03531af771614bca4eb0d6fd0ddb1b89dcb5) |

<pre>

WaR2 module v2.0 3.7.12

java.io.FileNotFoundException: 'Campaign2.vsav' not found in /home/pdietrich/DatenServer/Peter/Spiele/1939 - Second World War/Decision Games - GOSS/Decision Games - Wacht am Rhein IV/Bx-GOSS_Wacht_V2.vmod
 at VASSAL.tools.DataArchive.getInputStream(DataArchive.java:179)
 at VASSAL.build.module.PredefinedSetup.getSavedGameContents(PredefinedSetup.java:222)
 at VASSAL.build.module.PredefinedSetup.refreshWithStatus(PredefinedSetup.java:303)
 at VASSAL.configure.RefreshPredefinedSetupsDialog.refreshPredefinedSetups(RefreshPredefinedSetupsDialog.java:420)
</pre>

**Comment by BrentEaston** [comment]
Should be reported in GameRefresher log, not as a Vassla bug.
