### ISSUE TITLE
[FoGAM] IllegalArgumentException: Window must not be zero

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13407]
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter |  |
| Error Log | [11542 bytes](https://vassalengine.org/files/gh/b0adea4a5e6d36f6f7f3e264d2c2a2df2b041c73) |

<pre>

FoGAM v1.0 3.7.12

java.lang.IllegalArgumentException: Window must not be zero
 at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(Unknown Source)
 at java.desktop/sun.awt.X11.WindowPropertyGetter.<init>(Unknown Source)
 at java.desktop/sun.awt.X11.XlibUtil.isToplevelWindow(Unknown Source)
 at java.desktop/sun.awt.X11.XWindowPeer.setToplevelTransientFor(Unknown Source)
</pre>

**Comment by BrentEaston** [comment]
Issue in the Linux Native File Open dialog in this version of Java
