### ISSUE TITLE
ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6 Refreshing Can Rotate pieces

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13400]
| ABR | |
|-----|-----|
| Version | 3.7.12 |
| Reporter | revnye@yahoo.com |
| Error Log | [10454 bytes](https://vassalengine.org/files/gh/f7ebbc3f1dc7c827ba38b87f237da2ed98dd3820) |

<pre>Refresh counters

Men of Iron: The battle of Cortenuova v.1 3.7.12

java.lang.ArrayIndexOutOfBoundsException: Index 6 out of bounds for length 6
 at VASSAL.counters.FreeRotator.getAngle(FreeRotator.java:203)
 at VASSAL.counters.FreeRotator.boundingBox(FreeRotator.java:173)
 at VASSAL.counters.Delete.boundingBox(Delete.java:181)
 at VASSAL.counters.Footprint.getMyBoundingBox(Footprint.java:630)
</pre>

**Comment by BrentEaston** [comment]
Caused by reducing the number of faces on a Can Rotate trait, then refreshing a game containing a piece that is facing a side > the new face count.
