### ISSUE TITLE
Editor Search may generate Regex.Pattern.matcherexception

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13601]
| ABR | |
|-----|-----|
| Version | 3.7.14 |
| Reporter | markben61@gmail.com |
| Error Log | [1663415 bytes](https://vassalengine.org/files/gh/37cb7b7e29d7880706539f05e6d153bd57f10dbb) |

<pre>Search for start of word "gOrder\M" - nothing found; then search again for same using "Regular Expression" mode, resulting in this error.

Commands & Colors: Napoleonics V5 v5.1.0a817 3.7.14

java.lang.NullPointerException: Cannot invoke "java.util.regex.Pattern.matcher(java.lang.CharSequence)" because "regexPattern" is null
 at VASSAL.configure.ConfigureTree$SearchAction.checkString(ConfigureTree.java:3236)
 at VASSAL.configure.ConfigureTree$SearchAction.checkNode(ConfigureTree.java:2812)
 at VASSAL.configure.ConfigureTree$SearchAction.lambda$findNode$9(ConfigureTree.java:2654)
 at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:193)
</pre>

Also, yielding this report in the chat log:
`- Search string is not a valid Regular Expression: Illegal/unsupported escape sequence near index 7 gOrder\M ^`

**Comment by riverwanderer** [comment]
This can occur when the user selects the Regular expression search option but the search text is not a valid Regular Expression.  For example,

<img width="588" alt="image" src="https://github.com/user-attachments/assets/662b1201-00de-4bca-94ca-c0ce25f7fed9" />

Vassal does trap for the error and reports it in the chat log. In the above example, this chat log is generated:
<img width="509" alt="image" src="https://github.com/user-attachments/assets/cb574534-1ed9-4cc1-8457-95a3d08ba575" />

I am not sure why an exception should be generated. Perhaps the error handling is incomplete.

Meanwhile, the exception can be ignored and the user should select one of the other options or correct the Regular Expression.

The error is also likely to occur when the Regular Expression option is selected unintentionally.

Vassal search would benefit from robust exception handling for the Regular Expression option to deal with this user error. Recurrent issues should be linked here and closed with user advice.

**Comment by riverwanderer** [comment]
Fixed by #13850.
