### ISSUE TITLE
[Liberté] IllegalArgumentException: Piece is not on this map

### ISSUE THREAD

**Issue by uckelman** [vassalengine/vassal#13651]
| ABR | |
|-----|-----|
| Version | 3.7.14 |
| Reporter | markben61@gmail.com |
| Error Log | [1203922 bytes](https://vassalengine.org/files/gh/1675d3f9e6d06116db9b1b2ae33cbd3cdc44ebf2) |

<pre>Ran through a log. Backed up (up do). Moved some pieces with in a map.

Liberté v1.0.11 3.7.14

java.lang.IllegalArgumentException: Piece is not on this map
 at VASSAL.build.module.Map.positionOf(Map.java:2577)
 at VASSAL.build.module.map.MenuDisplayer.maybePopup(MenuDisplayer.java:274)
 at VASSAL.build.module.map.MenuDisplayer.mouseReleased(MenuDisplayer.java:248)
 at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
</pre>

**Comment by BrentEaston** [comment]
Duplicate of #12033
